### ISSUE TITLE
Tried suggested fix but didnt work so opened ticket and advice was to test suggested fix

### ISSUE THREAD

**Issue by Epyx911** [LibreVR/Revive#188] opened 2016-07-04 01:18 UTC
Not trying to be a pain sorry for typing this again but didnt see another way to contact you privately.  I had tried the suggested entitlement fix and indicated that but the ticket was closed with the suggestion to try the fix lol.  

Any other things I can check?  

Again thanks in advance, MUCH appreciated.

**Comment by LibreVR** [comment] 2016-07-04 07:39
Why create a new ticket? You can just comment on the old one and I can reopen it if necessary.

Duplicate of #187.

**Closed by LibreVR** 2016-07-04 07:39 UTC
Labels: duplicate
