### ISSUE TITLE
Red Matter not loading

### ISSUE THREAD

**Issue by tkapis** [LibreVR/Revive#997] opened 2018-05-26 12:40 UTC
Red Matter hangs when loading the game on the Vive, using Revive 1.2.2.

**Comment by SimplexPL** [comment] 2018-05-29 17:30
I can confirm it on Revive 1.3.0.3 and current SteamVR beta. 
This is the error message:
![image](https://user-images.githubusercontent.com/25101733/40674791-1d5f42d2-6376-11e8-8419-a5b708287f2c.png)

This is reviveinjector.log

> Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe" /library "Software\vertical-robot-red-matter\HYPNOS\Binaries\Win64\HYPNOS-Win64-Shipping.exe"
Creating process: D:\Gry\Oculus\Software\vertical-robot-red-matter\HYPNOS\Binaries\Win64\HYPNOS-Win64-Shipping.exe 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0xb22ce090
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xb22ce090
Injected dlls successfully

**Comment by pacotaco40** [comment] 2018-06-02 10:08
the same.....oculus rift not found

**Comment by hybrid11** [comment] 2018-06-03 20:10
I haven't really heard anyone say that this even works on Revive to begin with.

**Comment by Hoshi82** [comment] 2018-06-11 18:31
So? Anything new?

**Comment by SimplexPL** [comment] 2018-06-11 19:34
CrossVR had a hardware failure, he lost GPU and mobo.

**Comment by Armada651** [comment] 2018-06-11 21:47
Yeah sorry about that the hardware failure caused a bit of a slowdown, I'll look at this tomorrow.

**Comment by Hoshi82** [comment] 2018-06-12 12:16
Oh ok didn't know that. :) I hope the issue can narrowed down and be fixed. This game is taunting me in my oculus library ;)

**Comment by Armada651** [comment] 2018-06-12 12:46
Okay, the problem is that Unreal Engine 4.18 is the first version that calls `ovr_WaitToBeginFrame` directly and it does so from the main thread instead of the render thread. This causes a crash in Revive since it incorrectly assumes `ovr_WaitToBeginFrame` is always called from the render thread.

**Comment by Hoshi82** [comment] 2018-06-12 16:07
Yay :) Hope it works out smoothly :)

**Comment by 4dos** [comment] 2018-06-24 14:44
Can u please ad a Patch for this little  Project. We waitung 4.

**Comment by SimplexPL** [comment] 2018-07-15 08:20
Any progress?

**Comment by Armada651** [comment] 2018-07-27 00:03
Should be fixed now: https://github.com/LibreVR/Revive/releases/tag/1.4.2

**Closed by Armada651** 2018-07-27 00:03 UTC

**Comment by dtdoan1** [comment] 2018-07-28 14:01
Thank you for all the support!  Got the error messages removed and into the sensor calibration for Marvel.  Does the WMR controllers work with this game?  I noticed some games auto detect and allow the WMR controllers to work, some do not pair.

**Comment by Hoshi82** [comment] 2018-07-28 16:03
Red Matter works! Thank you! YEAAH :)

**Comment by SimplexPL** [comment] 2018-07-29 12:39
Are you using the latest version of Revive?

**Comment by yappowins** [comment] 2018-07-29 13:40
Yeah, I uninstalled the old version and reinstalled the latest version.

**Comment by 4dos** [comment] 2018-07-30 17:57
Very good work guys, where i can send you some money? I use this cool software and want to bring back some for your work. (Red Matter & so on.) Very, very thank you. (Or email me.)
Good work, epsilon!

**Comment by Armada651** [comment] 2018-07-30 18:24
There's a Patreon link in the ReadMe: https://github.com/LibreVR/Revive/blob/master/README.md

**Comment by yappowins** [comment] 2018-07-30 23:05
Using the latest version of Revive, whenever I click Red Matter it now says oculus touch not detected, what am I doing wrong?

**Comment by Armada651** [comment] 2018-07-31 07:47
@yappowins Did you turn on the controllers? Are they tracked?

**Comment by yappowins** [comment] 2018-07-31 08:02
Yes they are connected and tracking, I should add that I am using a WMR headset but this shouldn't be a problem should it? If it does load it says oculus touch not detected, otherwise the game doesn't load at all. At this point I don't think my computer wants me to play the game all.

**Comment by Armada651** [comment] 2018-07-31 08:03
> I should add that I am using a WMR headset but this shouldn't be a problem should it?

Revive is designed for and tested on the HTC Vive, problems with WMR headsets are to be expected. I'm working on improving WMR support through Remixed, but that is still experimental.
