### ISSUE TITLE
xinput (Xbox controller) not working with Obduction

### ISSUE THREAD

**Issue by mapotter99** [LibreVR/Revive#372] opened 2016-12-12 16:21 UTC
I'm currently using Revive 1.03.

Xinput/Xbox controller will not work with Obduction patched with Revive, either in VR or in the standard desktop mode. 

I removed the patch files, and the Xbox controller worked fine. I re-patched, and it stopped working again. 

I'm currently using Windows 10 Pro x64, and it is fully updated.

I've read that Oculus runtime has caused some serious issues with the Xbox controller in the past. Not sure if it is related this time. 

For what it's worth, the controller still works fine with Lucky's Tale.

**Comment by LibreVR** [comment] 2016-12-12 16:24
So are you playing the Steam version of Obduction?

**Comment by mapotter99** [comment] 2016-12-12 16:29
Yes.

**Comment by LibreVR** [comment] 2016-12-12 16:46
There's probably something wrong with the XInput proxy built into Revive, this main also explain issue #348.

**Comment by Stoppablemurph** [comment] 2016-12-22 06:38
Same issue here. Would falling back to an older ReVive version fix it do you think?

**Comment by mapotter99** [comment] 2017-01-07 16:59
@LibreVR & @Armada651, you may already be aware, but 1.0.4 has not resolved this problem.

**Comment by Armada651** [comment] 2017-01-07 17:00
I am aware, it will be solved in 1.1.0. I'm going to get rid of the xinput proxy and use other means of injecting revive.

**Comment by Armada651** [comment] 2017-02-17 15:24
Closing this one as a duplicate of #399, it's the same exact issue.

**Closed by Armada651** 2017-02-17 15:24 UTC
