### ISSUE TITLE
Subnautica, Doesnt Save games and opening the menu crashes the game.

### ISSUE THREAD

**Issue by ZuckerBlatt** [LibreVR/Revive#191] opened 2016-07-06 10:34 UTC
When I open up the menu with the "start"-button everything is normal, but when I close it the cursor gets bugget and stays at the same location in the world. Also I cannot save the game. When I press "Save" and close the menu is gets bugged as described above and when I close the game and restart it, all saves are gone.

I really need some help here. I am new to revive and I will refund the game, unless I get a solution.

Yours sinserely, ZuckerBlatt

**Comment by LibreVR** [comment] 2016-07-06 11:01
Duplicate of issue #37.

Please refer to that issue for potential solutions.

**Closed by LibreVR** 2016-07-06 11:01 UTC
