### ISSUE TITLE
sticky grip an option?

### ISSUE THREAD

**Issue by AerowynX** [LibreVR/Revive#342] opened 2016-12-06 00:05 UTC
I noticed the touch is designed to hold their grip button but for the Vive doing that isn't very comfortable so like in bullet train was seeing if there was any way to add maybe a sticky grip so you hit the grip it holds the gun then grip again it lets go

**Comment by LibreVR** [comment] 2016-12-06 00:17
That's a pretty good idea, from what I've seen in other Vive games that seems to be the way most of them handle the grip button. I'll look into this tomorrow.

**Comment by AerowynX** [comment] 2016-12-06 00:18
you're the man!:)

**Comment by LibreVR** [comment] 2016-12-06 00:20
My only concern is that it may be confusing, because the Oculus Touch Basics tutorial would not explain this behaviour.

**Comment by AerowynX** [comment] 2016-12-06 00:31
i think most who are used to the Vive would have no issue figuring this out though since all the gun type games have a sticky grip... just doing one round of bullet train my grip was already tired ha. I couldn't imagine a full game like that

**Comment by MehStrongBadMeh** [comment] 2016-12-06 01:11
Mimicking the hybrid grip mode used in Raw Data may be a good way of handling this. I.E. Tapping the Vive grip holds the Touch grip until Vive grip is tapped again, but holding the Vive grip results in holding the Touch grip until the Vive grip is released.

**Comment by srt23** [comment] 2016-12-06 08:38
This would be great.

**Comment by LibreVR** [comment] 2016-12-06 17:41
Moving this to the next version so I can release an update for unspoken.

**Comment by SaulMalone** [comment] 2016-12-06 17:42
Would it be possible to have this be a big obvious toggle on the ReVive menu in VR? 

Maybe that would help make it clear to people what's going on with the change?

**Comment by LibreVR** [comment] 2016-12-06 17:51
@SaulMalone No, I think @MehStrongBadMeh had the right idea about how to implement it transparently.

**Comment by SaulMalone** [comment] 2016-12-06 17:52
Ah- I was just editing my comment (and maybe you already saw the edited part) - but you'll probably want to do *something* to make sure people understand the sticky grips exist, and games aren't just broken.

**Comment by LibreVR** [comment] 2016-12-06 17:56
I have another idea, how about I make the grip stick if you keep the trigger pressed?

**Comment by MehStrongBadMeh** [comment] 2016-12-06 17:59
Sounds kinda awkward.

**Comment by LibreVR** [comment] 2016-12-06 18:00
Yeah, nevermind.

Anyway this clearly needs to be an option. Which means I need to create an option menu. I'm going to have to postpone this to the 1.1 milestone then.

**Comment by LibreVR** [comment] 2016-12-06 18:01
However, I'll probably provide at least the toggle grip as an internal option for you guys in the next update. So you don't have to wait until I get around to implementing an options menu.

**Comment by MehStrongBadMeh** [comment] 2016-12-06 18:03
Fair enough, this feature would wreak havoc on games where the grip buttons are used for a purpose other than holding things. If you can make it so we can set it on a per-game basis, that would be an awesome bonus.

**Comment by LibreVR** [comment] 2016-12-07 15:51
Commit 56438592ec240b0514f8ae260ba39a351be9161e adds an option for a toggled grip.

Once version 1.0.3 is released you can turn it on by editing your `steamvr.vrsettings` and adding to following:

   "revive" : {
      "ToggleGrip" : true
   },

You may already have a "revive" section, in which case you can just replace that section.

**Comment by lghtanddrk** [comment] 2016-12-07 17:22
That could be a problem for some games like Ripcoil where you have to make a fist by holding the trigger, grip and A button.  It's awkward  enough making a fist to punch discs with the Vive controller but then unmaking a fist but be even more awkward.

Maybe the future of Revive would be that there's a settings option that lets you change button configurations before launching a game.  Maybe even lets you save custom configs.

**Comment by LibreVR** [comment] 2016-12-07 17:23
@lghtanddrk It's a hidden option right now, I don't plan to make this behaviour permanent.

**Comment by Oaxhachul** [comment] 2016-12-07 21:33
This is probably one place where the Touch controllers will always have a small advantage over the current Vive wands. But this simple solution already made it possible for me to play Zombie Riot comfortably which is honestly a lot of fun - and the tracking and roomscale issues with the game on the Rift seem to disappear when playing it on the Vive :-)

**Comment by nateev** [comment] 2016-12-10 09:14
The toogle grip seemed the best solution, but it's a pain in the ass to throw bullet in bullet train.  @MehStrongBadMeh solution seems the best, tooglegrip guns, hold and release for bullets !

**Comment by LibreVR** [comment] 2016-12-10 10:25
@nateev I still plan to implement hybrid grip, it's just that I was in a hurry and toggle grip was the easiest to implement.

**Comment by bales86** [comment] 2016-12-13 02:23
Still for the love of god can't get this to work by adding

 "revive" : {
      "ToggleGrip" : true
   },

It just wont work.

**Comment by Oaxhachul** [comment] 2016-12-13 07:45
Bales, I can confirm that it works, so you should be able to solve it somehow. I am running the Steam beta version, could that be it?

**Comment by nateev** [comment] 2016-12-13 07:50
I'm running stable steam version and the ToggleGrip is working.

**Comment by bales86** [comment] 2016-12-13 08:57
Im running steamvr beta too, dis you guys just copy and paste the commands into the steamvr.vrsettings file?

**Comment by nateev** [comment] 2016-12-13 09:17
Yes, maybe you have a code structure error in your file ?

**Comment by bales86** [comment] 2016-12-13 09:19
Hmm can you copy paste yours into a comment or screenshot it so I can what it should look like

**Comment by nateev** [comment] 2016-12-13 09:20
I'm at work, I (unfortunately :p)  don't have steam here

**Comment by Oaxhachul** [comment] 2016-12-13 09:23
Hi Bales - this is my entire vrsettings text. I did have a revive entry already which I overwrote with the sticky grip code. 

{
   "audio" : {
      "offPlaybackDevice" : "{0.0.0.00000000}.{350e3220-ceb6-4903-82e1-77fcb768e88d}"
   },
   "camera" : {
      "enableCamera" : true,
      "enableCameraForRoomView" : true
   },
   "keyboard" : {
      "TutorialCompletions" : 1
   },
   "modelskins" : {
      "stage" : "D:\\Steam\\steamapps\\workshop\\content\\250820\\686313792\\blake_aperturetower\\blake_aperturetower.obj",
      "stage_PublishedFileId" : "686313792"
   },
   "perfcheck" : {
      "warnInHMD" : true,
      "warnOnlyOnce" : true
   },
     "revive" : {
      "ToggleGrip" : true
   },
   "steamvr" : {
      "background" : "D:\\Steam\\steamapps\\workshop\\content\\250820\\676006590\\spacestation-interior-02.png",
      "basestationPowerManagement" : true,
      "mirrorViewGeometry" : "0 0 1080 600",
      "playAreaColor" : "#FFFFFFD1",
      "showStage" : true
   }
}

**Comment by LibreVR** [comment] 2016-12-16 17:24
Hybrid grip mode is implemented in e64e0c4279ba5302d7335361c7900717a6d7a4e6.

**Closed** 2016-12-16 17:25 UTC
Labels: enhancement

**Comment by lghtanddrk** [comment] 2017-01-07 19:29
Can you please tell me the correct line of code to put in if I wanted to make it so you have to hold the side button a little longer before the sticky grip kicks in?  I put the code in but must have done it wrong and all my settings got wiped from the file. Luckily I had a backup.  My hand is sticking to the shotgun when I try to reload in ZR Zombie Riot so I have to click a second time to let go.

Also what does QueueAheadEnabled do?  That's the only line I had in my revive section.

**Comment by Armada651** [comment] 2017-01-07 19:32
You should install OpenVR-AdvancedSettings, it has a Revive tab so you don't need to configure this manually.

**Comment by lghtanddrk** [comment] 2017-01-07 19:34
Where do I get that and/or how do I install that? Thanks.

**Comment by Armada651** [comment] 2017-01-07 19:34
Google is your friend: https://github.com/matzman666/OpenVR-AdvancedSettings

**Comment by lghtanddrk** [comment] 2017-01-07 20:39
Just installed it. Thank you. This makes it so much easier.

**Comment by lghtanddrk** [comment] 2017-01-07 20:40
Looks like I could create separate profiles for each game, right?

**Comment by Armada651** [comment] 2017-01-07 20:44
I think so, but you need to manually switch.
