### ISSUE TITLE
EVE VALKYRIE  " FATAL ERROR "

### ISSUE THREAD

**Issue by HonokaZhan** [LibreVR/Revive#280] opened 2016-10-09 09:10 UTC
When started EVE VALKYRIE Revive in Steam VR 

Then Black Screen And "FATAL ERROR" Message

I Used lateset version Revive

My OS Win 10 

How can i do ? 

# Reviveinjector Log

->
Launched injector with: ReviveInjector_x64.exe  /base Software\Software\ccp-games-newcastle-eve-valkyrie\Image\WindowsNoEditor\VkGame\Binaries\Win64\EVE Valkyrie.exe -oculus
Creating process: C:\Program Files\Oculus\Software\Software\Software\ccp-games-newcastle-eve-valkyrie\Image\WindowsNoEditor\VkGame\Binaries\Win64\EVE Valkyrie.exe -oculus 
Failed to create process

# ReviveOverlay Log

->

SetProcessDpiAwareness(2) failed: COM error 0xffffffff80070005  (Unknown error 0x0ffffffff80070005), using 2
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/Software/
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/bigscreen-bigscreen_assets.json
Loading assets manifest: file:///c:/Program Files/Oculus/Software/Manifests/ccp-games-newcastle-eve-valkyrie_assets.json

**Comment by LibreVR** [comment] 2016-10-09 11:06
Duplicate of issue #278.

**Closed by LibreVR** 2016-10-09 11:06 UTC
Labels: duplicate
