### ISSUE TITLE
Rock Band VR Closes on Launch

### ISSUE THREAD

**Issue by Dynedge** [LibreVR/Revive#572] opened 2017-04-16 16:14 UTC
I just installed and set up Revive yesterday so I could purchase Rock Band VR. I followed all the guides for setup and everything appears to be working, I was able to mess around with all the apps Oculus comes with without any issue so I bought Rock Band VR and now any time I try to launch it I see a black box open on my desktop and immediately close. I've tried to troubleshoot this myself already and have done stuff like opened steam and the Revive app in administrator mode and made sure I didn't have any other anti-virus programs blocking it. I've also restarted my PC and the oculus service many times since the install. I have the latest version of Revive (1.1.0.1) and I am not using SteamVR beta. 

Was wondering if there was something I'm missing since it's listed as working on the wiki.

**Comment by Armada651** [comment] 2017-04-16 16:57
If this is a Unity Engine game there should be a _Data directory that contains the file output_log.txt. Please upload it in the comment box here.

**Comment by Dynedge** [comment] 2017-04-16 19:02
I'm not sure what engine this game is running on but I located the .exe file inside of C:\Program Files\Oculus\Software\Software\harmonix-rockband-vr and wasn't able to find any _Date folders there or around there. I was able to find what looked to be some log files in C:\Users\UserName\AppData\Local\Oculus names stuff like PerfLog_2017-04-16_12.01.49 or Service_2017-04-16_12.01.42 but these are pretty long and I'm not sure if they'll be useful at all. 

In case it helps to know, I was able to launch the game to my desktop using the .exe from the folder I mentioned above and it said it didn't detect the HDM or controllers. I've also tried injecting the code directly into the .exe using the Revive app in admin mode and that didn't seem to help. 

Let me know if I should post those logs or if maybe I was just looking in the wrong place.

**Comment by Armada651** [comment] 2017-04-16 19:30
Can you try Revive version 1.0.6? https://github.com/LibreVR/Revive/releases/tag/1.0.6

Just install over your existing installation.

**Comment by darkphoenixfox** [comment] 2017-04-16 19:43
Same issue witn 1.0.6. Still getting the "empty" noise inside SteamVR, still crashing when running from the folder.

**Comment by Armada651** [comment] 2017-04-16 19:43
@darkphoenixfox You need to restart SteamVR.

**Comment by Armada651** [comment] 2017-04-16 19:46
Anyway, this issue is probably related to issue #569. The size of some structures changed and I didn't correctly account for those. I'm working on a fix.

**Comment by darkphoenixfox** [comment] 2017-04-16 19:52
Alright, I had restarted steam and steam VR already. Will keep an eye on the other thread. Thanks

**Comment by Armada651** [comment] 2017-04-16 19:53
@darkphoenixfox Still would like to know if 1.0.6 fixes the crash. Can you try starting Rockband VR from the Revive dashboard instead of the SteamVR one?

**Comment by darkphoenixfox** [comment] 2017-04-16 19:56
Inject: nothing happens
Patch and run: Seems that doesn't crash. Can't fully test now. Will test it later today

**Comment by Dynedge** [comment] 2017-04-16 20:58
Just installed 1.0.6 and was able to boot the game successfully! Having guitar issues but I have a feeling those are unrelated. Thanks for the help!

**Comment by Dynedge** [comment] 2017-04-16 21:58
Confirmed that the guitar issue was unrelated. Didn't have the active window set to the game. lol

**Comment by Armada651** [comment] 2017-04-16 22:08
@Dynedge That clearly points to issue #569 as the cause, will be fixed in the next release.

**Comment by darkphoenixfox** [comment] 2017-04-16 22:41
after installing 1.0.6 I can get in game, after I press the green button to start I'm kicked out back to SteamVR

**Comment by Armada651** [comment] 2017-04-17 01:35
New version is released: https://github.com/LibreVR/Revive/releases/tag/1.1.1

**Closed by Armada651** 2017-04-17 01:35 UTC
