### ISSUE TITLE
Ripcoil   (Error: "...Pending hardware issue..." + "Fatal Error") 

### ISSUE THREAD

**Issue by Vivatokyo** [LibreVR/Revive#441] opened 2017-01-04 09:08 UTC
![capture](https://cloud.githubusercontent.com/assets/24572116/21636977/3851e32a-d2a8-11e6-9c27-2e2d932502dd.PNG)

It could be the origin of FatalError Issue in a lot of games

**Comment by Armada651** [comment] 2017-01-06 15:50
You should restart your computer to fix it.

**Comment by Vivatokyo** [comment] 2017-01-08 14:38
Doesnt work, i get Fatal Error

**Comment by gh0st0fsparta** [comment] 2017-01-11 07:14
FWIW I'm seeing this same behavior with Ripcoil and VR Sports Challenge, whereas Superhot, Dead and Buried, IEYTD and Medium are all working fine.

I'm on version 1.0.4

I tried reinstalling Oculus runtime, reinstalling Revive with no success.

**Comment by Vivatokyo** [comment] 2017-01-11 09:05
Same bro :(
Superhot works amazinging well ;D Love Revive

https://youtu.be/w38bRZvFBss

**Comment by Armada651** [comment] 2017-02-17 15:39
Closing this issue as I can't reproduce it. Feel free to leave a comment here if you're still running into this issue.

**Closed by Armada651** 2017-02-17 15:39 UTC

**Comment by Vivatokyo** [comment] 2017-03-10 23:13
#gh0st0fsparta hi, could you fix the issue?

**Comment by Vivatokyo** [comment] 2017-03-10 23:14
@gh0st0fsparta hi, could you fix the issue?

**Comment by Vivatokyo** [comment] 2017-03-11 06:43
Ok I fixed it!
If you have Fatal Error problem do this:
1-Uninstall Revive
2-Uninstall completely Oculus software
Follow this https://www.youtube.com/watch?v=2WWrQncMNqs&app=desktop

(3-Install "Vive Setup" if you don't have it) *This one I don't know if it helps but it is what I did, I had only SteamVR and basic Vive drivers installed

4-Install Oculus Setup 
Create an account/sign in

When you are asked for 
  Rift or Rift&Touch 
SELECT RIFT&TOUCH! 

When they say plug the cables, skip

Once it is installed download Bullet Train
(In Oculus settings you also check allow unknown, I don't know if it helps...)

-Download and Install Revive

-Back to Oculus check if the game is downloaded then, go to settings, beta, restart... wait
Once restart you can close Oculus.

-Launch Revive program(.exe) and It ll launch also steamvr 
Put on ur Hmd 
Select Revive tab and Lauch Bullet Train

I hope it helps

I have to check the other UE4 games that gave me Fatal Error/Crash... But I think It will work
