### ISSUE TITLE
Missing icons in the launcher

### ISSUE THREAD

**Issue by SimplexPL** [LibreVR/Revive#983] opened 2018-05-14 09:49 UTC
If this is an issue on Oculus side, please close.

The ReviveOverlay.exe process which opens a list of tiles of all oculus games is missing icons on some of them, for example, Invasion, Witchblood and Wilson's Heart. Is there any way to fix it?

**Comment by Armada651** [comment] 2018-05-14 11:30
Duplicate of #956

**Closed by Armada651** 2018-05-14 11:30 UTC
