### ISSUE TITLE
Haptics not working in oculus touch first contact preview 

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#327] opened 2016-12-02 20:38 UTC
using pre-release 3, Are haptics supposed to be working in the oculus touch first contact OR tutoarial> demo? if so, they are not working and how do i get them to work? Thanks!

**Comment by LibreVR** [comment] 2016-12-02 20:55
It doesn't really look like the First Contact demo has haptic feedback. None of the haptic feedback function are called.

**Comment by CarrotSurvivor** [comment] 2016-12-02 21:11
maybe that is because its the pre release version of the demo? are there any touch games yet i can purchase to try ? or do i have to wait till dec 6 th

**Comment by LibreVR** [comment] 2016-12-02 21:12
The Oculus Avatar application is also available on the Revive dashboard, that one has haptics.

**Comment by LibreVR** [comment] 2016-12-05 23:25
I'll close this issue, as you've opted to report it again.

Closed as duplicate of #336

**Closed by LibreVR** 2016-12-05 23:25 UTC
