### ISSUE TITLE
Lucky's Tale Black Screen on desktop nothing in HMD

### ISSUE THREAD

**Issue by Osprior** [LibreVR/Revive#189] opened 2016-07-04 04:33 UTC
Hi,

I want to first thank you for all of your work, it's super amazing stuff.

Currently I'm seeing an issue with attempting to run LT through Revive, the app appears to launch, however it just sits there with a black screen, and nothing appears in the headset.

I've ensured that I've gotten Unknown Sources checked, and am fully updated on both Oculus Home (1.5) and Revive (0.8). I've also attempted directly running LT through the stand-alone injector with the same results. Here's my Injector.log file, from running it within the Revive dashboard:

> Launched injector with: E:\Games\Revive\Revive\ReviveInjector_x64.exe /base "Software/Software/playful-luckys-tale/LT.exe"
> Creating process: E:\Oculus\Software\Software\playful-luckys-tale\LT.exe 
> Injecting DLL: E:\Games\Revive\Revive\x64\openvr_api.dll
> LoadLibrary found at address: 0x140c4960
> Injecting DLL: E:\Games\Revive\Revive\x64\LibRevive64_1.dll
> LoadLibrary found at address: 0x140c4960
> Injected dlls succesfully

I'll attempt more troubleshooting tomorrow, however not sure what could be causing the issue. Running the game on it's own throws a no headset warning, which I expect without the injector.

**Comment by Osprior** [comment] 2016-07-04 04:40
Decided to give 0.7 a shot and it's working just fine in that version.

**Comment by LibreVR** [comment] 2016-07-04 07:39
Seems to be a 0.8 regression then, will give it a test.

**Comment by LibreVR** [comment] 2016-07-04 07:44
Confirmed, it's an issue due to the AirMech fix. I'll release a hotfix as soon as I have a solution.

**Comment by LibreVR** [comment] 2016-07-04 07:50
Fixed in commit f07d7dd7f03ac8e3f76d28d34889ad125133c7ed.

**Closed by LibreVR** 2016-07-04 07:50 UTC

**Comment by LibreVR** [comment] 2016-07-04 08:06
A new hotfix has been released, please update to version 0.8.1.
