### ISSUE TITLE
Super Hot VR Problem (Game only starts on my desktop)

### ISSUE THREAD

**Issue by Blue283** [LibreVR/Revive#510] opened 2017-02-22 10:57 UTC
Hello guys and girls,

my problem is tha every time i try to launch the game over Revive it just stats on my Desktop.
I already rebooted my Computer twice but still the same Problem.
If someone knows how to fix it would be great.
If someone want to help me with it my Steamname is ''Blue283'' 
(I'm sorry for the bad english but it isn't my nativ laguage)

**Comment by Armada651** [comment] 2017-02-22 10:59
@Blue283 Please read my reply before opening an issue report, I'm notified of every comment on the repo so no need to make multiple posts.

> You're running into issue #478. Unfortunately the SteamVR update broke the Revive dashboard. Try starting Superhot from Steam, it should be in your library when you have SteamVR running.

Closing as duplicate of issue #478.

**Closed by Armada651** 2017-02-22 10:59 UTC
