### ISSUE TITLE
Xinpu1_4.dll missing :- ( 

### ISSUE THREAD

**Issue by Dariusz1989** [LibreVR/Revive#27] opened 2016-04-21 20:51 UTC
Cant start Pcars because the dll listed above is missing... what to do ? 

Win 7 x64 + Vive. 

Please will there be support for Win7? I dont want to use win 10 spy system :- ((

**Comment by LibreVR** [comment] 2016-04-21 21:04
There will be Windows 7 support in the next version, this issue is a duplicate of issue #4.

**Closed by LibreVR** 2016-04-21 21:04 UTC
