### ISSUE TITLE
Minecraft VR

### ISSUE THREAD

**Issue by TheFlyingFishy** [LibreVR/Revive#1198] opened 2019-04-07 08:36 UTC
My Problem is when i downloaded minecraft VR on the Oculus store, it crashes after like 5 seconds of saying "Launching"
I do have a Microsoft account and its synced, because i got it up and running once.
I launch the game in SteamVR via Revive.
From what i can tell its a common problem that got fixed once in 2016. But its back.

SPECS:

Corsair TX750M, 750W PSU

Intel Core i7-8700 Processor

Cooler Master Hyper TX3i Komplett Ed.

ASUS ROG Strix B360-F Gaming, S-1151

2x HyperX Fury DDR4 2666MHz 8GB

ASUS GeForce GTX 1080 ROG Strix Gaming

Samsung PM961 SSD 256GB M.2 NVMe

2x Seagate Firecuda 1TB 3.5'' SSHD

Windows 10 Home OA 

Lenovo Explorer

**Comment by Armada651** [comment] 2019-04-07 17:02
Duplicate of issue #230.

**Closed by Armada651** 2019-04-07 17:02 UTC

**Comment by mikeonator** [comment] 2019-07-09 14:35
> Duplicate of issue #230.

I can tell you get this question quite a lot, but I just wanted to know if you've just marked the problem as impossible and moved on, or if there's an actual chance of eventual compatibility with Minecraft VR?

**Comment by Armada651** [comment] 2019-07-09 22:40
There is a chance it will happen with OpenXR eventually, but it's never going to happen with OpenVR.
