### ISSUE TITLE
The Unspoken broken after new update

### ISSUE THREAD

**Issue by mikegomak** [LibreVR/Revive#480] opened 2017-02-03 10:58 UTC
The Unspoken pushed a new update including new maps 4 days ago and will not launch anymore using any method. Any advice appreciated. I did have jittery performance issues with it before, mainly during the intro and training round.

**Comment by Werbel** [comment] 2017-02-03 11:08
Hi there!

I have updated Revive to latest version and it launched flawless (had crash on previous version).

I have issue during game instead - tracking is way off, world (and chaperone!) acts weirly - it tracks but with delay or something like that - it's bad and unplayable because of it.

**Comment by Armada651** [comment] 2017-02-03 11:25
I'm on a vacation until the 13th of February, I probably won't be able to look at this problem until then unfortunately.

**Comment by mikegomak** [comment] 2017-02-04 09:34
Enjoy your hols and thanks for letting me know. I'll update here if any problems persist for me after I update revive to newest version.

**Comment by Werbel** [comment] 2017-02-04 21:49
@Armada651 I gather more information about this issue with tracking.

It affects only pitch/roll/yaw of headset, doesnt affect positional movement and it's just for head. Any settings i can try meantime?

I've heard about more people with problems to run game and it keeps crashing/hanging before anything shows up.

Hope it's helpfull!

**Comment by SkywardEntertainment** [comment] 2017-02-05 17:29
@mikegomak When the same thing happened to me I knew what to do to allow me to play it again.
Here is how I did it in a step by step format.

1. Go to the Oculus folder, it should be in "Program Files" or "Program Files(x86)" in the Local Disk, mine is in Program Files.

2. Once you get to the Oculus folder open the software folder and inside that folder is another folder called software inside it that you need to open.

3. Open the folder that says "insomniac-games-the-unspoken" then open "game."

4. Go to the Revive folder and make a shortcut for the "ReviveInjector_x64."

5. Put the "ReviveInjector_x64 - Shortcut" file inside of the "game folder."

6. Find the "i24.exe" file and drag it on top of the "ReviveInjector_x64 - Shortcut" file.

7. Viola!

**Comment by Werbel** [comment] 2017-02-05 17:41
/\ it helps for app crash, does not help for tracking issues (i know you know Skyward ;) ).

**Comment by mikegomak** [comment] 2017-02-05 18:07
When I updated to the newest version of revive means I can start the game now - even the updated version - but I still can't play it as it's dropping too many frames and is too juddery when moving my head even on my good spec PC :( absolutely gutted as i would love to play this game. All of the other Oculus titles I play through revive work perfectly

**Comment by Werbel** [comment] 2017-02-06 16:09
@mikegomak 

You should not report an issue if you not updated program to the newest version - it causes misunderstanding, IMHO.

About that dropping frames - are you SURE, its dropping frames? Not tracking issue with HMD orientation only? It does not affect tracking if i move without changing my head rotation, just position. Can you see dropped frames via steamvr?

**Comment by mikegomak** [comment] 2017-02-07 18:34
@Werbel - Yes, agreed - sorry for reporting before updating.

I have tested again today and definitely is skipping frames, a lot - reported in the console and popup in the headset I am quite sensitive to the motion sickness too so Its completely unplayable for me.

Just FYI Im running a HP Omen i5, Nvidea 1060 with 8M ram and the whole lot is saved on SSD so I should be able to run on Highest settings without problems. All drivers are fully up to date too.

If I can capture any log files that might be able to help when you return from your vacation please let me know.

Thanks Again

**Comment by Werbel** [comment] 2017-02-15 18:30
@Armada651 
Just a friendly reminder here! Hope your vacation was great!

I was able to play some rounds of Unspoken with that tracking issue and i'm sure it's there and it's just related to rotation/orientation of headset. It does not affect controllers or positional movement.

Hope you can fix it!

Best wishes!

**Comment by Chupacabra1989** [comment] 2017-02-15 21:35
i got the same problem here -.- got a 1080 and i got massivley frame drops only in my favorite game unspoken. unplayable i dont know why. changed everything in rendering and graphic options.  please fix this :/

**Comment by mikegomak** [comment] 2017-02-16 00:03
I have just seen The Unspoken running on OR with a much lower spec PC than mine and frankly it looks incredible. As @Chupacabra1989 said it seems the most polished VR game ever. Please let me know if I can offer any log files etc to help the process. Also, really appreciate that this is a labour of love. Where can I donate to the development? Thx

**Comment by Werbel** [comment] 2017-02-16 03:01
I'm also having frame drops problems with gtx1070 and decent cpu and ram. Not on every map, but it's kicking hard.

**Comment by mikegomak** [comment] 2017-02-16 04:30
So far, issues raised seem to be with Nvidea cards only. I have personally had some issues with games using the Unreal engine too (mainly launching and exiting) perhaps this is an Nvidea specific issue? Is that worth exploring?

**Comment by Strongpillow** [comment] 2017-02-16 06:38
The tracking on the headset is way off for me. It's like parts of it follow my gaze or the world moves in the opposite direction? I couldn't stay in it for long so I can't say exactly. All I know is that it looked really odd and bothered me fast. 

I have a gtx 1070, i5 6600, 16gb ram. It's a brand new computer that I only use for VR.

**Comment by Chupacabra1989** [comment] 2017-02-16 08:03
by the way i got a rx 480 in my computer before and it works fine seems really to be a nvidia problem -.- i use actual drivers for the 1080 maybe i should try an older version ?

**Comment by Armada651** [comment] 2017-02-16 12:24
I'm currently focusing on getting The Climb fixed. I will look into this issue as soon as I've fixed The Climb, please bear with me.

**Comment by Chupacabra1989** [comment] 2017-02-16 17:09
thank u very much of course :) where i can donate for you ? :D by the way for all others i figured out when in steam vr options in performance i signed both reprojections i got no more framedrops warnings but its still stuttering in movement. maybe this helps to find a fix :) best regards to community and thanks for all

**Comment by mikegomak** [comment] 2017-02-16 17:11
Thank you for keeping us updated. I would like to clarify that I have had the performance issues only with The Unspoken and in all versions of Revive, not just the newest version. Hope that aids understanding.

**Comment by Strongpillow** [comment] 2017-02-16 17:13
No rush @Armada651 I just wanted to let whoever know that I am experiencing issues with this game also. I am eager to play it but have no issue waiting patiently. Revive team = Gods!

**Comment by mikegomak** [comment] 2017-02-16 17:18
@Chupacabra1989 Regarding "I signed both reprojections" can you clarify for me exactly what you did and to which settings so I can also try please? If you have some optimised settings that would also help. Thx

**Comment by Chupacabra1989** [comment] 2017-02-16 17:22
yeah of course bro when u start up your steamvr then u go in the settings( not in steam only steamvr) and then choose options and performance on the right side u can activate both reprojections the framedrops are gone now but its still stuttery but now i think its not a problem from nvidia. maybe u can also try this and report :)

**Comment by Armada651** [comment] 2017-02-17 11:11
I got stuck with The Climb, so I've started to take a look at The Unspoken. I can't reproduce any issues trying to launch it, that seems to work fine. I can reproduce the tracking latency and this is where the new profiler I've built into Revive comes in handy:

![clipboard01](https://cloud.githubusercontent.com/assets/2028870/23063168/5f6f01ee-f509-11e6-88e3-023284d21024.png)

What's happening here is that `ovr_GetTrackingState()` is being called before we've finished submitting the frame. This is something Revive does not account for and it will return tracking information from the previous frame if that happens, which introduces at least an extra frame of latency.

There are two options to fix this: either I block `ovr_GetTrackingState()` while we're submitting a frame with a simple mutex. Or I allow `ovr_GetTrackingState()` to be called early and I use prediction to fix the issue. I'll probably go with the mutex option, as prediction should only be used as a last resort.

**Comment by Armada651** [comment] 2017-02-17 11:50
Ok, that's fixed in commit e43db8160a60131f6df93ec21d2f5f10eb83af7e. That will be part of the next release.

There still seems to be about one frame of latency, but that latency seems to affect multiple games not just The Unspoken.

**Comment by Chupacabra1989** [comment] 2017-02-17 12:40
u guys just awesome love u.  and yes armada this problem is in many games also in dead and buried. thanks for working on it <3

**Comment by mikegomak** [comment] 2017-02-17 13:41
@Armada651 is there a way I can give this a try or do I need to wait for the next release. Apologies if this is an ignorant question but I am new to this and don't fully understand terms like "commit" or how to work with the newly updated files. Thx again.

**Comment by Armada651** [comment] 2017-02-17 14:51
@mikegomak If you're not familiar with how to compile software you need to wait for the next release.

**Comment by Strongpillow** [comment] 2017-02-17 16:20
Thanks for taking a look @Armada651 Definitely excited for the new update. Unspoken looks awesome.

**Comment by mikegomak** [comment] 2017-02-17 16:56
Thanks for your work on this - awesome!

**Comment by Armada651** [comment] 2017-02-18 16:03
I've found the issue in The Climb and it also affects this game as expected. Both games consistently request tracking data one frame ahead of the frame they are supposed to render. This is causing the extra frame of tracking latency that's visible in those two games.

**Comment by Chupacabra1989** [comment] 2017-02-18 16:16
i love u :D cant await this fix

**Comment by Armada651** [comment] 2017-02-18 16:19
Well, I can never truly fix that, I have to resort to tracking prediction and that can never be truly accurate. However, this prediction would also happen on the Oculus Rift as the game is explicitly requesting it in this case.

I get the feeling these games may be cheating a little to get around a CPU bottleneck in their games.

**Comment by Chupacabra1989** [comment] 2017-02-18 16:27
im not a big pro in what u are doing but i trust in u :D cant believe whats really wrong with this game. i got a rx 480 it worked in low settings without SS really fine. upgraded to gtx 1080 and its unplayable

**Comment by mikegomak** [comment] 2017-02-22 18:11
@SkywardEntertainment - I'm having the same problem again and have done all the steps you mentioned above apart from the last one....

Find the "i24.exe" file and drag it on top of the "ReviveInjector_x64 - Shortcut" file.

I cannot find it. Advice appreciated.

**Comment by Armada651** [comment] 2017-02-22 21:13
I'll be tracking the second part of the tracking latency issue in ticket #512.

**Closed by Armada651** 2017-02-22 21:13 UTC

**Comment by mikegomak** [comment] 2017-02-22 22:36
Thanks for the update.

I can confirm no skipped frames anymore so it's a little slicker, but the tracking issue is too severe for me to be playable as I'm a bit too sensitive to it. Thanks again.
