### ISSUE TITLE
AirMech Command

### ISSUE THREAD

**Issue by LuckDragon82** [LibreVR/Revive#961] opened 2018-04-12 00:12 UTC
the Steam VR shows the game as flashing between playable and unresponsive. Inside the headset it flashes between the game and the loading screen. 

Out of curiosity are games supported on steam still going to receive support on here? Thank you for this awesome program.

**Comment by LuckDragon82** [comment] 2018-04-14 23:50
I updated to latest everything (even reinstalled oculus home and revive to be sure). Still doesn't seem to work. It alternates between the game and an error that says the rift is disconnected please reconnect.

**Comment by Armada651** [comment] 2018-04-15 13:31
Which headset are you using?

**Comment by LuckDragon82** [comment] 2018-04-16 01:05
HTC Vive (not the pro)

**Comment by Armada651** [comment] 2018-04-18 11:40
This is interesting, there's some sort of race condition here that causes AirMech Command to skip a frame and then submit the same frame twice. So it will submit frames in this order:

1, 2, 3, 5, 5, 6, 7, etc.

I'm not sure whether this is a bug in the game or whether Revive should be forcing the game to run slower. In any case the tracking in that game is a bit jittery due to the frame skip.

**Comment by LuckDragon82** [comment] 2018-04-18 12:04
Hmm. On mine its more than just jittery. In the vive it flashes between the loading screen and the game constantly. On the computer monitor it flashes between the game and the error saying it can't find an occulus rift. How odd. Wonder if something specific to my setup.

**Comment by Armada651** [comment] 2018-04-18 12:56
Oh sorry, forgot to mention that I also reproduced that error, but it was an easy fix, it's related to the frame submission order though.

I actually figured out why it happens though. This game relies on the fact that a call to `ovr_GetSessionStatus` takes 0.027ms with the original Oculus Runtime. However because I spent a lot of time optimizing Revive that call now takes 0.009ms with Revive causing the game to desynchronize.

That indicates bad programming on the part of the game. There are plenty of other issues with this game too such as getting the new headpose before the runtime finished submitting the frame. This adds a lot of latency and makes the experience uncomfortable.

Fixing this game completely will require some game-specific hacks.

**Comment by Armada651** [comment] 2018-04-18 13:42
Fixed in these commits: https://github.com/LibreVR/Revive/compare/7f4093a6dd05...9eab91cc34aa

Will be part of the 1.3.1 release.

**Closed by Armada651** 2018-04-18 13:42 UTC

**Comment by LuckDragon82** [comment] 2018-04-18 23:27
ah ok, I guess I'll keep an eye out for a steam sale :) Thanks for looking into it. Thanks for revive too!

**Comment by LuckDragon82** [comment] 2018-04-18 23:28
oh awesome. I just saw the fix. Thank you

**Comment by Armada651** [comment] 2018-05-08 10:03
New version has been released, please test it.
