### ISSUE TITLE
Haptics are not working in Pro Fishing Challenge VR and First Contact

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#336] opened 2016-12-05 22:27 UTC
I tried the free fishing game on oculus home, and the haptics do not work :( also, no way there are no haprotcs in the tutorial... something must be wrong

**Comment by CarrotSurvivor** [comment] 2016-12-05 22:29
Unless that game really had no haptics.. which would be stupid

**Comment by LibreVR** [comment] 2016-12-05 22:48
I really need some feedback from an actual Oculus Touch user, because I've debugged the Oculus Tutorials and they really don't seem to even attempt to use any of the haptics functions. Not even the functions used to detect whether haptics are supported.

**Comment by AerowynX** [comment] 2016-12-05 23:34
is pro fishing actually going to the fishing part for you? i point and touch the tablet but nothing happens

**Comment by frank707** [comment] 2016-12-06 05:44
You have to hover over the buttons in pro fishing so they show as highlighted before attempting to press them.

**Comment by LibreVR** [comment] 2016-12-07 12:36
At least one user on Reddit confirmed there are haptics in First Contact. I will examine it more thoroughly.

**Comment by AerowynX** [comment] 2016-12-07 12:38
Haptics work on bullet train

**Comment by LibreVR** [comment] 2016-12-07 12:59
@AerowynX I do know the Haptics work, combined with the fact that the relevant functions are never called I didn't expect First Contact to have haptics.

**Comment by LibreVR** [comment] 2016-12-07 15:15
Found the problem, there's a strange bit of code in the Unreal Engine source code that checks this:

`(ovrControllerType_Touch == OvrInput.ControllerType) != 0`

What this means is that *only if* both Touch controllers are connected will it even attempt to use any haptic feedback. This means that it won't give haptic feedback if an Xbox controller or Oculus Remote is active.

**Comment by LibreVR** [comment] 2016-12-07 15:40
Fixed in fec0963a8ca4a021f0c4f09e3ad55999a2e26274.

Will be part of the next release.

**Closed by LibreVR** 2016-12-07 15:40 UTC
