### ISSUE TITLE
Minecraft 10 edition doesn't get past loading the desktop application, but the VR side/application works perfectly

### ISSUE THREAD

**Issue by pat277** [LibreVR/Revive#505] opened 2017-02-19 16:39 UTC
its useless though as the VR application needs to launch the desktop version. BUT at the very least Minecraft 10 edition VR does accept Xbox 360 input PERFECTLY regardless of it loading, so that's better than nothing.

**Comment by Armada651** [comment] 2017-02-19 17:02
Duplicate of issue #230.

**Closed by Armada651** 2017-02-19 17:02 UTC
