### ISSUE TITLE
Dirt Rally Not Working On VR, But On PC - VIVE

### ISSUE THREAD

**Issue by haleychavez90** [LibreVR/Revive#887] opened 2018-01-05 02:51 UTC
I have the HTC Vive. I spent hours trying to get Dirt Rally to work on my Vive. I followed all the directions to a tee. I even have Revive 1.1.11 downloaded. I can get it to play on my PC, but not in my Vive headset. I am honestly not sure what more to do. I read forum after forum, tried this and that. No luck! I am hoping someone could point me in a direction to making this work in my headset. I have Windows 10, if that makes a difference with anything.

**Comment by Armada651** [comment] 2018-01-05 03:18
Do you have Oculus Home installed?

**Comment by haleychavez90** [comment] 2018-01-05 03:28
Yes, I do have Oculus Home installed. I do have an Nvidia GeForce GTX 1060. Am I supposed to download something different for that? I am reading forum after forum so I do not have to aggravate you. I am just running out of options.

**Comment by haleychavez90** [comment] 2018-01-05 23:06
This explains my situation. I saw this on another forum and it is perfect to my situation..
I installed oculus home, setup, signed in. I installed revive. I copied two x64 exes from revive to the dirt game folder. I've turned off run in Theatre mode. I have steamVR started. I have tried dragging the dirt.exer onto the reviveInjector.exe and the console flashes up for a second and that's it. Or I can launch the game from steam, get a warning that it wont work in vr, and then it runs on my monitor. Please help! Any of the tutorials I've seen have been over a year old :/ I've tried right clicking the revive icon and running both patch and inject on the drt.exe but neither seem to do anything. If I click the Revive icon in the headset, I get a blue popup window with some default oculus apps, but Dirt Rally is not shown there... any advice would be appreciated.

**Comment by Armada651** [comment] 2018-01-05 23:37
Did you follow these instructions? https://github.com/LibreVR/Revive/wiki#steam-games

**Comment by haleychavez90** [comment] 2018-01-05 23:47
Sure did, like 50 times.

**Comment by Armada651** [comment] 2018-01-05 23:52
I plan to revisit the Steam version of Dirt Rally sometime, the patching functionality isn't working for everyone right now.

If you absolutely can't wait you can buy the [Oculus Home version of Dirt Rally](https://www.oculus.com/experiences/rift/992124094188963/) which works through the Revive dashboard out of the box and doesn't require patching.

**Comment by Armada651** [comment] 2018-01-05 23:56
One more thing you could try is installing the DirectX runtime: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by haleychavez90** [comment] 2018-01-06 00:07
Thanks. Got a new steering wheel. I'll buy it through Oculus Home because I am impatient. Appreciate it.

**Comment by raffi100** [comment] 2018-01-06 06:30
Thanks for the update armada. I look forward to seeing the patching functionality working again for Steam DR.

**Comment by JustDisgustiD** [comment] 2018-01-06 18:03
I had the same issue after buying Dirt about a week ago. I've just installed an older version of Revive where is still works. Runs well for me - not using Revive for any other games so not sure if there would be any problems there.

**Comment by crzyeyz** [comment] 2018-01-14 05:30
So i just found a fix and allows you to just inject the game file. I was originally trying to fix the stupid press y on your controller. One suggestion was to run vrdashboard in admin. When i did this steamvr was closed. Vrdashboard was found in program filesx86/steam/steamapps/common/steamvr/bin/win32
So anyways out of desperation on trying to get dirt running and failing on atleast getting rid of the message inside steamvr i tried to inject dirt once more despite seeing numerous posts saying injectong it didnt work anymore and boom. It worked, played for a bit then tried to repeat to figure out what i had done to get it working lol im using to 1.2.0.6 version of revive

**Comment by crzyeyz** [comment] 2018-01-14 05:32
Also should note im playing it through riftcat beta 2.0 on my gearvr. I just connect vridge up to riftcat and dont start steamvr from riftcat instead i go to that vrdashboard file an run in admin. That

**Comment by crzyeyz** [comment] 2018-01-14 05:34
Also the patch files didnt work for me so i removed them from the dirt folder.

**Comment by crzyeyz** [comment] 2018-01-14 05:35
Arg sorry for the mass comments, its 130 in the morning and wanted to get this up before i passed out. I am running 1.23? Of the game i think? Lol

**Comment by octatone** [comment] 2018-01-15 21:17
Followed the instructions to a tee. Oculus home installed and store is accessible. Launching Dirt with theater mode disabled just gives the steam warning that VR is not supported and it launches to the desktop.

**Comment by raffi100** [comment] 2018-01-19 02:24
Just got it working for me. Order of things I did:
1. Exit Steam and SteamVR (make sure it's not showing in task manager)
2. Start vrdashboard manually (there is another thread about it discussing it)
3. On the revive dashboard, inject drt.exe.
4. On the revive dashboard, patch drt.exe.
5. Start steam/steamVR.
6. Open dirt and ignore the (VR is not supported BS).

Not sure which version I'm running (not home right now).

**Comment by tkf144** [comment] 2018-01-20 00:53
Can confirm the above steps work with Revive 1.2.0, without Oculus Home installed (only the LibOVRRT32_1.dll and LibOVRRT64_1.dll libs present in Dirt Rally directory).

**Comment by syberphunk** [comment] 2018-01-21 22:18
> LibOVRRT32_1.dll and LibOVRRT64_1.dll
@tkf144 Where are these files sourced from? They're not in the Dirt Rally folder by default.

**Comment by tkf144** [comment] 2018-01-21 22:27
@syberphunk Begin the Oculus Home install and check C:\OculusDownloadCache (or similar - can't remember). There will be an OculusRuntimes.zip (or similar) folder which contains these libraries. Put them in your Dirt Rally directory alongside drt.exe.

As for vrdashboard.exe, open Steam and look at the properties for SteamVR - from memory there's a button that will open the install location.

**Comment by syberphunk** [comment] 2018-01-21 22:39
@tkf144 
For the sake of documenting for anyone else that finds this thread:
steam\steamapps\common\OpenVR\bin\win32\vrdashboard.exe

**Comment by syberphunk** [comment] 2018-01-21 22:56
It appears uninstalling oculus home and copying the runtime DLLs into the game folder are what make this game work as I'm now able to play it also.

However alignment is all over the place as there doesn't seem to be any room location co-ordination. I had to physically move myself to sit anywhere near the drivers seat of the car, and I had to take the headset off to be able to see the menu screen as it was so far away from me and the headset.

**Comment by Armada651** [comment] 2018-01-22 00:02
@syberphunk You can re-align the game by pressing Ctrl on your keyboard. You can also reset your seated position using the SteamVR settings.

**Comment by Kiefy** [comment] 2018-01-22 22:29
There is some kind of bug where the menu is stuck in the floor. Ctrl or w/e key is bound to reset hmd doesn't help. it adjusts the theatre-like grey dome and seating position when in the race fine, but nothing is getting that menu out of the floor. so I have to remove HMD or go into SteamVR Desktop mode to operate the menus.

**Comment by Armada651** [comment] 2018-01-22 23:42
@Kiefy If it's just the menu, then I think this commit will fixes it: f81a06f11ee0253c9978894fb7ad56cdf5a4714a

Will be part of the next release.

**Comment by Armada651** [comment] 2018-01-28 17:39
@Kiefy Can you try the latest 1.2.1 release?

**Comment by Easy-J** [comment] 2018-01-30 22:16
I can confirm that it works on the latest release! Great job!

**Comment by Kiefy** [comment] 2018-01-31 21:28
@Armada651 Yes. 1.2.1 has solved the floor menu issue. Thanks!

**Comment by silelmot** [comment] 2018-02-17 19:58
Hello there. i have the newest revive patcher and tried dirt rally today. it starts, i have to ignore the oculus-warning.. than start the game and a race from desktop (in the vive i am only inside a grey ball?) and than i see the starting line in vr and my car is ready to start. but i cant switch into the headset. i stay beside the car and can do nothing. ... any help needed!

**Comment by ajsw78** [comment] 2018-02-23 07:09
please guys help me out...I have sent so many help post already about getting my steam version of dirt rally working...I finally found out about the hiding icon of the revive icon on the bottom right hand corner of the screen...I press patch and the game bring me to a menu with all the games listed that could be patched that I bought from steam...and I click on dirt rally exe and I am not sure if i does anything...I went back to the tool bar thingy and tried to inject but nothing worked...Ive done the steps so many times...please guys help me out...i am using the version 1.2.1.0

**Comment by BazzaLB** [comment] 2018-03-17 09:45
Fantastic! Followed raffi100's instructions and Dirt Rally does indeed work perfectly with 1.2.1 release. Brilliant! Runs miles better than 1.1.14.

**Comment by ajsw78** [comment] 2018-03-17 12:59
Thank you for the reply...but i followed the instruction...but instead of
c:and programx86 i when to d: that is where i installed my steam
files...and i saw all the files until bin 32...i dont understand what do
you want me to do next...did you want me to double click on the steamvr exe
on that so i can get the revive working pls...you got give me instructions
like an idiot...

**Comment by ajsw78** [comment] 2018-03-17 13:06
Oh made a mistake i mean i double clicked on vr dashboard..but it did open
up and i saw it open on hindden files i right clicked inject it brought me
to files where my games were...i clicked on dirt rally then what...did i do
a step wrong

**Comment by gsxryan** [comment] 2018-05-13 03:16
Couldn't get this to work in 1.3.0, reverted back to 1.2.1 and it works fine.

**Comment by luzat** [comment] 2018-08-06 10:56
While I have previously not had success with versions > 1.1.11.1, I can confirm that patching drt.exe for some reason, starting Steam and SteamVR and next DiRT Rally while ignoring the "will run on desktop" warning works with current Revive 1.4.2.0.

**Comment by ajsw78** [comment] 2018-08-22 04:10
I was able to get it to work...since there are multiple versions on revive
you gotta make sure its not a beta version..and it will work..id play my
game right now..problem is now oculus rift setup is having problems and its
not allowing the setup to finish

**Comment by TripRodriguez** [comment] 2018-08-30 05:33
Hey guys, just wanted to say thank you to Raffi100 , tkf144, and others for putting these instructions out there.  

I use a motion sim and Oculus Home doesn't work with the SteamVR motion cancellation plugin by MatzMan666 .  I didn't expect to be able to play this, but with this technique (Oculus Home uninstalled, just using the DLL's) it works perfectly!

**Comment by ajsw78** [comment] 2018-08-30 09:05
Sir how did you just use the oculus dll can you explain it in a non
computer way....i rebooted my computer and now im trying to reinstall
oculus but the install isnt finishing..so mayby you dll techinic my help me
out pls

**Comment by qlyoung** [comment] 2019-10-10 04:54
Sounds like everything is fixed from a Revive perspective here. Please open a new issue if you're having similar problems.

**Closed by qlyoung** 2019-10-10 04:54 UTC
Labels: bug, regression, revive
