### ISSUE TITLE
Oculus Medium - Unable to initialize Oculus Rift

### ISSUE THREAD

**Issue by Dudeinparadise** [LibreVR/Revive#1249] opened 2019-07-06 03:46 UTC
### Description of the issue
When trying to run Oculus Medium I get an "Unable to initialize Oculus Rift error.

### Technical Information
*Tell us your specs and versions*
  - CPU: i7-8700k
  - GPU: GTX-970
  - RAM: 16gb
  - OS: Windows 10
  - Vive 

#### Versions and features
*This issue is about:*
  - Tried 1.6.4, 1.4.1, and the latest pre-release
  - SteamVR version (unless Remixed): Beta

### What apps/games are you trying to run?
  - Oculus Medium

## How to reproduce your issue?
It happens every time I try to open Medium in revive.

**Comment by Harpaxia** [comment] 2019-07-06 04:01
[Here's](https://github.com/LibreVR/Revive/issues/1244) a link to a thread also discussing this, if you stay updated to the replies they'll notify you when it's patched. It's a common occurrence when there's a new update - best bet is to disable auto-updates incase Revive needs to catch up.

**Comment by Dudeinparadise** [comment] 2019-07-06 17:29
Thank you!!

**Comment by Armada651** [comment] 2019-07-07 10:22
Duplicate of #1244

**Closed by Armada651** 2019-07-07 10:22 UTC
