### ISSUE TITLE
Oculus Medium 1.3.2 patch doesn’t display in HMD

### ISSUE THREAD

**Issue by routb3d** [LibreVR/Revive#842] opened 2017-12-06 00:42 UTC
I just tried the updated Oculus Medium. Medium launches and displays on the monitor but not in hmd. It also looks as though the HTC Vive controls are not present in Medium.

**Comment by ilanvfs** [comment] 2017-12-06 02:09
Same thing happened to me. Really frustrating was looking forward to some relaxing time sculpting and I don't see anything in the HMD nor do I see my controls but it's working on my computer screen.

**Comment by Armada651** [comment] 2017-12-06 02:11
Oculus Medium may have switched to a new layer type that Revive doesn't support. I will look at it tomorrow.

**Comment by quarzon** [comment] 2017-12-06 06:42
Hey there, just wanted to chime in and say that I'm having a similar experience. I'm able to see Medium 1.3.2 working in the headset (default opening scene with a sphere) but I cannot see the wands/controllers. (I do see the controllers when navigating in other programs.) Thank you for looking into this for us!

**Comment by mm373** [comment] 2017-12-06 07:18
+1 is there any way to revert to previous updates?

**Comment by theoneonlykid69** [comment] 2017-12-06 09:47
Same here

**Comment by Armada651** [comment] 2017-12-06 13:59
I am not able to reproduce the problem with the latest beta release, please try it: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

**Comment by Armada651** [comment] 2017-12-06 14:18
I was able to reproduce a similar bug in Robo Recall, a workaround is opening and closing the dashboard, that should force the controllers to appear.

**Comment by Armada651** [comment] 2017-12-06 14:49
I replaced the beta 3 release with one that should fix it, please download it again: https://github.com/LibreVR/Revive/releases/tag/1.2.0-beta3

**Comment by routb3d** [comment] 2017-12-06 18:14
The new Patch works to launch Medium and everything appears to be running smooth.

After closing Medium, Steam VR's UI becomes unusable. I can see the beam from my controller goes past the UI plane and can't click buttons in most of the UI. For some reason, the bottom row of buttons, Power, Steam, Desktop, Revive, Setting continue to work, but everything else fails.

Restarting Steam VR resets the UI to a working state until Medium is launched again.

**Comment by mm373** [comment] 2017-12-06 22:59
Thanks Armada for the quick fix. Long live revive!

**Comment by quarzon** [comment] 2017-12-07 06:48
Thank you so much for the quick response on this Armada!  Great work :D

**Comment by retrojack70** [comment] 2018-03-14 18:42
Hi everyone. I've tried everything (installing, uninstalling, reinstalling) the above beta version of Revive and have the same issue as listed above: I see Medium on my monitor, but not in the HMD. Also, In the HMD, it doesn't show the icon for Medium, just a gray square. It is clickable, so it does "work" to attempt to load the program, but I thought it was worth mentioning here. Anyone have any ideas on how to make this work? If not, I just blew $30 on Medium. Thank you in advance!

**Closed** 2018-03-14 18:55 UTC

**Comment by Armada651** [comment] 2018-03-14 18:57
@retrojack70 https://www.patreon.com/posts/how-to-fix-part-17220186

Also, make sure you're using the latest Revive version.

**Comment by retrojack70** [comment] 2018-03-14 20:05
OH, THANK YOU SO MUCH. This is my first use of Revive. Gotta say, man--this is an amazing thing you've done.
