### ISSUE TITLE
Airmech doesn't output video or sound to the headset

### ISSUE THREAD

**Issue by thepotatoman23** [LibreVR/Revive#83] opened 2016-05-14 23:24 UTC
The game seems to work perfectly fine when looking at the game window on the computer monitor, including tracking headset movement but the Vive headset just stays in the home environment as if no game is running.

**Comment by LibreVR** [comment] 2016-05-15 00:15
Duplicate of issue #65

**Closed by LibreVR** 2016-05-15 00:15 UTC
