### ISSUE TITLE
"AirMech Command" doesn't display into the Vive

### ISSUE THREAD

**Issue by FrBLD** [LibreVR/Revive#65] opened 2016-05-01 21:52 UTC
Hello,

I tried "AirMech Command", the game started well but didn't display any images into the headset.
But I can see that into my monitor, the tracking is working well and the game is running.

Thanks for this amazing work!

**Comment by LibreVR** [comment] 2016-05-18 19:10
I think this may be related to issue #94 and #89, Airmech is probably using OpenGL.

**Comment by LibreVR** [comment] 2016-05-27 14:58
Probably fixed in commit db1221756bb317895025ceebea45bc4a6c38dff4.

**Comment by LibreVR** [comment] 2016-06-25 19:20
Found the cause of this issue: https://steamcommunity.com/app/358720/discussions/0/405692224241830277/

Will be fixed in the next version.

**Comment by LibreVR** [comment] 2016-06-25 19:45
Fixed in commit ba1418cedd7eff00861e7e3d573dc37ff5509b01.

**Closed by LibreVR** 2016-06-25 19:45 UTC
