### ISSUE TITLE
Arktika 1 hardware issue pop up 

### ISSUE THREAD

**Issue by sakurarozu** [LibreVR/Revive#1117] opened 2018-11-28 17:29 UTC
i so i have the latest revive from today and i cant start arktika since i get a hardware issue pop up. i tried injecting and patching and no dice. any way to fix this? im using a vive. ty

**Comment by Dragoboss** [comment] 2018-12-15 18:46
Duplicate of #1132 
Closing, awaiting response/continuation on #1132

**Closed by Dragoboss** 2018-12-15 18:46 UTC
