### ISSUE TITLE
Can't seem to drop toys in Toybox

### ISSUE THREAD

**Issue by JoeMBlair** [LibreVR/Revive#337] opened 2016-12-05 23:08 UTC
Maybe I'm just being an idiot and there's a button combination I haven't pressed but whenever I pick something up in Toybox I can't seem to let go of it again. Is something not being mapped in revive that would usually be in the touch controllers.

**Comment by LibreVR** [comment] 2016-12-05 23:09
I'll take a look.

**Comment by LibreVR** [comment] 2016-12-05 23:20
Confirmed, I don't know what causes it yet.

**Comment by slessie** [comment] 2016-12-06 03:35
I have a different but maybe related problem. I can't pick up anything. My hands are in and I can hit objects around. None of buttons will pick up anything.

**Comment by LibreVR** [comment] 2016-12-06 17:39
Moving this to the next version so I can release an update for unspoken.

**Comment by LibreVR** [comment] 2016-12-07 13:06
Fixed in commit 17b5c59d008d74ab1a4e75a3b76dd14c65679cee.

Will be part of the next release.

**Closed** 2016-12-07 15:40 UTC

**Comment by r00tuzr** [comment] 2016-12-07 17:19
Pick up and Drop now Works?

**Comment by LibreVR** [comment] 2016-12-07 17:21
> Fixed issues with grabbing/dropping objects in Toybox (#337)

No, I closed the issue because I felt like it. /s
