### ISSUE TITLE
Dance Central crash on startup

### ISSUE THREAD

**Issue by LightbeamZ** [LibreVR/Revive#1221] opened 2019-05-26 07:34 UTC
# Revive/Remixed Report Template
*Please fill out this template/form to the best of your abilities to give us enough info to look into your issue.*
### Description of the issue
*Please provide us with a detailed description of the issue*

I tried to start Dance Central with Revive and does not start with the following error message. https://imgur.com/l4QUmMr 

### Technical Information
*Tell us your specs and versions*
  - CPU:AMD Fx8350
  - GPU:AMD Vega 64 LC
  - RAM: 16Gb DDR3 1600MHz
  - OS:  Windows 10 Pro 1809 (Build 17763.503)
  - Vive with TPCast (Open TPCast)

#### Versions and features
*This issue is about:*
  - SteamVR version (unless Remixed): 1.4.18
  - Revive installation version: 1.6.3.0

#### What is the last working version before this issue first came up?
  - Revive installation: never (game released 4-5 days ago)
  - SteamVR (unless remixed):  never

### What apps/games are you trying to run?
  - Dance Central

## How to reproduce your issue?
_**This is some of the most essential information: what steps did you do to get to this issue. Which steps do we take to get to the same result?**_

  1. just start the game with Revive 

## Error messages/codes
  - LowLevelFatalError [File:Unknown]  [Line: 251] Result failed at 
    E:\BuildAgent\work\767d980fd80afde6\main\ue4\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11VertexBuffer.cpp:83 with error E_INVALIDARG
![Error](https://user-images.githubusercontent.com/51022770/58378745-47a17c00-7f99-11e9-907d-92e07059269a.jpg)

Thank you for reporting your issues/feedback/suggestions about Revive! We really appreciate your support!

**Comment by akanemori58** [comment] 2019-06-04 07:42
I'm having this issue too.

**Comment by LightbeamZ** [comment] 2019-06-04 10:07
Someone on Reddit reported to try the following:

> Did you try the new dll? It is an early release from another issue post.
> 
> https://github.com/LibreVR/Revive/files/3209865/LibRevive64_1.zip
> 
> Replace old version (change C for your install drive):
> 
> C:\Program Files\Revive\Revive\x64

I can not try this right now because I already refunded the game. Can you try this and report back?

**Comment by akanemori58** [comment] 2019-06-08 08:20
I replaced the old version but it's still not working. Getting the same error

**Comment by LightbeamZ** [comment] 2019-06-14 12:08
Can you try the new "Version 1.7.0 pre-release"? Maybe it fixes the issues. If so it would be nice when you report back.

**Comment by akanemori58** [comment] 2019-06-15 10:25
Downloaded and still not working. Same message.

**Comment by LightbeamZ** [comment] 2019-06-15 12:01
Then Revive probably has to get a major update to get it working. Too bad.

**Comment by cflfa** [comment] 2019-06-24 14:07
Yh, I had this exact same problem with it... had to refund the game :(
W8ting for it to be fixed!

**Comment by LightbeamZ** [comment] 2019-06-30 15:54
Any news?

**Comment by akanemori58** [comment] 2019-07-04 05:20
Still not working, I'm hoping there's a fix soon.  Not sure why it's reference an E-drive but I'm not savvy enough to figure out the cause

**Comment by c2morg** [comment] 2019-07-07 11:23
Same problem on this for me with latest early release of revive

**Comment by laserob** [comment] 2019-07-09 23:32
Same problem here as well.

**Comment by nyshotgun05** [comment] 2019-07-19 16:17
Same here, just signed up to to say the same thing. Would love for this to work.

**Comment by Flyingtitus** [comment] 2019-07-19 17:30
> Same here, just signed up to to say the same thing. Would love for this to work.

+1

**Comment by CheeZuShRicE** [comment] 2019-07-20 15:41
Same here with latest version of Revive, just as an additional note if it helps at all, get the exact same message with Moss too if there is common ground there.  Other titles do work so it is game specific.

**Comment by indyjb** [comment] 2019-07-23 05:07
After trying the 1.7.1.1 update, I do not get the Low Level Fatal Error, but it still crashes after showing the Dance Central logo.

**Comment by Flyingtitus** [comment] 2019-08-05 17:32
¿Any news with new version?

**Comment by nyshotgun05** [comment] 2019-08-05 18:19
I’ll try it out after work today

**Comment by indyjb** [comment] 2019-08-05 20:09
I tried it and it’s still crashing in the same place.  I’m wondering if there’s some sort of entitlement check to the Harmonix servers that’s not being properly resolved when run through Revive.  I recall Rock Band VR having a similar issue initially.

**Comment by thenayr** [comment] 2019-08-06 19:32
I tried running the app through proxy to see if there were some server side checks going on, didn't see anything that stood out, unfortunately.

**Comment by CheeZuShRicE** [comment] 2019-08-09 13:39
Looking at similar stuff in pancake gaming, seems to be something to do with Unreal Engine and directx with win10 on dx12.  Been messing about for the last hour trying to force a -12 switch with no luck, but this looks too familiar, in terms of the error we are getting in revive - https://forums.unrealengine.com/community/general-discussion/1497761-why-is-unreal-engine-4-19-2-not-backwards-compatible-with-direct-x-12-per-default-windows-10

**Comment by Armada651** [comment] 2019-08-11 01:27
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3

**Closed by Armada651** 2019-08-11 01:27 UTC

**Comment by mvereecken** [comment] 2019-08-13 08:02
Btw @CheeZuShRicE also tested, and still has the error.

**Comment by CheeZuShRicE** [comment] 2019-08-13 08:06
Just to be sure, I have since did a fresh install of both oculus home and revive 1.7.3 after removing all local appdata info on Windows 10, getting the same error on both Dance Central and Moss unfortunately.

**Comment by Flyingtitus** [comment] 2019-08-21 15:44
I played the game days before, with 1.7.3, but now the game crash at "dance central" logo.

**Comment by Flyingtitus** [comment] 2019-08-24 07:55
> I played the game days before, with 1.7.3, but now the game crash at "dance central" logo.

Reverted from 1.8.0 to 1.7.3 and is working again.

**Comment by CheeZuShRicE** [comment] 2019-08-24 20:12
Just wanted to update on my comments re moss having the same issue, it's not really a revive thing, I and @mvereecken have been trying to run this using a quest with Virtual Desktop also in the mix so none standard SteamVR, I tested this all the way up to present 1.8.0 version and got no success.  However in the last day have got an Index and removing the VD aspect this is working 100% on SteamVR Beta 1.7.9 and revive 1.8.0.  Just wanted to post in-case you thought this might need to be re-opened it does not it does indeed work.

**Comment by jaskas** [comment] 2019-09-11 15:45
@CheeZuShRicE can you please explain a bit more. I am trying to get this to run on my samsung odyssey + and am having no luck. Its crashing at the startup screen or I get a hardware failure.

Sorry i'm new to this what does "VD" mean. When you said you got the index and removing the VD aspect  

BTW I have all the latest steam VR beta and revive 1.8

**Comment by LightbeamZ** [comment] 2019-09-21 12:10
So I tried it today and it still works with Revive 1.7.3. But its broken in Revive 1.8.1. So it seems like some recent changes in Revive broke it again.

AMD 3700x / Vega64 
SteamVR 1.7.15

**Comment by haywirephoenix** [comment] 2020-01-07 15:27
this is still happening :(

**Comment by ClarkHH** [comment] 2020-01-18 19:17
This is still happening for me, too! Please help.

**Comment by redtani** [comment] 2020-05-02 01:49
This is still a problem for me. I am indeed using a wireless setup (Vive Focus Plus) with SteamVR, so that may be related to it. But from my understanding, this used to work previously for people with wireless setups (Virtual Desktop, ALVR, Riftcat, etc.) so I was hoping this could be fixed to accommodate wireless again.

**Comment by CrossVR** [comment] 2020-05-02 09:55
Virtual Desktop, ALVR and Riftcat were never supported, they just happened to work sometimes.
