### ISSUE TITLE
Damaged Core "zoom" issue

### ISSUE THREAD

**Issue by placebo787** [LibreVR/Revive#245] opened 2016-08-31 00:59 UTC
Hi - just purchased Damaged Core.  Everything is flawless until you are instructed to zoom your weapon.  Everything goes blurry and there is no magnification...

Is this something you can fix?  I was super stoked to play this game!!!

**Comment by sbawden77** [comment] 2016-08-31 06:26
Yeah that bummed me out too. Hope it can be fixed!

**Comment by srt23** [comment] 2016-09-01 07:42
Yeah, I have the same problem. Playable without it, but gets really hard. The biggest problem however i find is the lack of crosshair. Makes it really hard to jump longer distances. Except these two issues it works flawlessly.

**Comment by placebo787** [comment] 2016-09-01 18:10
Forgive my paranoia, but this seems like a purposeful malfunction...  I thought Oculus was done with this sh!t...  I sent an email to the dev looking for clarification.  I doubt I'll get a reply :-(

**Comment by LibreVR** [comment] 2016-09-01 19:25
I'll look at this issue soon, please don't take out your pitchforks until we've determined what the issue is. Revive is still pre-release software and it doesn't implement every little feature of the runtime yet, so problems are to be expected.

**Comment by placebo787** [comment] 2016-09-01 19:32
Pitchfork withdrawn...  Thanks for taking a look and THANKS for all of your hard work :-)

**Comment by LibreVR** [comment] 2016-09-05 10:09
I've taken a look at the issue, Damaged Core uses two stereoscopic scene layers that it can render at different resolutions. Unfortunately due to limitations of the OpenVR API this is not yet supported in Revive. I'll look into a solution, but it is not an easy fix.

**Comment by srt23** [comment] 2016-09-05 10:35
That's too bad. Thanks for the good work though. Does this problem apply to the missing crosshair also?

**Comment by LibreVR** [comment] 2016-09-05 10:39
Yes, the HUD is part of the second layer that is currently ignored by Revive. I should be able to merge these layers within Revive, but that requires a bit of restructuring.

**Comment by srt23** [comment] 2016-09-05 12:20
Amazing how you are able to figure this out:)

**Comment by LibreVR** [comment] 2016-09-05 12:35
That isn't really difficult, when you compile Revive you can just change which scene layer it uses.

**Comment by sbawden77** [comment] 2016-09-05 18:55
Thank you for all of your help! I appreciate it.

**Comment by newend** [comment] 2016-09-08 04:15
Just curious if this was fixed yet?

**Comment by LibreVR** [comment] 2016-09-08 10:09
Working on it, I have a branch that is able to at least display the Scope and HUD, but it's at the incorrect depth. I will need to do a completely different approach instead, so it'll take a bit longer.

**Comment by LibreVR** [comment] 2016-09-09 00:51
Good news everyone, I have a local prototype where the necessary features are implemented to merge the two layers. There's a couple of issues I need to solve, but it's looking good.

This will be fixed before the next release.

**Comment by placebo787** [comment] 2016-09-09 01:12
That's awesome news!!!  Thanks so much for your hard work on this :-).  I figured this would take weeks or months.

**Comment by toooner** [comment] 2016-09-09 16:35
This is great news, thank you for all your hard work.  Is there an ETA for the next release or is it possible to download builds before a major release?  Excuse my ignorance.

**Comment by srt23** [comment] 2016-09-09 18:19
Awsome!

**Comment by LibreVR** [comment] 2016-09-12 22:32
This is now fixed in the source code, just waiting on a new release. I just have two more issues to take care of before the next release, so expect it somewhere around the end of this week.

**Closed by LibreVR** 2016-09-12 22:32 UTC

**Comment by LibreVR** [comment] 2016-09-16 17:24
[Revive 0.9 has been released](https://github.com/LibreVR/Revive/releases/tag/0.9).

**Comment by srt23** [comment] 2016-09-16 18:03
Thank you so much for your amazing work. Really wish I could donate directly to you, or help otherwise. I have a few games on the oculus store, will give you access to my account if that could help you. Downloading Feral Rites now to see if that works.

**Comment by placebo787** [comment] 2016-09-16 18:34
Damaged Core is AMAZING!!!  Thank you again.

**Comment by sbawden77** [comment] 2016-09-17 03:06
Thank you so much for all of your hard work! Damaged core is working beautifully!
