### ISSUE TITLE
Revive lags on Defector - maybe coz Revive conflict with Oculus Home

### ISSUE THREAD

**Issue by mena99** [LibreVR/Revive#1287] opened 2019-08-05 13:13 UTC
hi , I've just bought Samsung OdySSey and i was excited about playing lots of games in vr 2 of them were fallout 4 and Defector .

all games that supports WMR works GREAT!
but Defector Glitches not too bad but that it all it takes to take away all the fun, i tried to go through with this but i couldn't hold it for more than 10 mins without feeling like throwing up .
any idea how to fix it ?

i think the problem Occurs because Windows Mixed reality home starts with Steam VR
i don't think its performance issue due to the lake of recourse in my system , it's more like conflict between SteamVR and ReVIVE and Windows mixed reality home 

the problem is the Revive DASHBOARD doesn't INCLUDE the game in it ( Defector) only the ones that were downloaded with Oculus home. 

### Technical Information
 Dell Inspiron 15 7567 Laptop + 
  - CPU: I7 processor 7700HQ 2.8 GHZ
  - GPU: NVIDIA GTX 1050ti
  - RAM: (amount and DDR#) :12GB rams
   - storage : SSD 256 (( the game is on the ssd ))
   - storage : 1 TB HDD ( windows is installed here )
  - OS:  windows 10
  -Samsung Odyssey

#### Versions and features
*This issue is about:*
  - Revive / Remixed / Injector or Patcher : Current version (1.7.2)
  - SteamVR version (unless Remixed): auto update 
  - Revive installation version: 1.7.2

#### What is the last working version before this issue first came up?
nothing this is my first time ever.

### What apps/games are you trying to run?
  - Defector ( Oculus rift )

**Comment by Armada651** [comment] 2019-08-10 10:19
Duplicate of #1272

**Closed by Armada651** 2019-08-10 10:19 UTC
