### ISSUE TITLE
Xbox One wire controller issue with Revive Tab

### ISSUE THREAD

**Issue by nerdwithus** [LibreVR/Revive#181] opened 2016-07-02 07:33 UTC
I have to open up the Xbox app on windows 10 to get the Xbox button to respond. Thus opening the dashboard in the Vive headset.

however, while i can navigate the mid tabs, when i select revive the screen listing my games in the revive tab cannot be navigated with the controller.

any help would be appreciated.

**Comment by LibreVR** [comment] 2016-07-02 10:24
Duplicate of issue #162, albeit with an Xbox controller instead of a Steam controller.

**Closed by LibreVR** 2016-07-02 10:24 UTC
