### ISSUE TITLE
Ultrawings "Waiting for controller"

### ISSUE THREAD

**Issue by OutlawViking** [LibreVR/Revive#508] opened 2017-02-21 20:38 UTC
I am having an issue where when I start ultrawings I get a "wait for controller" screen and the game goes no further. I know the game came out today but I wanted to start this topic to try and help in any way I can to get this game working. I have an Xbox controller and both Vive controllers connected. I am running the latest version of Revive, Oculus Home, and Steam VR.

**Comment by jaorg1234** [comment] 2017-02-21 21:27
Don't have that game, but try to move your Vive wands around **before** and **while** the game is starting up. Maybe that helps to get the controllers recognized by the game

**Comment by OutlawViking** [comment] 2017-02-21 22:07
I started another game in Steam and played for a few min. Then I switched to a revive game (Super Hot VR) and played that for a few min. Then I tried Ultrawings again and had the same issue. I sat at the waiting screen for about 5 min waiving the VR controller and pressing buttons on the Xbox and VR controllers.

The exact terminology used by the game is "Waiting on Controller" that to me sounds like the Xbox controller. In the Oculus store it does say "Gamepad Required" Oculus Home does see my controller.
I'm guessing that Revive does not send any controller data except for the Vive Controllers.

**Comment by Armada651** [comment] 2017-02-21 22:45
Xbox controllers are supported in Revive, I'll see if I can reproduce this.

**Comment by Armada651** [comment] 2017-02-21 23:13
According to the store page Oculus Touch controllers are supported.

**Comment by Armada651** [comment] 2017-02-22 17:24
I'm able to reproduce the issue, currently trying to find the cause.

**Comment by Armada651** [comment] 2017-02-22 17:54
Fixed in 36251ea02fdecc3ec027496b74eabac5bb556463.

**Closed by Armada651** 2017-02-22 17:54 UTC

**Comment by OutlawViking** [comment] 2017-02-22 19:12
@Armada651 Thank you for your help I greatly appreciate it.
I have downloaded and edited the files per the link above.
I am trying to fine the files to replace them but I am having no luck.

Do these files need to be compiled into an installer?
Or
Are the files located on my HD but not in the Revive folder?

**Comment by Armada651** [comment] 2017-02-22 19:25
Hahaha, no that's the source code, and that doesn't compile into an installer, it compiles into a whole bunch of binaries and libraries.

Normally you'd have to wait until the next release, but I just released a new version an hour ago so you can use it right now. Just download it here: https://github.com/LibreVR/Revive/releases

**Comment by OutlawViking** [comment] 2017-02-22 19:34
Too funny. Thanks for all the help.

**Comment by jacobking25** [comment] 2019-03-11 00:52
I'm running into the same problem now, I'm running the current version for SteamVR oculus and Revive.

what can i send to help out?
