### ISSUE TITLE
Oculus Video works, Oculus 360 Pictures doesnt.

### ISSUE THREAD

**Issue by ZyonPlay** [LibreVR/Revive#217] opened 2016-08-03 15:06 UTC
It tells me that:
![unbenannt](https://cloud.githubusercontent.com/assets/20818376/17370502/8d9200fc-599c-11e6-8b44-2ed317514237.JPG)
funktioniert nicht mehr : doesnt work anymore.

**Comment by ZyonPlay** [comment] 2016-08-03 15:56
I already reinstalled ReVive and Oculus360Photos

**Comment by LibreVR** [comment] 2016-08-10 20:57
Duplicate of #219

**Closed by LibreVR** 2016-08-10 20:57 UTC
