### ISSUE TITLE
Oculus dash, not home [request]

### ISSUE THREAD

**Issue by shadkp** [LibreVR/Revive#1461] opened 2020-02-03 17:11 UTC
Hello, I'm a quest user and I'd like to request for the future updates if it was possible to access the oculus dash, not the home, as in being able to display the windows of my computer as I please around me.

I've read around that having that would be kind of tough for a computer to handle, but the problem is not because of the dash but the home that use UE and takes a lot from the computer. Simply using the dash from the hub, with nothing load but your windows showing up.

If possible maybe you could go through the occulus, interface rather steamVR ? I'm sorry I'm a neophyte in how this works, so I might say something stupid.

There would be other solution like using directly the oculus link with a USB-c to USB-A 3.0 , but there's not much cable around, and the plus of an occulus quest is to have no cable at all, but aside that using oculus link reduce the image quality.

Using an other software like virtual desktop, or Vspatial doesn't bring as much options as occulus dash, even though Vspatial is on a good way.
Do you have any other solution ?

**Comment by CrossVR** [comment] 2020-02-04 11:22
Oculus Dash relies on the runtime to capture windows, so implementing the necessity functions would require just as much development time as writing virtual desktop from scratch.

There's not much to be gained from going this route unfortunately.

**Comment by shadkp** [comment] 2020-02-04 17:02
I see. Thanks for taking time to answer

**Comment by CrossVR** [comment] 2020-02-06 12:48
Closed as duplicate of #847

**Closed** 2020-02-06 12:47 UTC
Labels: question
