### ISSUE TITLE
Henry only displaying in the right display

### ISSUE THREAD

**Issue by herbiems89** [LibreVR/Revive#123] opened 2016-05-29 19:50 UTC
Tried Revive for the first time tonight. Luckys tale and INtroduction to VR worked flawlessly.
Then i tried Henry, which starts of ok but as soon as the real story starts (when you get into his house) my left display goes black and the content is only displayed in the right eye. The only thing still visible in the left display are my base stations.

Would be great if you could help and also thank you for this amazing project :)

EDIT: The same issue im having with Henry also appears with Lost.

**Comment by LibreVR** [comment] 2016-05-30 09:15
What are your system specifications?

**Comment by Glibber** [comment] 2016-05-31 10:16
I do have the same problem with "Henry", but for me only the left eye did work. No problems with Luckys Tale.
Used the Revive-Installer Version 0.6 for Oculus Home-Games, this is the first version I ever tried.
System Spec: 
Radeon R9 390, newest beta drivers, if you need the exact version I have to look when I'm home.
Core i5 3570K; 16Gig RAM

If i can help you solving the problem please tell me.
Thank you for your time & work.

**Comment by herbiems89** [comment] 2016-05-31 20:05
i5-2500k
R9 390 (tested with my old driver and the newest beta driver)
8gb Ram
Windows 10 x64

**Comment by LibreVR** [comment] 2016-06-01 09:31
Seems to be an AMD problem then, that would explain why I can't reproduce it.

**Comment by KeithSedgeman** [comment] 2016-06-10 21:51
Henry works ok, but Mythos won't start on my GTX 970. there's a quick flash of the main menu or something with the Mythos logo, then all black with sound.

I tried with revive tab & Injector on both exe's.

**Comment by KeithSedgeman** [comment] 2016-06-11 23:42
Seems to be a common problem.
https://www.reddit.com/r/oculus/comments/4ide3x/mythos_of_the_world_axis_free_on_oculus_home/d2xhbos

PS. As a testament to my PC's Compatibility/Stability, of the 50+ different VR apps/games I've tried, including a large bulk of the free Oculus home stuff. Mythos is the only game that I've been unable to play.

**Comment by gormanj** [comment] 2016-06-12 03:51
Mythos has never worked for me and I have most everything working that anyone else does (except Pinball FX2 VR). I found an older version of it that loads the opening screen (3D), but as soon as you press "X" on the controller it does the same thing--black with some sound and that's it.

**Comment by LibreVR** [comment] 2016-06-12 19:24
@KeithSedgeman I understand that multiple people have this problem, but until I can reproduce the problem I can't really fix it. Revive is still alpha software which means there is a lot of stuff to fix and the ones that I **can** reproduce will take priority over those which I **can't** reproduce.

**Comment by LibreVR** [comment] 2016-07-05 19:32
Can you test the latest version 0.8.1?

**Comment by LibreVR** [comment] 2016-07-15 10:50
This should be fixed in version 0.8.5.

**Closed by LibreVR** 2016-07-15 10:50 UTC
Labels: help wanted
