### ISSUE TITLE
Revive tab on dashboard no longer shows any of my Occulus library

### ISSUE THREAD

**Issue by markbradley1982** [LibreVR/Revive#911] opened 2018-01-25 02:19 UTC
After Occulus Home updated itself the Revive tab in SteamVR no longer shows my Oculus game icons. They're basically invisible except for the demos that come with Oculus Home like Dreamdeck and First Contact. It's a grand total of 4 experiences with icons, the rest are invisible. I can still pull them up in my "installed" SteamVR menu, but they too show up without any icons there.

I am using the latest auto updated version of Revive 1.20 and I am not sure what version of Oculus Home I am running. I looked everywhere for a version number, but the window is much larger in the new version of Oculus Home compared to the old version.
 
How do I make my Revive tab show icons for all of the games I bought?

**Comment by Armada651** [comment] 2018-01-25 02:24
Duplicate of #907.

**Closed by Armada651** 2018-01-25 02:24 UTC
