### ISSUE TITLE
ONWARD on WMR not working anymore

### ISSUE THREAD

**Issue by kodama12** [LibreVR/Revive#1142] opened 2018-12-22 17:26 UTC
I have to open a new issue because a guy "armada651" closed it without reading and knowing what he is talking about..... 

Hi guy,
First, thanxs for your Revive mod .
After 1 year of playing, i stopped onward; it was fine. I've just update Revive, Oculus, SteamVR & drivers of GPU, and ONWARD refuse to launch, or more precisely, the screen is not redirected/injected inside VR headset. I hear the sound, but i'm still inside the "white room" of STEAMVR. On my computer, the window of Onward is opened, but white, nothing appears.
I use Onward on Oculus Store, with Revive and steamVR (read the fucking manual Armada651"
https://github.com/LibreVR/Revive
"4."Start SteamVR if it's not already running."

**Comment by Armada651** [comment] 2018-12-22 17:38
Onward is available on the Steam store with native SteamVR support. Using Revive for games that already natively support SteamVR is not supported.

I'm the one who wrote Revive, I know what I'm talking about.

**Comment by Armada651** [comment] 2018-12-22 17:39
duplicate of #1141

**Closed by Armada651** 2018-12-22 17:38 UTC

**Comment by kodama12** [comment] 2018-12-22 17:39
strange, i can play on it in past, before it was realeased on SteamVR....

**Comment by Armada651** [comment] 2018-12-22 17:42
> before it was realeased on SteamVR....

It has always been available on Steam

**Comment by kodama12** [comment] 2018-12-22 17:42
so why i was functionnal by Revive in past and not anymore.... man i'm not a liar....

**Comment by Armada651** [comment] 2018-12-22 17:45
Not calling you a liar, it might be broken, but it makes no sense to use Revive to play Onward.

Onward was initially released on SteamVR and only got an Oculus release much later. It doesn't make sense to use Revive to get it to work on SteamVR again.
