### ISSUE TITLE
XBox One Controller Not working with Lucky's Tale

### ISSUE THREAD

**Issue by mattdsoares** [LibreVR/Revive#1114] opened 2018-11-25 04:28 UTC
I have a Lenovo Explorer WMR headset.  Lucky's Tale fires up just fine but does not seem to accept any input from my XBox One controller.  Steam VR, WMR, and the Oculus app all show it as being connected and working.  Any ideas?

**Comment by Armada651** [comment] 2018-11-25 13:05
Duplicate of #1064

**Closed by Armada651** 2018-11-25 13:05 UTC
