### ISSUE TITLE
Minecraft VR

### ISSUE THREAD

**Issue by neuhaus** [LibreVR/Revive#234] opened 2016-08-17 10:26 UTC
The game crashes shortly after showing the 360-degree environment.

**Comment by jimx78** [comment] 2016-08-17 16:56
salut ! ajoute moi sur steam ou oculus : pseudo jimx78
on a déjà un topic
https://github.com/LibreVR/Revive/issues/230

**Comment by jimx78** [comment] 2016-08-17 21:03
Hello,
There was an update today from Mojang that corrects the problem on Rift CV1.
I uninstall minecraft minecraft on W10 and oculus and redemarer PC.
I reinstall everything but I have the same problem.

Once minecraft start, there's a blur in minecraft skybox with nothing. (This is the menu)
10 seconds later, crash the game. (This game has stopped working)
It can be a DRM?

**Comment by iamwes** [comment] 2016-08-18 00:03
Exactly the same for me, loads up with a blurry minecraft background then shuts down after about 10 seconds.

**Comment by LibreVR** [comment] 2016-08-18 00:17
I'll take a look at this soon.

**Comment by LibreVR** [comment] 2016-08-18 12:16
Duplicate of issue #230.

**Closed by LibreVR** 2016-08-18 12:16 UTC
