### ISSUE TITLE
Lone Echo is shaking when looking around only in the Spaceship normally (SteamVR) and Lone Echo is not recognising my controllers without SteamVR (Remixed (I think)) (WMR)

### ISSUE THREAD

**Issue by BlackCatTB** [LibreVR/Revive#1152] opened 2018-12-29 18:22 UTC
### Description of the issue
So in SteamVR Revive mode, in the game Lone Echo the Controllers are recognised but when in the Spaceship -the tutorial works just fine btw- whenever I look around normally the game seems to stutter without stuttering, I mean it looks like playing with 23fps but with 90+ FPS. And the second problem is that whenever I start the game without SteamVR the game would not recognise my controllers.
Help!

### Technical Information
My Rig rn:
  - CPU: Ryzen 7 1700x
  - GPU: RX Vega 64 strix
  - RAM: 16gb
  - OS: Windows 10 Pro
  - WMR
#### Versions and features
This issue is about:
  - Revive / Remixed
  - SteamVR version: latest (29.12.2018)(idk where to find it)
  - Revive installation version: 1.6.2

#### What is the last working version before this issue first came up?
first time using Revive _or Remixed_

### What apps/games are you trying to run?
  - First Contact (SteamVR and without SteamVR worked fine with controllers)
  - Touch basics (SteamVR and without SteamVR worked fine with controllers)
  - Lone Echo (SteamVR controllers are showing up but there is a wierd jitter happening when looking 
                       around, but when starting the Revive dashboard and Launching the game frome there the 
                       controllers won't work but float around infront of me)

## How to reproduce your issue?

  1. Start Lone echo in the SteamVR version, get in the spaceship and look around naturally.
  1(2). Start Lone echo without SteamVR

## Error messages/codes
  - N/A

**Comment by Obi2000** [comment] 2018-12-29 21:39
I'm having the same issues in Revive using an Odyssey+ headset. Seems like a controller tracking issue to me. As soon as you exit the tutorial the hands become very juddery. Everything else happening in front of me is perfectly smooth though, and fpsVR reads 90FPS.

Trying to use Remixed leads to the controllers not being detected.

**Comment by Dragoboss** [comment] 2018-12-30 13:55
So, three different people with three different issues in here...
(Yes, if you read it carefully enough you notice that those who said they have the exact same problem actually have a different one).
All of which I cannot reproduce.

I am talking with @BlackCatTB in Discord.
@Obi2000 your issue sounds like a controller tracking issue in SteamVR. Your head-tracking is smooth, though? Are you using a external bluetooth adapter or using built-in bluetooth of your computer?

Are you and @MorbidNoodle both on Windows 1809?
If so, press the windows button of your controllers to open the little dash then click it away with your trigger by clicking anywhere else in the game (not on the buttons).

**Comment by MorbidNoodle** [comment] 2018-12-30 18:48
I am on Windows 1809. I've tried bringing up and dismissing the dash with no success. I've also tried WIN+Y to switch the window focus back and forth. I still receive the "Hardware Error: You have a pending hardware issue that is preventing you from entering VR. Please check that your left touch controller is paired and powered" screen in my Lone Echo window. In the Mixed Reality Portal, I get the flashing red touch controller icons on the bottom of the window. 

Oddly enough, Echo VR works perfectly fine.

**Comment by Obi2000** [comment] 2018-12-30 23:36
My head tracking is fine, as far as I can tell. But the controllers stutter and have a ghosting effect on them. For bluetooth, the Odyssey+ controllers connect directly to the head set. This is all under Steam VR.

I tried your suggestion with the Win key and Remixed still wont detect my controllers in Lone Echo.

**Comment by MorbidNoodle** [comment] 2018-12-31 19:16
I ran some additional tests earlier on SteamVR (revive) on Lone Echo using fpsVR. The jittering/stuttering I was experiencing is caused by bad performance. Even on low, the FPS spikes down hard when moving around, with my GPU (1070 Ti Overclocked) spiking up to over 90% utilization. Testing in Echo VR yields similar results.

Closing Steam and launching with remixed, Echo VR runs great with no frame rate dips even on high with super sampling set to 1.5. Echo VR also has no issues picking up my controllers when launched via remixed. However, as stated previously, Lone Echo does not pick up my controllers at all. 

The performance issues with 'WindowsMR>SteamVR>Revive' are to be expected, so it appears to me that the only way I'd be able to play this game is via remixed. The most confusing part of this issue to me, is that everything works fine on Echo VR, but not Lone Echo. Please let me know if there is any additional information I can provide about this issue.

**Comment by JoePinapples** [comment] 2019-01-03 15:20
I have very similar issue with Samsung Odyssey Plus to you @MorbidNoodle. Although I can't get the game passed the Lone Echo main menu using either method of Revive, i.e. Remixed nor injecting via SteamVR compositor.
See issue raised below.
#1158

**Comment by Armada651** [comment] 2019-02-03 19:17
Unfortunately I do not have access to a Samsung Odyssey Plus, so I'm unable to debug this issue.

**Comment by Armada651** [comment] 2019-02-03 19:32
I made a change in the latest version (1.6.3) that could potentially fix the controller detection issue in Remixed.

**Comment by MorbidNoodle** [comment] 2019-02-03 20:09
I can confirm that with this new version Lone echo shows that both controllers are now successfully paired/connection. However, the animated hands are locked in position in front of me, and do not respond to any movement. I've tried alt-tabbing, switching input focus (win+y), etc. The game does not accept any motion or input.

**Comment by JoePinapples** [comment] 2019-02-03 20:48
Apparently it's not just Odyssey plus but all WMR controllers. Others have complained of it with the vive wands.

On 3 Feb 2019 7:32 pm, Jules Blok <notifications@github.com> wrote:

I made a change in the latest version (1.6.3) that could potentially fix the controller detection issue in Remixed.

**Comment by sascha005** [comment] 2019-02-24 17:15
Hi, I have exactly the same Problem with my Lenovo Explorer. With Revive/SteamVR i have strange Shaking when moving my Head. But only in Spaceship. In Tutorials i have no Problems and a good Performance. Echo VR runs just fine btw. without any Problems on my System.

My System :
CPU I5 4440
RAM 8GB
GPU NVIDIA 1070TI
Revive 1.6.3
Steam 1550534751
SteamVR 1.2.10

I know, this is no HigEnd Machine, but i can Play allmost any other Game without any Problem. Does anyone know exaclty what causes this Shaking Problem ? Or can anyone tell me, why the Controllers would not get tracked using Remixed ? Is there any Fix for that ?

**Comment by Armada651** [comment] 2019-06-06 00:28
Remixed has been replaced with ReviveXR in the pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0

**Closed by Armada651** 2019-06-06 00:28 UTC
Labels: WMR on Revive, remixed
