### ISSUE TITLE
Medium 2.0 - Broken again

### ISSUE THREAD

**Issue by cartoonmonkey** [LibreVR/Revive#1022] opened 2018-06-28 23:57 UTC
Medium update 2.0 not working with Revive any longer. 
:-/

**Comment by johnboyjr** [comment] 2018-06-29 01:45
same for me :(

**Comment by fezzza** [comment] 2018-06-29 15:39
same, same :(

**Comment by cartoonmonkey** [comment] 2018-06-29 17:06
I'll hang in there for an update. Donating to your patreon!

**Comment by wkarnchanapee** [comment] 2018-06-29 21:52
Not working for me either :(

**Comment by 3dbumper** [comment] 2018-06-29 23:23
Good call @cartoonmonkey.

I think I will do the same. I owe him a debt of gratitude for having enabled me to discover Medium on my Vive.

**Comment by marcoleone** [comment] 2018-07-02 21:02
@Armada651 Do you have an idea on when there could be a fix to this issue?
Thank you so much for your work!

**Comment by Porcelainfog** [comment] 2018-07-03 02:03
@Armada651 Thank you for your work.

**Comment by Armada651** [comment] 2018-07-03 16:40
Caught the flu, there's going to be some delay in fixing this. Sorry about that!

**Comment by johnboyjr** [comment] 2018-07-03 16:48
Just feel better. Your health matters the most. Appreciate the work you do

**Comment by marcoleone** [comment] 2018-07-03 17:24
@Armada651 No problem man! Feel better!

**Comment by Porcelainfog** [comment] 2018-07-03 22:50
Take some sick time! Feel better :)

**Comment by wkarnchanapee** [comment] 2018-07-04 13:10
@Armada651 No worries take care of yourself :)

**Comment by Armada651** [comment] 2018-07-05 19:21
@Qianqianye Funding is not the problem, just manpower.

**Comment by stema84** [comment] 2018-07-13 20:44
I just bought medium, just to realize this. Tried several version, beta combinations, no luck. At least it's a known issue :) Hope it gets sorted, thank you for the work!

**Comment by Porcelainfog** [comment] 2018-07-15 18:30
Yea I've been keeping my eye on this thread for awhile. Anyone have any tricks to get medium working again?

**Comment by johnboyjr** [comment] 2018-07-16 04:49
Porcelainfog there are no ways to get 2.0 to work. i found a copy of 1.0 and it works but is missing so much its not worth it. if you could find some one that never updated passed 1.3 you might be able to use there files to get you back running. other then that you have to wait for revive to be updated

**Comment by Armada651** [comment] 2018-07-16 14:45
The problem is fixed in commit fe77db07a811c84454740f7f86a3ec6690c57af7. I'll release a new beta version once I've fixed another Vulkan crash that happens when exiting Oculus Medium.

**Comment by parsec3d** [comment] 2018-07-16 16:06
Awesome... well as long as saving works I am ready to test even if it crashes on exit.

**Comment by jonnibravo** [comment] 2018-07-16 21:16
@Armada651any chance this will fix the problem rock band vr is having

**Comment by dangercloset** [comment] 2018-07-16 21:52
sorry for the noob question...I have revive installed, how do I update it now to work with medium 2.0?

**Comment by johnboyjr** [comment] 2018-07-16 21:57
@dangercloset  you wait for the next beta to be released here https://github.com/LibreVR/Revive/releases

**Comment by dangercloset** [comment] 2018-07-16 22:18
ok thanks!

**Comment by cartoonmonkey** [comment] 2018-07-16 23:36
Freaking awesome. I can't wait. Thank you!

**Comment by Armada651** [comment] 2018-07-17 14:12
Beta version 1.4.1 is now released.

**Closed by Armada651** 2018-07-17 14:12 UTC

**Comment by anthonywob** [comment] 2018-07-17 14:17
Awesome, thanks! Will load it up this evening.

**Comment by johnboyjr** [comment] 2018-07-17 14:25
@Armada651 on Samsung Odyssey the controller buttons do not do anything. I can see my hands but none of the buttons work. I am trying to reinstall Oculus medium just to make sure nothing's wrong with that

**Comment by gfodor** [comment] 2018-07-17 14:30
(Sorry if newb question) but I am trying to run this with an Odyssey and getting a crash on launch. I'm using the 1.4.1 beta. It runs fine on my rift. Any ideas?

**Comment by johnboyjr** [comment] 2018-07-17 14:35
gfodor you have to launch from inside steam vr. The dashboard would not work for me. But chances are you won't be able to use any buttons anyway

**Comment by gfodor** [comment] 2018-07-17 15:06
Ah yup, that worked! And yes, no buttons :(

**Comment by stema84** [comment] 2018-07-17 15:47
I didn't have buttons when I was trying the beta with non beta steamvr and wmr in steam. I don't know if that could cause the issue, but maybe trying combinations? I can't test it yet, maybe in an hour.

**Comment by Armada651** [comment] 2018-07-17 15:49
You *have* to use the SteamVR beta. But I can also reproduce the fact that buttons don't work, I didn't expect that because it work in other games. I'll work on another update.

**Comment by Armada651** [comment] 2018-07-17 15:53
Check it again, inputs seem to work for me after all. Please make absolutely sure you're using the SteamVR beta.

**Comment by Armada651** [comment] 2018-07-17 15:58
You might need to restart SteamVR too.

**Comment by johnboyjr** [comment] 2018-07-17 15:58
I tried with beta and with out going to try restarting pc

**Comment by Armada651** [comment] 2018-07-17 16:05
If input still isn't working please drag the following log file into the comment box here to upload it to the issue:

`C:\Program Files (x86)\Steam\logs\vrclient_OculusMedium.txt`

**Comment by johnboyjr** [comment] 2018-07-17 16:05
Tried  runing it after each ot this 1st on none steam beta, then reinstalled medium, then steam beta,  then rebooted pc, then reinsalled revive 

Buttons do not work on any of the steps

**Comment by sirkitree** [comment] 2018-07-17 16:06
Updated to SteamVR beta - launched Medium, no buttons. I then re-installed Revive and it works! Thank you so much!

**Comment by johnboyjr** [comment] 2018-07-17 16:12
[vrclient_OculusMedium.txt](https://github.com/LibreVR/Revive/files/2202456/vrclient_OculusMedium.txt)

**Comment by Armada651** [comment] 2018-07-17 16:18
I've released a hotfix (replaced the 1.4.1 installer) that should fix an issue where input may not work on the first run.

**Comment by Armada651** [comment] 2018-07-17 16:20
@johnboyjr The log looks fine, have you checked the Settings > Controller Bindings on the SteamVR Dashboard? It should show that you're using the official "Revive for Vive Controller" binding.

If it is showing the Legacy binding or one with local changes than input will probably not work.

**Comment by gfodor** [comment] 2018-07-17 17:15
Ah, my SteamVR install had nuked itself and removed the beta (don't ask me why!) Re-installing fixed it. Amazing work!

**Comment by stema84** [comment] 2018-07-17 17:31
Working with WMR, thanks man :) Crashes on exit, but who cares. I was able to try medium for the first time. The tutorial is hard with not having the same button layout, but I'll get used to it, it looks awesome.

**Comment by Porcelainfog** [comment] 2018-07-17 18:13
I'm not sure if it helps, but 1.4 never worked with samgsung, the buttons
only worked on 1.3.   Would it be possible to give vulkan to 1.3? Maybe
look at the differences between 1.3 and 1.4, somewhere in that patch the
buttons stopped working. I know nothing about code so I feel kind of silly
even offering advice. Thank you again for your time Jules

**Comment by Armada651** [comment] 2018-07-17 19:01
@Porcelainfog Make sure you're running the SteamVR Beta, 1.4 uses the new SteamVR Input API and if you're not using the SteamVR Beta it won't work.

Vulkan is actually supported in 1.3 but the code is broken, I've tried porting the 1.4 fixes over to 1.3 but it failed.

I'll look into providing a fall-back that uses the old input API to make the transition a bit easier seeing as more people will be relying on 1.4 now.

**Comment by johnboyjr** [comment] 2018-07-17 19:31
i messed up and used steam beta not SteamVR Beta ok it working now thank you. i joined your Patreon a few weeks ago
