### ISSUE TITLE
Oculus Remote emulation not functioning

### ISSUE THREAD

**Issue by vgf89** [LibreVR/Revive#193] opened 2016-07-07 06:40 UTC
The Oculus Remote functionality does not seem to be working in 0.8.2, 0.7, or 0.6.2. The touchpad and menu button do nothing in DreamDeck and Farlands. I've made sure only one controller is connected

I just updated controller firmware today, if it makes any difference.

**Comment by iamwes** [comment] 2016-07-07 07:38
None of the oculus games currently support motion controllers, its not revive... the games are just only designed for xbox pads at the moment.

**Comment by vgf89** [comment] 2016-07-07 07:40
I'm not talking about motion controllers. I'm talking about the Oculus
Remote that comes with the Rift, AKA the Gear VR buttons/dpad input stuck
into a controller.

**Comment by iamwes** [comment] 2016-07-07 07:47
Thats not emulated, all it is used for is to press play or stop, just point with your head and use the xbox pad. Its the only way.

**Comment by vgf89** [comment] 2016-07-07 07:49
Read the Readme.md, or the number of updates on the releases page.
Multiples of them refer to the Oculus Remote mode which should work when a
single Vive controller is connected.

**Comment by iamwes** [comment] 2016-07-07 07:53
Oh i didnt even know they added that, fair enough. It really doesn't do much anyway though

**Comment by vgf89** [comment] 2016-07-07 07:55
Farlands is unplayable without this working, so not, it's not "not much". And having to connect an additional controller for games that shouldn't even need more than a measly 5 button remote is annoying.

**Comment by iamwes** [comment] 2016-07-07 07:57
I have played fairlands with my xbox remote quite a bit it works fine

**Comment by LibreVR** [comment] 2016-07-07 10:37
I'll test it soon, but it has always worked for me.

In general I need a better solution for switching between Oculus Touch and Oculus Remote support. Turning controllers off makes sense since you would never use just one Oculus Touch, but it does result in a lot of people not even realizing you can use a Vive controller as an Oculus Remote.

**Comment by LibreVR** [comment] 2016-07-07 19:32
Reproduced the issue, will release a hotfix.

**Comment by LibreVR** [comment] 2016-07-07 20:30
Fixed in 2877f98e0a47212f0dd85aa37b32fa7bba361bca.

Go to the frontpage to download the new release.

**Closed** 2016-07-07 20:31 UTC
