### ISSUE TITLE
Superhot - worked once, black screen

### ISSUE THREAD

**Issue by ehhwerd** [LibreVR/Revive#400] opened 2016-12-20 06:57 UTC
Installed revive and bought superhot a few days ago and it worked great.

Tried to launch it today and superhot just launches with a black screen.

Tried reinstalling revive and superhot both, same result.

The oculus avatars thing works fine though.

**Comment by michaelmsheen** [comment] 2017-01-20 23:29
Did you ever find a fix? I'm having the same problem.

**Comment by Armada651** [comment] 2017-02-17 15:26
Closing this bug as I can't reproduce the issue. Feel free to leave a comment here if you're still running into this issue.

**Closed by Armada651** 2017-02-17 15:26 UTC
