### ISSUE TITLE
games not showing up(lone echo) 

### ISSUE THREAD

**Issue by hylke1992** [LibreVR/Revive#910] opened 2018-01-24 22:36 UTC
reviveoverlay
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest: C:\Program Files\Revive\revive.vrmanifest
Loaded manifest: C:\Program Files\Revive\app.vrmanifest
Loaded manifest: C:\Program Files\Revive\support.vrmanifest
Oculus Library found: F:\oculus\
qrc:/Overlay.qml:219:9: QML AnimatedImage: Error Reading Animated Image File file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/tools/bin/content/vrmonitor/icons/icon_loading.gif
qrc:/Overlay.qml:41:5: QML ListModel: remove: indices [4 - 4] out of range [0 - 4]
Loading manifest: file:///f:/oculus/Manifests/ready-at-dawn-echo-arena.json
Loading manifest: file:///f:/oculus/Manifests/ready-at-dawn-lone-echo.json
Found application ready-at-dawn-echo-arena
Found application ready-at-dawn-lone-echo
qrc:/Overlay.qml:84:13: QML Image: Cannot open: file:///F:/oculus/Software/StoreAssets/ready-at-dawn-echo-arena_assets/cover_square_image.jpg
qrc:/Overlay.qml:84:13: QML Image: Cannot open: file:///F:/oculus/Software/StoreAssets/ready-at-dawn-lone-echo_assets/cover_square_image.jpg

injector
Launched injector with: "C:\Program Files\Revive\Revive\ReviveInjector_x64.exe"  F:/SteamLibrary/SteamApps/common/ARK/ShooterGame/Binaries/Win64/ShooterGame.exe
Creating process: F:/SteamLibrary/SteamApps/common/ARK/ShooterGame/Binaries/Win64/ShooterGame.exe 
Failed to create process

**Comment by Armada651** [comment] 2018-01-24 22:36
Duplicate of #907

**Closed by Armada651** 2018-01-24 22:36 UTC
