### ISSUE TITLE
Superhot VR Endless mode revive Shortcut Launch Failed - Failed to Launch Superhot VR

### ISSUE THREAD

**Issue by DrakeLandon** [LibreVR/Revive#528] opened 2017-03-07 23:40 UTC
I recently installed the Superhot endless mode update and wanted to play it through revive. I booted up revive and upon attempting to launch Superhot from the revive dashboard, it simply responds with a noise and nothing happens. When launching it directly from steam, I get a notification that says Steam- Shortcut Launch Failed Failed to Launch Superhot VR. I can't seem to find anything to fix this.  Thanks for the responses.

**Comment by Armada651** [comment] 2017-03-07 23:42
Try rebooting SteamVR, if that doesn't work please upload your log files from `%APPDATA%\Revive`.

**Comment by sirchandistroix** [comment] 2017-03-07 23:51
ditto for me, PC restart and SteamVR restart - still cannot launch since downloading the update.

[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/826184/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/826185/ReviveOverlay.txt)

**Comment by DrakeLandon** [comment] 2017-03-07 23:51
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/826188/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/826189/ReviveOverlay.txt)

**Comment by Armada651** [comment] 2017-03-07 23:52
> Creating process: C:\Program Files\Oculus\Software\Software\superhot-superhot\superhotvr.exe 
> Failed to create process

Can you check if this file exists?

**Comment by DrakeLandon** [comment] 2017-03-07 23:54
There is the superhot_Data, superhotvr_Data and the superhot.exe

**Comment by DrakeLandon** [comment] 2017-03-07 23:54
at this file location I mean

**Comment by Armada651** [comment] 2017-03-07 23:55
What happens if you try and launch superhot.exe?

**Comment by DrakeLandon** [comment] 2017-03-07 23:56
So it launches what seems to be the game with a weird frozen shot. I'll try launching steam VR

**Comment by Armada651** [comment] 2017-03-07 23:57
That's fine, at least it launches. I'm not sure what's going on.

You didn't move the Software directory to another harddrive right? Can you try restarting Steam and running it as the Administrator?

**Comment by DrakeLandon** [comment] 2017-03-07 23:58
Yeah that does not seem to fix it, it is still a frozen screen of the game. I have not moved my directory. I'll run steam as administrator.

**Comment by sirchandistroix** [comment] 2017-03-08 00:01
Just chiming in to say I have had the same results as @DrakeLandon so far. Could it be that it is looking for superhotVR.exe when the file name is superhot.exe?

**Comment by DrakeLandon** [comment] 2017-03-08 00:02
Ok, so, I ran steam as administrator and superhot.exe along with steam VR. The superhot game is still a frozen shot whith still no ability to play it. When I put on the headset I am still at the vive hub.

**Comment by Armada651** [comment] 2017-03-08 00:02
@sirchandistroix That is correct, I was reading over that last part.

**Comment by Armada651** [comment] 2017-03-08 00:03
Okay here is the fix: Superhot changed the filename of the executable, but Revive still has the old one cached.

I recommend you re-install Revive, that will clear the cache, you can just install over your existing installation.

**Comment by sirchandistroix** [comment] 2017-03-08 00:04
@Armada651 Thank you, much appreciated. I will give this a shot right now and report back.

**Comment by DrakeLandon** [comment] 2017-03-08 00:04
Same, thanks guys.

**Comment by Armada651** [comment] 2017-03-08 00:06
I'll look into either refreshing this information more often.

I'll probably have the Revive dashboard always use the information from Oculus directly rather than reusing the same information used to add the games to your Steam library.

**Comment by sirchandistroix** [comment] 2017-03-08 00:09
Confirmed, I reinstalled Revive and the updated SuperhotVR now works A-OK.

**Comment by DrakeLandon** [comment] 2017-03-08 00:15
Yep, It works! Thanks again, excellent feedback!

**Comment by CarrotSurvivor** [comment] 2017-03-09 21:51
its not working anymore :( it just launches to a black screen now ive done everything .. used to work perfectly

**Comment by sirchandistroix** [comment] 2017-03-09 22:00
did you reinstall Revive? My power has been out the last few days, can't see for myself.

**Comment by CarrotSurvivor** [comment] 2017-03-09 23:15
yes, restarted steam vr, PC, reinstalled super hot .... its not working .. just launched into a black screen

**Comment by sirchandistroix** [comment] 2017-03-10 07:05
got power back on and fired up Superhot VR in Revive...still works. I have no experience with programming unfortunately, wish I could say more than 'did you try turning it off and on again?'

**Comment by CarrotSurvivor** [comment] 2017-03-10 08:08
I've resinstslled revive 5 times, restarted everything, reinstalled super hot.... itsnjist not working it keeps launching toms black screen. Before this new update (super hot forever update) it worked fine !!

**Comment by CarrotSurvivor** [comment] 2017-03-10 08:10
I really want to try this will uploading the output log from revive help? If armada651 confirms that he'll check it out I'll do that .. really wanna play this :(

**Comment by funderburgh** [comment] 2017-03-11 17:35
I'm having the same issue, was working fine before the update

**Comment by funderburgh** [comment] 2017-03-11 17:39
Spoke too soon, I quit steam vr, uninstalled revive, reinstalled it and then started steam vr. Everything works now!!

**Comment by Armada651** [comment] 2017-03-11 17:40
@funderburgh Yes, that was specifically mentioned in the comments as the solution.

**Comment by Armada651** [comment] 2017-04-15 16:44
Going to postpone the planned dashboard changes to version 1.2.

**Comment by Dragoboss** [comment] 2018-12-22 20:49
Original ticket owner solved their issues as did some others.
Closing this ticket.

**Closed by Dragoboss** 2018-12-22 20:49 UTC
