### ISSUE TITLE
Robinson: The Journey Headset not found

### ISSUE THREAD

**Issue by LLesGTU** [LibreVR/Revive#494] opened 2017-02-13 16:47 UTC
When I try to start the steam version of the game, I receive "Hardware issue: No VR Device available".

**Comment by ReckonerVR** [comment] 2017-02-13 19:30
Same issue here. 

![image](https://cloud.githubusercontent.com/assets/25752667/22899459/cd885f2a-f222-11e6-8ca2-76e23883e729.png)

**Comment by Bonhovis** [comment] 2017-02-13 19:48
Same error unfortunately! Although, reportedly it works with the Oculus Store version okay! Tried to both Inject and Patch, but to no avail.

**Comment by Armada651** [comment] 2017-02-13 21:52
Probably has something to do with no one being able to play the Steam version, even with an Oculus headset: http://www.roadtovr.com/robinson-the-journey-steam-vr-release-bug-oculus-rift-htc-vive-support/

Different error though.

**Comment by ReckonerVR** [comment] 2017-02-13 21:55
Yeah, error has been patched and Rift users seem to be fine with the Steam version now.

I've updated and this is a different issue, presumably specific for Revive at the moment.

**Comment by peteostro** [comment] 2017-02-14 14:27
Same here. Seems to be failing on the Head set check. I wonder if the developers are doing a different in game check for it since i believe for now this is an Oculus exclusive title, which they want you to buy from oculus home. Could be the reason why they steam version had the initial bug.

**Comment by Armada651** [comment] 2017-02-15 12:43
Duplicate of #489.

**Closed by Armada651** 2017-02-15 12:43 UTC
