### ISSUE TITLE
Wont let me play echo arena its says I dont have hardware set up

### ISSUE THREAD

**Issue by KennyTheKennyPlease** [LibreVR/Revive#972] opened 2018-04-30 05:51 UTC
Everytime I try launching echo arena it has an error and closes right after I start it. i try uninstalling and reinstalling both revive and oculus please help!

**Comment by AltVRat** [comment] 2018-07-01 10:38
Same thing happened to me after the update to Echo VR and the latest Oculus. As a last ditch effort I did a direct injection from the revive app and it worked!! Revive library failed, Vive home failed, Oculus failed of course but then inject and go!!!

**Comment by Armada651** [comment] 2018-07-01 10:52
Duplicate of issue #1015.

**Closed by Armada651** 2018-07-01 10:52 UTC
Labels: question
