### ISSUE TITLE
RE- Asgard's Wrath button menu issue (Htc Vive cosmos) follow up #1362

### ISSUE THREAD

**Issue by Evildancer81** [LibreVR/Revive#1364] opened 2019-10-18 23:32 UTC
I allow me to copy this topic which had with the status "closed"
Sorry if it's not the right approach
----
 Evildancer81 commented 2 days ago •

Hi,

I have an issue with the second chapter after beating the kraken.
The game asks me to press the "menu" button (see attachment) but none of them work on my hands tracking controller htc vive cosmos

Do you have a solution? Do I need to configure the button somewhere

![rezrzre](https://user-images.githubusercontent.com/56655981/67133723-6afde980-f20e-11e9-9e76-474fe73b65f4.JPG)

Thank you in advance
----
@Evildancer81 Evildancer81 added the question label 2 days ago
@KaooT
KaooT commented yesterday •

Same issue here on a Cosmos, menu not working in Asgard's Wrath or Lone Echo. Mapping to menu in the controller settings doesn't seem to fix it.
-----
@Armada651
Member
Armada651 commented 13 hours ago •

Rebound the menu (enter) button to the bumper above the trigger in version 1.9.0.1. It might be a bit of an inconvenient location, but I do not know if the Vive Cosmos controllers have an application menu button anywhere.
If you know of another button that's free that doesn't open the VR dashboard, let me know in this issue.
@Armada651 Armada651 closed this 13 hours ago
@Evildancer81
Author
------
Evildancer81 commented 8 hours ago

@Armada651 : Hi, thanks for your answer.
I don't know if that's what you're talking about but when you try to push the menu button on the left controller It does nothing (I mean in the Asgard wrath) While the same button on the right controller works and opens the VR Dashboard.

It's like the left menu button is disabled on Revive or in the game.

![67106770-85fb3a00-f1cb-11e9-9c6c-e3a9dd747b13](https://user-images.githubusercontent.com/56655981/67133951-9a612600-f20f-11e9-929d-0098ae3e2962.JPG)

Thanks for your support.

Cosmos controller

**Comment by KaooT** [comment] 2019-10-19 10:57
For now, the fix for mapping the menu function to the left bumper works like a charm. Oculus won't ever support those bumper buttons anyway, because their controllers don't have those buttons.

**Comment by gunnarweibrink** [comment] 2019-10-19 16:10
Otherwise it won't help them... "me".
I got the same problem with oculus quest: ALVR > SteamVR > Revive > Asgard's Wrath = no menu.

Touch Controller config left hand:
- Menu-Button = SteamVR Dashboard (turning it off won't help either)
- Joystick/ThumbStick = moving (forth/back/left/right) - press/touch = no function

Touch Controller config right hand: 
- Menu-Button = Oculus Home "task manager"
- Joystick/ThumbStick = turning (right/left) - press/touch = center view

Would be perfect, to map the ingame function "menu" to press left hand ThumbStick.
Everthing else works like a charm... no stuttering oder glitches with 1.9.0!

Thank you for your really outstanding support!

**Comment by Armada651** [comment] 2019-10-19 21:49
For the Oculus Touch you have to do that yourself in the SteamVR controller
settings. If I would rebind it to the left thumbstick then people would
complain the left thumbstick isn't bound.

Since so many people are using the Oculus Touch binding now I'll add a
chord for it. Perhaps pressing both face buttons at the same time?

**Comment by Evildancer81** [comment] 2019-10-19 22:05
"Perhaps pressing both face buttons at the same time". It seems to me to be a very good idea.

Anyway thanks for your help and time.

**Comment by Armada651** [comment] 2019-10-19 22:14
@Evildancer81 For Vive Cosmos it's already bound to the bump, but I'll also bind it to the menu button.

**Comment by Armada651** [comment] 2019-10-19 22:50
Duplicate of #1362

**Closed by Armada651** 2019-10-19 22:50 UTC
Labels: question

**Comment by Evildancer81** [comment] 2019-10-20 17:49
It works now!

Many thanks @Armada651
