### ISSUE TITLE
Quill/Medium - Possible to improve trigger sensitivity? 

### ISSUE THREAD

**Issue by chemb0t** [LibreVR/Revive#452] opened 2017-01-11 01:06 UTC
Hi there, 

I had a chance to try out Quill and Medium and noticed that there may be an issue with the way trigger sensitivity is mapped to the Vive controllers. In both of these apps, it is possible to vary the brush size or transparency based on how much you squeeze the trigger. However it seems like there is a jump when the trigger is fully pressed. You can go from about 10% to 60% size/opacity while lightly squeezing the trigger, then beyond that point, it feels like a physical button is engaged/clicked in the Vive controller and the brush would jump to 100%. It would be nice if there could be a smoother transition, perhaps setting the smooth trigger motion from 0-100% and then leaving the fully pressed position at 100%.   

To reproduce this behavior in medium, go to the clay brush settings and turn on "Trigger" under the Feather heading. For Quill, it should be enabled by default. 

![2017-01-10 17_00_31](https://cloud.githubusercontent.com/assets/25044337/21831192/d5da7dac-d756-11e6-884c-071467857e56.jpg)

**Comment by Armada651** [comment] 2017-01-11 01:31
The problem is that Revive gets the trigger value directly from OpenVR. This means that the behaviour you're describing is a SteamVR issue. I could work around this issue by multiplying the value by 1.67, but that's an ugly hack.

**Comment by chemb0t** [comment] 2017-01-11 02:17
Thanks for the quick response. I did a little more digging and it seems that this behavior could be coming from a bug fix; http://steamcommunity.com/app/358720/discussions/0/615086038684288967/

> Added early trigger press to the SteamVR controller that is included with the HTC Vive Developer Edition. The triggers should now report as "pressed" when they get close to the bottom even if the hardware switch hasn't actually been pressed yet.

That probably explains why it jumps. Sounds like developers are implementing their own trigger values to compensate for the default behavior as well. Considering that this may be an issue specific to Oculus based apps, would it be possible to add a "Disable early trigger press" option to Revive so that it maps a smooth curve?  Or would that still be in OpenVR's domain?

**Comment by boberfly** [comment] 2017-01-15 04:05
Hi,
I tested it today in Medium and found the same issue, so I hope this can be enabled! Everything else seems to work, the thumbstick emulation is a bit tricky but workable.

**Comment by vdruts** [comment] 2017-01-25 17:16
Yeah, I'm hoping for an improvement as well. I'm especially having trouble with the sensitivity of the touch-pad that increases your brush size in Medium. It's very imprecise and almost impossible to vary the width of your stroke as you begin.

**Comment by RygorX** [comment] 2017-02-18 23:11
Signed up to plead for this hack - override its really hard to get much subtlety out of Medium with the current situation :/

**Comment by Armada651** [comment] 2017-02-18 23:40
@chemb0t That's not why it jumps, the hardware trigger is causing it to jump. The bugfix just made it so the "trigger pressed" event is not bound to the hardware trigger, but is actually just a trigger threshold instead.

The problem with the trigger is that it's not properly calibrated, causing it to jump at the end when the hardware trigger is pressed. It would be much better if this curve was calibrated on the OpenVR side rather than hacks implemented in Revive.

So please plead for a proper fix on the forums I linked to before pleading for a hack here.

**Comment by Dragoboss** [comment] 2018-12-22 20:46
On top of this being over a year old, I am 99.9% sure that this can now be done easily through the SteamVR binding system.
Closing ticket as its no longer relevant.

Please post a new ticket in the new issue format for any further / new issues.

**Closed by Dragoboss** 2018-12-22 20:46 UTC
Labels: enhancement
