### ISSUE TITLE
Robo Recall Stuck on Menu after updating to 1.5 with the third beta version of Revive

### ISSUE THREAD

**Issue by DoomDavid** [LibreVR/Revive#843] opened 2017-12-06 16:05 UTC
After Robo Recall decided to update to 1.5 my Revive version then no longer worked. I believe I was using the second beta version at the time. I then updated to the third beta version and unfortunately, Robo Recall no longer showed up in the Revive dashboard. I started it up by injecting which worked, but as the game started my controllers disappeared and pressing buttons on the controllers did nothing. As some previous issue said, the solution of opening and closing the dashboard was unsuccessful for me. Pressing keys on the keyboard could bring me to the main menu of Robo Recall (obviously), but that was it. I have tried reinstalling the game as well as reinstalling Revive which did not work. Just to clarify, I'm not super familiar with Revive as I learned of it recently. Was wondering if anyone has a solution. All input is appreciated by me!

**Comment by Armada651** [comment] 2017-12-06 16:07
Duplicate of #840

**Closed by Armada651** 2017-12-06 16:07 UTC
