### ISSUE TITLE
Vader Immortal crashes on revive 1.7.2.4

### ISSUE THREAD

**Issue by Nordomus** [LibreVR/Revive#1288] opened 2019-08-05 16:38 UTC
It crashes before it even starts. It was working perfectly fine on previous version.

### Technical Information
  - CPU: i7 6700K
  - GPU: GTX 1080Ti
  - RAM: 16 GB
  - OS: Windows 10 Pro
  - Valve Index

#### Versions and features
  - Revive 1.7.2.4
  - SteamVR beta 1.6.10

**Comment by e270889o** [comment] 2019-08-05 21:44
Same here

**Technical Information**

- CPU: i7 4770K

- GPU: GTX 1070

- RAM: 32 GB

- OS: Windows 10 Pro

- Lenovo Explorer

**Versions and features**

- Revive 1.7.2.4

- SteamVR beta 1.6.10

**Comment by T-Hutch** [comment] 2019-08-06 16:14
Same here, as well:
Technical Information

CPU: i5 7600K

GPU: GTX 1080 TI

RAM: 16 GB

OS: Windows 10 Home

Versions and features

Revive 1.7.2.6

SteamVR Version:	1.6.10 (1564442420)

**Comment by squishyderpy** [comment] 2019-08-07 05:54
Crash on startup, then launches on my main screen saying it can not detect the VR hardware.

CPU: I7 - 7820X
GPU: RTX2080Ti
RAM: 32GB
OS: Windows 10pro
Revive: 1.7.2.6
SteamVR: Version 1.7.1 (1565041651)

**Comment by mapotter99** [comment] 2019-08-08 00:04
Same.

**Comment by noodle1009** [comment] 2019-08-08 19:29
thanks for information on 1.7.0 - can confirm that release works for me too.

Prior to that was getting the [UE4-WKND crash](https://i.imgur.com/Il7Og23.png).

Also I have to dial in the video settings as low, otherwise there's some sort of weird ghosting going on when I move my head from side to side.

@Armada651 is there any information we could collect on this that would help?

**Comment by squishyderpy** [comment] 2019-08-08 20:45
Confirmed as launching on 1.7.0.3, with Steam VR updated today to1 .7.2, although the performances are ok, it's shaky as hell as soon as my head or character moves.

As soon as I updated again, it crashed again. Hope this helps fixing things :)

**Comment by mapotter99** [comment] 2019-08-09 06:41
Yes, graphics have had to be set to low for all systems on revive to prevent judder. 

If this isn’t the case for someone, please chime in.

**Comment by Armada651** [comment] 2019-08-11 01:25
Fixed in latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.3

**Closed by Armada651** 2019-08-11 01:25 UTC
