### ISSUE TITLE
No Game Icons 

### ISSUE THREAD

**Issue by BoneHawk1** [LibreVR/Revive#907] opened 2018-01-21 20:08 UTC
Hello,

All was working well for a while but recently whenever I opened the revive tab I was presented with blank icons for my games making it a guessing game as to which game I was selecting. Is there any way for this to be fixed?

**Comment by baggyg** [comment] 2018-01-22 18:54
I have the same issue. I am not sure if this is related to the new Rift core, which I believe has different manifest locations.

**Comment by tkapis** [comment] 2018-01-23 14:39
It seems that the cause of this is that the StoreAssets folder is now empty.

**Comment by Armada651** [comment] 2018-01-23 14:52
@baggyg Isn't the new Rift core only on the Public Test Channel?

**Comment by baggyg** [comment] 2018-01-23 15:05
No, it just got launched to everyone with the option to downgrade to use the classic home.

https://www.digitaltrends.com/computing/oculus-vr-rift-core-20-january-update/

**Comment by Armada651** [comment] 2018-01-23 15:08
Must be a staged roll-out, I still didn't get the update.

**Comment by lllsondowlll** [comment] 2018-01-24 06:46
I'm having the same issue. This is the first time using revive for me, and I thought the games weren't showing up so I was troubleshooting the wrong thing for hours until I stumbled my cursor over a blank space and it lit up. The other pre-installed games have icons but nothing purchased / downloaded

**Comment by Armada651** [comment] 2018-01-24 12:59
I'll try installing Oculus from scratch, I just can't seem to get the version installed that reproduces this behaviour even if I enroll in the Public Test Channel.

**Comment by baggyg** [comment] 2018-01-24 13:23
The PTC / New core maybe a red herring, although there are similar apps (Oculus Tray Tool) that have also been broken by it. I think there is enough of us reporting the same issue, that for sure something is going wrong. Is there any debug mode / information I could pull out the diagnose the issue?

**Comment by Armada651** [comment] 2018-01-24 13:33
You can try posting your log file from `%APPDATA%\Revive`, just drag the `ReviveOverlay.txt` file into the comment box here.

**Comment by Armada651** [comment] 2018-01-24 13:46
Ok, after a complete clean install I finally got the same version you guys have. It looks like the StoreAssets folder was moved to `C:\Program Files\Oculus\CoreData\Software`. I'll update the paths to reflect this, but the fact that this is a staged rollout means that unless I also implement fallback code this is going to result in it breaking for all people still stuck on the old version.

**Comment by baggyg** [comment] 2018-01-24 14:10
The eventual plan is that everyone is on core 2.0, so I would think over time this may break for everyone. Hopefully there is something identifiable in the StoreAssets to determine it is active and you can branch the location of this.

**Comment by Armada651** [comment] 2018-01-24 14:25
Some people may opt-out of core 2.0 though and that would break it if I don't have fall-back code.

**Comment by baggyg** [comment] 2018-01-24 14:30
I believe the opt out of Core 2 is only a temporary option and they will be taking that away at some point.

**Comment by Armada651** [comment] 2018-01-24 14:34
Just to be clear, we're discussing whether to have a fallback at all, I fully intend to support the cover art feature in Core 2.0.

**Comment by alexvance89** [comment] 2018-01-25 19:33
Is it possible to make these paths configurable in the future so we could temporarily resolve these issues ourselves? Also would be nice if when we inject a game path that it stores a history of say the most recent injected games? Just a thought.. Thanks for the work.

**Comment by ConorKnoxx** [comment] 2018-01-25 22:31
yeah, same problem here. I see the file/tree: C:\Program Files\Oculus\CoreData\Software - so is there somewhere else Revive is looking for this (in other words can I copy this folder somewhere else to make it work for now?)

**Comment by baggyg** [comment] 2018-01-26 09:50
I suppose if you were really impatient for the official fix you could play around with adding a symlink to the new folder. However that could cause untold issues.

**Comment by fireplug911** [comment] 2018-01-27 00:53
A simple temporary fix looks to be to just copy the Oculus StoreAssets folder from its new location to the old location (they are just a bunch of image files so shouldn't hurt to be in two places.)

**Go to C:\Program Files\Oculus\CoreData\Software\ and right click then copy the folder called StoreAssets

then go to C:\Program Files\Oculus\Software\Software\ and right click then paste the folder there.**

This will bring back all the icons when you list them in library view. It will also bring back the pictures in Revive view, but it looks like another change to the Oculus core is only letting 15 titles show there right now. Of course, if you download new Oculus games, those wont show unless you copy their StoreAssets files over too.

**Comment by ConorKnoxx** [comment] 2018-01-27 22:11
aha! That worked perfectly. I realize its good until you change/add a game, but its certainly an easy patch in the meantime. Thanks fireplug911

**Comment by Armada651** [comment] 2018-01-28 17:38
Fixed in version 1.2.1, please download the latest release.

**Closed by Armada651** 2018-01-28 17:38 UTC

**Comment by Armada651** [comment] 2018-01-28 17:42
Also, in the future if the game icon can't be found then the overlay will show some placeholder text. This should serve as a good enough fallback.

**Comment by hylke1992** [comment] 2018-01-29 20:00
it doesn't work for me. :(

**Comment by baggyg** [comment] 2018-01-30 09:31
@hylke1992 Probably would be helpful to share a little more information than that.... do you see the placeholder text showing the game names?

**Comment by hylke1992** [comment] 2018-01-30 10:31
it works now. I got a message to download the new update but it didn't. After downloading the new update from the site it worked.
