### ISSUE TITLE
Getting failed entitlement check after the Oculus 1.13 update

### ISSUE THREAD

**Issue by GuidoFida** [LibreVR/Revive#557] opened 2017-03-29 03:34 UTC
I only have 2 games, "Rock Band VR" and the game you get free with a purchase, "Ripcoil". I have been playing RBVR no problem since it came out March 23, but after the 1.13 update I fail the entitlement check on both games, even after doing beta>restart and restarting my PC.

**Comment by Brody79** [comment] 2017-03-29 20:31
I can confirm this. Oculus Store update 1.13 seems to bring back the old forced "entitlement check".
A few games still work if I patch them manually (i.e. Edge of Nowhere or Lucky's Tale) with the Revive tray icon but every title fails to start from the Dashboard. Titles like Defense Grid 2 or Chronos don't work at all.

**Comment by Armada651** [comment] 2017-03-29 20:33
If the old entitlement check was back, then using manual injection would also fail. They probably just changed their manifests which the Revive Dashboard relies on to detect Oculus applications.

**Comment by Armada651** [comment] 2017-03-29 21:04
Please make sure you're running the latest version of Revive (Use Check for updates in the tray icon menu). If it still doesn't work, post your logs from `%APPDATA%\Revive` (Just enter that into the address bar of a folder and drag the files in the comment box here)

Also, please post your Revive manifest located at `C:\Program Files\Revive\revive.vrmanifest`.

**Comment by Brody79** [comment] 2017-03-29 22:12
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/880516/ReviveOverlay.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/880517/ReviveInjector.txt)
I'm not sure if this will help since the logs don't show any errors. I'm using the latest Revive version (1.0.6.0).

**Comment by Brody79** [comment] 2017-03-29 22:16
Maybe it's important to not that the Oculus Store automatically opens with SteamVR since the 1.13 update. If you close it, it shows the warning that no VR games will work without it. If you start any Oculus game from the dashboard, the Oculus Store automatically opens again.

**Comment by hyperseven** [comment] 2017-03-29 22:19
> Maybe it's important to not that the Oculus Store automatically opens with SteamVR since the 1.13 update. If you close it, it shows the warning that no VR games will work without it. If you start any Oculus game from the dashboard, the Oculus Store automatically opens again.

Even with Revive dashboard uninstalled it still does this :(

**Comment by Armada651** [comment] 2017-03-29 22:21
@Brody79 I think you need to keep the Oculus Store open to pass the entitlement checks.

**Comment by Brody79** [comment] 2017-03-29 22:26
@Armada651 I already tried this several times. It doesn't help.

**Comment by GuidoFida** [comment] 2017-03-30 00:13
I too am on the latest version 1.0.6.0

[revive.txt](https://github.com/LibreVR/Revive/files/880685/revive.txt)
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/880686/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/880687/ReviveOverlay.txt)

**Comment by Brody79** [comment] 2017-03-30 07:41
@hyperseven If you stop and disable the Oculus runtime service the Oculus Store will not open up automatically anymore, but your Revive games won't work for obvious reasons. Most don't work at the moment anyways, though.

**Comment by Armada651** [comment] 2017-03-30 12:59
I'm unable to reproduce any of the reported problems, I recommend reinstalling the Oculus software.

**Comment by Brody79** [comment] 2017-03-30 13:18
I already clicked on repair from the Oculus Setup. It downloaded the whole package again (1.5GB) and reinstalled. I did not have to reinstall every Oculus game using this method but the problem with Revive persisted. I will try to completely uninstall and reinstall the software again (I can do so in a few hours).

It all started directly after the latest Oculus Store update and regarding to reddit there are a few other people with problems after this update: [Thread 1](https://www.reddit.com/r/Vive/comments/62611u/revive_not_working_game_windows_is_black/), [Thread 2](https://www.reddit.com/r/Vive/comments/62cdg7/oculus_app_starting_by_itself/)

**Comment by Brody79** [comment] 2017-03-30 13:22
@Armada651 [This guy](https://github.com/LibreVR/Revive/issues/559) already reinstalled the Oculus software with no luck.

**Comment by Armada651** [comment] 2017-03-30 14:52
I still cannot reproduce the error, but what @Brody79 is implying is that the injector fails, but patching does work.

@Brody79 Can you attempt to launch an application from the dashboard that does not work and then send the logs from `%APPDATA%\Revive`?

**Comment by Brody79** [comment] 2017-03-30 15:51
[ReviveInjector.txt](https://github.com/LibreVR/Revive/files/882993/ReviveInjector.txt)
[ReviveOverlay.txt](https://github.com/LibreVR/Revive/files/882994/ReviveOverlay.txt)
I attempted to run Defense Grid 2, this time by running it from the Steam library instead of the dashboard.
"Game failed entitlement check".
Nothing helpful in the logs, though.

**Comment by Brody79** [comment] 2017-03-30 16:54
I did find something out that makes no sense to me:
If I inject the game executable by dragging and dropping onto the Revive\ReviveInjector_x64.exe it works!
But if I inject via the tray icon or try to run it from the dashboard, it fails.
I already tried uninstalling and reinstalling Revive and it changed nothing. I don't get it.

**Comment by Armada651** [comment] 2017-03-30 17:04
Sounds like a user rights problem, possibly related to UAC. Try installing Revive in the default Program Files location. Applications installed in Program Files get more privileges.

**Comment by CarrotSurvivor** [comment] 2017-03-30 19:23
i think i know the issue! The 1.13 update added a button in oculus home settings to either allow or disallow unkown sources not reviewed by oculus to run on rift! try to enable this setting and see if it fixes the issue.

**Comment by Brody79** [comment] 2017-03-30 19:33
@Armada651 It actually was the UAC! Reinstalling Revive to C:\Program Files didn't do the trick but starting Steam with Administrator privilege did.
@CarrotSurvivor Thanks, but this button exists for a long time and was already set to allow unknown sources in my case.

**Comment by CarrotSurvivor** [comment] 2017-03-30 19:34
okay, by the way i bought Giant Cop guys, ill let you know if it works in case your interested.

**Comment by GuidoFida** [comment] 2017-03-30 19:40
Running Steam as admin also did the trick for me, even though Revive was already installed in Program Files to begin with

**Comment by Armada651** [comment] 2017-03-30 22:18
Are the people encountering this problem running Windows 7 or 10?

**Comment by LinosM** [comment] 2017-03-30 22:23
Windows 10

**Comment by CarrotSurvivor** [comment] 2017-03-30 23:07
giant cop is not working, make a ticket. :(

**Comment by KyleGospo** [comment] 2017-03-31 19:52
Have you tried going into the oculus store and doing the restart oculus option under beta in settings?

That fixed it for me.

**Comment by PixelSplitter** [comment] 2017-04-01 01:11
Hey I had the very same issue. Starting Steam and Oculus Home as admin did not resolve it but exiting from Revive via the system tray button then restarting it from the root folder as admin resolved the problem :)

**Comment by jonnypanic** [comment] 2017-04-01 10:44
Cheers, PixelSplitter, that solved it for me. It was driving me mad.

**Comment by alexagui** [comment] 2017-04-03 01:36
Confirming PixelSplitter's recommendation to run the Revive Dashboard as administrator on Windows 10 Pro worked for me.

**Comment by China-VR-DRAGONCITY** [comment] 2017-04-25 08:32
me too,reinstall oculus home failed. reinstall REVIVE1.1.1 failed.reinstall rock band vr failed.
restarting revive from the root folder as admin,......failde........I tried all the ways I failed.
**I will try to reinstall the system**

**Comment by Dragoboss** [comment] 2018-12-16 12:06
@China-VR-DRAGONCITY
Please make a new report if this is still an issue for you.

Closing this as it appears it was indeed an UAC problem and this ticket is over a year old.

**Closed by Dragoboss** 2018-12-16 12:06 UTC
