### ISSUE TITLE
X Moon Productions - XStoryPlayer 3.5 - ReviveInjector

### ISSUE THREAD

**Issue by Skidrow68** [LibreVR/Revive#145] opened 2016-06-10 20:57 UTC
Can you enplane how i should do it then? what i tried was drop the exe file on ReviveInjector_x64.exe.

Please dont close it direct you answer.

**Comment by LibreVR** [comment] 2016-06-11 09:30
You should give me a lot more info:

- Where did you buy this game? Steam? Oculus Home? Or is it standalone?
- What is in the Revive logs found in `%APPDATA%\Revive`?
- Are you using the Vive headset?

**Comment by Skidrow68** [comment] 2016-06-11 10:09
Its a standalone game that makes it own engiene, so it dont use unreal or so. Revive is installed on D:\Revive and the game on E:\X Moon Productions\XStoryPlayer 3.5. Ocukus is also installed D:\Oculus

Yes i use a Vive headset.

**Comment by LibreVR** [comment] 2016-06-11 11:36
Ah I see you made a duplicate of issue #131. No reason for that, I just closed it because it's not a bug in Revive. You can continue to post in that issue and I'll still be notified. Please post your logs in that issue.

Closed as duplicate of issue #131.

**Closed by LibreVR** 2016-06-11 11:36 UTC
