### ISSUE TITLE
Bullet Train Only Shows on My Monitor

### ISSUE THREAD

**Issue by Sukotto85** [LibreVR/Revive#380] opened 2016-12-13 21:37 UTC
Hi all, 

Every time I start bullet train, the image won't display on the Vive, only on my monitor. 

I start up Lucky's Tale, which feels perfectly. 

Any ideas?

**Comment by kvdv99** [comment] 2016-12-14 01:08
same here

**Comment by Sukotto85** [comment] 2016-12-14 18:00
At least I am not the only one. I have searched the net. Sadly couldn't find a fix.

**Comment by bcbfrancis** [comment] 2016-12-14 18:06
I had the same problem yesterday. 

I started it directly with the injector, but the game only started on my monitor. 

Then i tried to start it on the dashboard, and this worked for me. 

But first i just saw a white room, until i turned around and the game started.

**Comment by Sukotto85** [comment] 2016-12-14 18:29
Ah, 

How do I start it from the injector? 

I shall try it again later. 

Thanks, Francis.

**Comment by LibreVR** [comment] 2016-12-14 19:31
Starting using the injector will not work, you need to use the dashboard.

**Comment by Sukotto85** [comment] 2016-12-14 19:43
Hi Libre, 

I am running the latest version. I will try it again later.

**Comment by kvdv99** [comment] 2016-12-14 21:01
Running 1.0.1, tried it using the dashboard overlay,  and also tried it with injector : in both cases, the game started running on my desktop screen only, the headset showed only the usual SteamVR environment.

**Comment by LibreVR** [comment] 2016-12-14 21:43
Can you try the latest version 1.0.3?

**Comment by kvdv99** [comment] 2016-12-14 22:49
Just installed 1.0.3 but same result for me : only on my desktop screen.

**Comment by starks1** [comment] 2016-12-16 15:31
Hi, I have a similar issue using both 1.0.3 and 1.0.1.  I get the unresponsive win64... .exe error that was prior to 1.0.1.

gtx 1070
i52500k
latest nvidia driver, steamvr (and steamvr beta).

**Comment by laserob** [comment] 2016-12-16 20:10
I have the same issue. The game launches in desktop mode. When I select game window I can hear audio as well. I see a bunch of missed frames while loading like it wants to load in headset, but doesn't. The Revive menu continues spinning while the game is launched and cannot select anything else until I quit app from desktop window. Other Revive apps load fine like Lucky's Tale, Dreamdeck and the Touch demos.

**Comment by LibreVR** [comment] 2016-12-16 20:13
Is the application on the desktop frozen or does it just not display on the headset?

**Comment by laserob** [comment] 2016-12-16 21:09
The application is running. I can see and hear the game on the monitor in desktop mode. Moving the headset does not affect the camera. Camera shows a static low angle shot of what I believe is the train floor.

**Comment by LibreVR** [comment] 2016-12-16 21:11
Sounds like you are either running an older version of Revive or you didn't start it through the Revive Dashboard.

If you still can't get it to work, can you post the logs from `%APPDATA%\Revive`? Just rename them to .txt files and drag them in the comment box here.

**Comment by Sukotto85** [comment] 2016-12-16 22:19
Since running 1.0.3 it runs perfectly

**Comment by LibreVR** [comment] 2016-12-17 00:51
Yeah, everyone here really needs to make sure they are on the latest version, while SteamVR is running the system tray on the desktop has a Revive icon. Right-click that one and click "Check for updates" .

**Comment by LibreVR** [comment] 2016-12-17 00:52
It has also been confirmed that @kvdv99 was running an older version because he had two installations of Revive in different locations. So I'll close this as invalid.

**Closed by LibreVR** 2016-12-17 00:52 UTC
