### ISSUE TITLE
Oculus Dreamdeck and First Contact

### ISSUE THREAD

**Issue by kvdv99** [LibreVR/Revive#511] opened 2017-02-22 15:42 UTC
both these titles are no longer working for me..

First Contact -> on the monitor everything is mirrored correctly, but headset only displays black screen
Dreamdeck -> I only see something that resembles the colors (grey for opening screen, green for first world, etc) but nothing more than a solid color all around (with some flickering when I move)...

**Comment by Armada651** [comment] 2017-02-22 15:42
Going to do a new release soon that will hopefully fix these launching issues.

**Comment by kvdv99** [comment] 2017-02-22 18:34
many thanks!!

**Comment by Armada651** [comment] 2017-02-22 21:09
New release has been uploaded, can you confirm that it is now fixed?

**Comment by octo1234** [comment] 2017-02-22 21:31
1.0.5.1  with latest Steam Beta  I'm having the same problem

**Comment by mapotter99** [comment] 2017-02-23 00:39
Same issue here in multiple programs with 1.0.5.1

At least the following are affected:

Dreamdeck 
Showdown
First Contact
Touch Tutorial

**Comment by mapotter99** [comment] 2017-02-23 00:54
Add "Dear Angelica" to the list of programs affected by this nasty problem. 

Lucky's Tale, Henry, Quill, Medium, I Expect You To Die, and Unspoken all work fine.

**Comment by Armada651** [comment] 2017-02-23 01:43
> I only see something that resembles the colors (grey for opening screen, green for first world, etc) but nothing more than a solid color all around (with some flickering when I move)...

Sounds like some kind of render target issue. It's likely that the headset is only showing one pixel for some reason.

**Comment by mapotter99** [comment] 2017-02-24 00:32
I resolved this by turning off SteamVR Betas and reverting to the current release version of SteamVR. 

That said, a new problem with Dreamdeck has shown itself.  Dreamdeck completely closes when selecting a scene from the in-app menu. No crash... no freeze. The program just quits back to the Vive home screen. I'll create a new issue about this.

**Comment by kvdv99** [comment] 2017-02-24 10:38
I would prefer to keep using SteamVR Betas, so I hope a new patch will be released.
WIth SteamVR beta + Revive 1.0.5.1  :  Dreamdeck, Showdown, First Contact and Dear Angelica are still not working.

Thanks to the dev(s) for all the hard work!

**Comment by Armada651** [comment] 2017-02-24 17:10
@kvdv99 I looked at the issue, it's not caused by Revive. There is a bug in the SteamVR beta, which isn't really surprising, it's a beta for a reason.

**Comment by kvdv99** [comment] 2017-02-25 17:00
Yes, correct,  opting out from SteamVR beta solved all issues.
Dreamdeck also works perfectly.
Thanks!

**Comment by mapotter99** [comment] 2017-02-25 17:04
@kvdv99, are you having the problem I described in issue #514, where Dreamdeck closes when selecting a scene?

**Comment by kvdv99** [comment] 2017-02-25 17:32
Ah I didn't try the selection (how do you select?). I just let autoplay start and then click thumbpad up to skip to the next. Didn't watch them all, I think about 5 or 6, and they all worked.

Kris

**Comment by mapotter99** [comment] 2017-02-25 17:36
There are two versions of Dreamdeck... a version that came with the Oculus Store and a version that can be downloaded separately. The separate version allows you to press down at the Dreamdeck homescreen, and allows you to select which scene to start. 

I should add that I'm only having the problem on 1.0.5.1.

**Comment by mapotter99** [comment] 2017-02-25 22:15
Well, today it's working fine with 1.0.5.1. Not sure what's up with that!  Anyway, glad to have everything working!

I must say, with all this wrapped up, 1.0.5.1 seems to be the most stable and best performing release yet... until Oculus or SteamVR breaks something again!

**Comment by rclough** [comment] 2017-03-09 04:20
can confirm this is happening to me with the SteamVR beta, works once I revert to regular steam.

**Comment by Armada651** [comment] 2017-04-17 01:37
Since this issue was reported the SteamVR Beta switched back to the same supersampling code as the stable branch, so this issue is now fixed.

**Closed by Armada651** 2017-04-17 01:37 UTC
