### ISSUE TITLE
SteamVR update breaks the Revive Dashboard

### ISSUE THREAD

**Issue by IBootleg** [LibreVR/Revive#478] opened 2017-02-02 04:58 UTC
Title pretty much says it all.  Ever since the Vive update with the new loading screens, none of the oculus games run.  I re installed revive and still nothing.  Any suggestions?

**Comment by ptdean82** [comment] 2017-02-04 20:01
Same for me. I had used Superhot previously, as well as a couple freebies. After I heard about the Superhot update I tried to check it out, it doesn't load up.

A bit more detail:

1. Revive tab still shows up in the tray, and my games are still in there.
2. When you click on a game, you get the circular waiting animation. After a while, you get the in-game sounds in the headset. On the monitor, you'll see that the game has started, a window shows a view from inside the game (as it would normally during a VR game). The view does not correspond to the headset orientation, though. Controllers are visible in front of you in this windowed view, and do not respond to movements of the actual Vive controllers.
3. I have uninstalled and reinstalled Oculus, and then reinstalled the latest version of Revive (as of today). Same problem persists.

**Comment by ChaseLangley** [comment] 2017-02-05 19:09
Would love to know whats going on with this. Been skeptical of Revive since I heard about it - but heard such good things I took the plunge. Thank you for working on Revive - but hoping this is solved soon as my trust lead me to purchase products I cannot currently play.
Thank you :]

**Comment by Armada651** [comment] 2017-02-17 15:32
I tried launching a few games today without any problems. Have you tried re-installing SteamVR?

**Comment by Armada651** [comment] 2017-02-17 16:01
Ah I can now reproduce the problem, but only by using the Revive Dashboard. There seems to have been some change in the way SteamVR handles application loading.

**Comment by ptdean82** [comment] 2017-02-17 18:34
It seems to work perfectly if you click on the game from inside the Steam
application (on the computer).

**Comment by Armada651** [comment] 2017-02-22 18:11
Should be fixed in the latest release.

**Closed by Armada651** 2017-02-22 18:11 UTC
