### ISSUE TITLE
Jittery in all games and Apps after SteamVR update 1.1.3

### ISSUE THREAD

**Issue by Pitrakos** [LibreVR/Revive#1123] opened 2018-11-29 21:28 UTC
Please post if you have same issue.

Happens alson with 1.5 version

Thanks

**Comment by flowerdealer** [comment] 2018-11-30 05:30
Dirt Rally is also completely broken for me.

**Comment by macfly123** [comment] 2018-12-02 13:31
Jittery in Dirt is extreme.

**Comment by Armada651** [comment] 2018-12-03 09:18
None of you mentioned the headset you're using. If you're using Mixed Reality headsets with Revive on SteamVR then latency, lag and tracking issue are to be expected.

**Comment by masta2k9** [comment] 2018-12-03 17:35
Same problem here (Dirt Rally).
Worked fine with previous SteamVR version.
Using Oculus Rift CV1 with latest updates.

**Comment by flowerdealer** [comment] 2018-12-03 17:43
> None of you mentioned the headset you're using. If you're using Mixed Reality headsets with Revive on SteamVR then latency, lag and tracking issue are to be expected.

Using Samsung Odyssey. Never had issues with this since on WindowsMR until this release. Revive has always worked with good performance for me since day one, except a few bugs with games not running, white screen on Dirt Rally, etc.

**Comment by sotobon** [comment] 2018-12-03 19:51
I wanted to comment that since the update of steamvr 1.1.3 with my hmd samsung I have problems only in the games of oculus creating a live in the image when I move my head and it prevents me from being able to play someone could help me "thanks"

**Comment by sotobon** [comment] 2018-12-03 19:53
the problem is that the image lives by moving the head alone with the games of oculus those of steam go well all help pls

**Comment by sotobon** [comment] 2018-12-03 21:19
> Ninguno de ustedes mencionó el auricular que está usando. Si está usando auriculares de realidad mixta con Revive en SteamVR, entonces se esperan problemas de latencia, retraso y seguimiento.

the problems we are having with mixed reality could be solved ??

**Comment by dborosev** [comment] 2018-12-04 00:40
Odyssey+ headset, and jittery.  Also, I can't seem to reliably run the games anymore.  Some won't open at all.

**Comment by FoxtrotD** [comment] 2018-12-04 13:16
Hello! thanks for the work with revive.

Same ploblem here. I have windows mixed reality, Dell Visor.  Since friday 30 november i have a problem with oculus games. In brass tactics, which I have bought, it is unplayable, the fps is good(70-90 fps) but all game tembles when turning his head, vibration in the image, in the tracking of the movement of the viewer. I played a lot of hours at brass tactics, It has always worked very well but not now sinde friday 30 november aprox. Same problem with all games oculus, echo combat, contact, etc. With the games steam vr, rec room, karnage chronicles etc work very well, as usual. I have 1809 w10 version.

I have 2 friends with the same problem, wmr samsung odyssey.

I hope it can be solved, encouraged and thanks.

**Comment by cappaholic** [comment] 2018-12-07 13:47
Same problem with TribeXR on a Dell Visor. Also started with SteamVR 1.1.3.

**Comment by sotobon** [comment] 2018-12-08 19:06
buenas amigos ya he encontrado la solucion para que vuelva a ir bien los juegos de oculus en wmr aqui dejo las instrucciones

https://steamcommunity.com/app/250820/discussions/0/1741101364288717349/
![roll_back_steamvr](https://user-images.githubusercontent.com/11430483/49689669-b3e00e80-fb24-11e8-9609-2fc8f820cc30.jpg)

un saludo

**Comment by sotobon** [comment] 2018-12-08 21:43
> Sotobon. 
> ¿Pero SteamVR no se actualizará automáticamente una vez que estés en línea?


you put it in disconnected mode, and the only thing we can not play steam games online

**Comment by FoxtrotD** [comment] 2018-12-09 13:49
It works for me, download the steam version and everything works as usual. It is steamvr beta motion smoothing problem, have annoyed the whole community with this update and do not leave the option to deactivate it. I will not buy steam again until they fix it. We should make a forum in steam.

**Comment by Dragoboss** [comment] 2018-12-15 17:35
So in any case I'll close this ticket with the message that if you didn't jitter before SteamVR 1.1.3 and do now, it is because of the newer SteamVR motion smoothing.

There are several suggested solutions in this thread, main on being just disabling motion smoothing and see how that goes.

Any further issues please post a new ticket with more details following the newly set format.

**Closed by Dragoboss** 2018-12-15 17:35 UTC
