### ISSUE TITLE
entitlement check Chronos 

### ISSUE THREAD

**Issue by knetterspetter** [LibreVR/Revive#503] opened 2017-02-19 09:36 UTC
I could always play Chronos with my HTC Vive but now i get the Entitlement check error.
Somoene else have the same problem? THX

**Comment by Armada651** [comment] 2017-02-19 10:23
The is a problem with the new SteamVR update, of games will fail to initialize when you start them from the dashboard. You could try starting them from your Steam Library or injecting manually from the tray icon menu.

Closing this as duplicate of #478.

**Closed by Armada651** 2017-02-19 10:23 UTC

**Comment by knetterspetter** [comment] 2017-02-19 11:12
Thank you Armada. Already tried to eject the game manually from the tray icon menu from Revive and also Patch it. But i get the same error. Can i start this game from my steamVR library? Because i need to drag the exe file to the revivelnjector x64 exe. Do you know this?? Thx

**Comment by Armada651** [comment] 2017-02-19 11:17
I'm having a hard time understanding you. Are you saying it works correctly when using the injector manually?

Please explain your problem more clearly.

**Comment by knetterspetter** [comment] 2017-02-19 11:36
Hi, no it does not work. It used to work with the injector. But now not anymore. I tried different things but still get the Entitlement check error.

**Comment by knetterspetter** [comment] 2017-02-19 11:39
The game starts up when i'm using the injector. Also in VR, but after the Unreal Logo I get Entitlement check error.

**Comment by Armada651** [comment] 2017-02-19 15:53
An entitlement error means that the Oculus software thinks you don't own the game. There's not much I can do about that, perhaps you can try reinstalling the Oculus software?
