### ISSUE TITLE
Multiple hard drive install location support

### ISSUE THREAD

**Issue by jgeorge12** [LibreVR/Revive#1363] opened 2019-10-18 20:53 UTC
**Which game or application is your request about?**
[e.g. First Contact]
Asgard's Wrath

**Is your request related to a problem? Please describe.**

I have installed Asgard's Wrath on a different hard drive as my main Oculus Library because of the large size and it is not showing up in revive. I believe this is because revive can only locate my main oculus library on the original hard drive. I am also unable to inject the program.

**Describe the solution you'd like**
I'd like it to automatically add library locations from multiple hard drives or at least allow you to manually point to another library location. 

**Describe alternatives you've considered**

I've attempted injecting and restarting several times. All other installed oculus games show up but Asgard's Wrath does not show up.

**Additional context**

I apologize if this isn't the problem. If there is already some way to work around this.  I'd appreciate any help or a feature update in the future.

Thanks for your help,

**Comment by Armada651** [comment] 2019-10-19 14:42
duplicate of #928

**Closed** 2019-10-19 14:42 UTC
Labels: question
