### ISSUE TITLE
Failed to start ReviveOverlay

### ISSUE THREAD

**Issue by lahesis333** [LibreVR/Revive#185] opened 2016-07-03 14:05 UTC
When I try to start ReviveOverlay every time I get an error. I tried to reinstall the software version to an earlier and install the latest version of the error does not disappear. Help please advice! I already tried to reinstall the operating system, but still remained an error ...

The signature of the problem:
  Event Name the problem: APPCRASH
  Application Name: ReviveOverlay.exe
  Application Version: 0.0.0.0
  Mark application time: 574885cd
  The module name with the error: ReviveOverlay.exe
  Module version with an error: 0.0.0.0
  Stamp module-time error: 574885cd
  Exception code: c0000005
  Offset exceptions: 0000000000003b3a
  OS Version: 6.1.7601.2.1.0.256.1
  Language code: 1049
  Additional Information 1: 28f7
  2 For more information: 28f7588e8161581e2b7636aa4cdbf4ef
  3 For more information: 7b14
  More information 4: 7b149801ef548e8d4cbec40902162321

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

If privacy statement is not available in the internet, check out his local version:
  C: \ Windows \ system32 \ ru-RU \ erofflps.txt

**Comment by LibreVR** [comment] 2016-07-03 14:10
Duplicate of issue #156.

**Closed** 2016-07-03 14:10 UTC
Labels: duplicate
