### ISSUE TITLE
The Climb --) Laggy as hell

### ISSUE THREAD

**Issue by joeyb197** [LibreVR/Revive#427] opened 2016-12-28 22:24 UTC
Hey !

First, sorry for my bad English, if bad my English is.

So, I bought "The Climb" yesterday. I wanted to play it so badly. I launched it. I did the tutorial without any problems. Then I launched a real level.

BOOM! disgusting graphics and extremely laggy/choppy/... 
The image doesn't follow the movement of my head and it kinda jump. 

looks like his case : (https://github.com/LibreVR/Revive/issues/403)

So, I've a GTX 970 and a i5-4460.

I've asked on many forums what could be the problem. They answered me that : it's not the ram, it's probably not the i5 and it's not the motherboard (yes I aksed those questions because I'm noob at those things)

SO. Conclusion. It's PROBABLY the GPU.

So, I've some questions.

IS IT the GPU?
Is it normal?
What can I do?
Should I buy another GPU/CPU/Ram/whatever else
How can I play games like these with a great quality (because at the moment, my The Climbs settings are awful (screenshots following))
I want so bad to play Fallout 4 VR when it'll come out, so what should I do(buy) to be able to play in Full HD? (This isn't a ReVive question, but if you could answer it, it would be awesome! :D)

Thanks a lot for your time !

Sincerely, Joey.

N.B. The game works well for one of my friend who have a GTX 970 and a i5-4460, just like me, but he has 12GB of Ram and an occulus, not a vive. What's the difference? 

The climb settings : 
The climb resolution : 1200x720
Everything (pretty much) touching graphics (shadows) are on "low"

**Comment by LibreVR** [comment] 2016-12-28 23:23
Set the climb to the lowest settings and then follow these instructions to submit performance data: https://github.com/LibreVR/Revive/issues/353#issuecomment-265434808

That would help me in finding the bottleneck on your system. I will also run some more tests on my own PC to check for bottlenecks I can optimize there.

**Comment by joeyb197** [comment] 2016-12-29 03:39
Houston we have a problem

So, I was able to take a picutre with my phone of my screen, but not a screenshot. The problem was that every time I clicked out the game to take the screenshot, the game paused and the frames just came back at normal.

For the vrframes.cs thing, I didn't find the file :/ I even did a research in the whole PC, but couldn't find it.

Thanks anyway for any answers.


![image](https://cloud.githubusercontent.com/assets/24771594/21536262/6f7b2be0-cd4e-11e6-8941-f639a588e712.png)

**Comment by mapotter99** [comment] 2016-12-29 15:33
@LibreVR, I'm having some serious lag in "The Climb" as well with an i7 and a GTX 1070. It used to run smoothly. 

I'll see if I can get and share performance data.

**Comment by mapotter99** [comment] 2016-12-29 16:35
Ok, so the "Save Frame Data Now" button doesn't seem to be creating a log file. I've tried repeatedly, and no file titled "VRframes.csv" appears in the log folder. Possible bug with the current beta of SteamVR?

That all said, I'm wondering if the performance issues with "The Climb" aren't issues with the game itself, rather than Revive, based on the reddit about performance issues in "The Climb" ever since the Graphics menu was added. The reddit page was referenced in a previous issue related to "The Climb" which should probably be merged with this one.

**Comment by mapotter99** [comment] 2016-12-29 16:36
The reddit was mentioned in a comment in issue 403.

**Comment by CarrotSurvivor** [comment] 2017-01-06 18:01
You need to disable async reprojection and disable interleaved reprojection and then enable always on reprojection :)

**Comment by sthaber** [comment] 2017-01-14 01:44
Hi there. Same issue here. I have a slightly overclocked 980Ti that used to run this game fine back when I had a Rift. I fired it up in ReVive recently to try out the new touch controls, and the perf is bad. Screenshot and raw frame data attached.

<img width="962" alt="capture" src="https://cloud.githubusercontent.com/assets/1794470/21951164/c7713964-d9b7-11e6-9c28-cfd552c055d0.PNG">

[VRFrames.txt](https://github.com/LibreVR/Revive/files/705678/VRFrames.txt)

**Comment by Armada651** [comment] 2017-01-14 03:00
Duplicate of #403.

**Closed by Armada651** 2017-01-14 03:00 UTC
