### ISSUE TITLE
Dirt Rally no sound. Injector doesn't work.

### ISSUE THREAD

**Issue by Raging-Beard** [LibreVR/Revive#235] opened 2016-08-19 04:45 UTC
I now have no sound :(
The injector never worked for me so I had to use that patch that was created. Unfortunately using that I get no sound so I tried using the latest injector, which as before just does not load the game at all for me.

**Comment by Hitman29413** [comment] 2016-08-19 14:13
Same Problem here...:(

**Comment by dom334** [comment] 2016-08-19 16:18
same problem here no sound since update would never boot with injector but would boot with the special 1 he created

**Comment by Raging-Beard** [comment] 2016-08-20 12:29
I'm hoping LibreVR comes to the rescue again!

**Comment by LibreVR** [comment] 2016-08-20 21:00
Well, it's even worse for me, a crash right when I start the race. But anyway, I'm on it no need for ridiculous titles.

**Comment by taikila** [comment] 2016-08-20 21:27
Same issue here

**Comment by LibreVR** [comment] 2016-08-20 23:12
Closing this issue as it is an exact duplicate of issue #232.

**Closed by LibreVR** 2016-08-20 23:12 UTC
