### ISSUE TITLE
Newest version of Remixed issues in Echo vr

### ISSUE THREAD

**Issue by Porcelainfog** [LibreVR/Revive#1128] opened 2018-12-05 01:44 UTC
I just checked out the latest version of remixed for echo vr, samsung odyssey OG. The game booted up great, no lag or stutter anymore. The latest update really fixed that (i didn't realize how much latency I was putting up with before now).

There are some bugs though. For instance, when I charge to shoot my pistol my hand will go in weird direction instantly, I think its the 'forward' direction that you would look towards the menus when you first start a game. No matter what I do, when i pull the trigger my arm shoots to the same direction until i release the trigger. Throwing frisbees is now also worse. When I throw it, it basically doesn't leave my hand. I can throw it quite hard and it will just sit there the second I release.

The strangest part about the frisbee is that the latest update basically fixed the over the shoulder grenade throws. They are also little disks, but they mustive been coded differently. Before this patch they didn't throw straight, now they throw perfectly. 

I didn't test throwing the balls, dinosaurs, or darts yet. 

Thanks again for all the hardwork, if I knew anything about code i'd contribute in that way; this is the most I can give back.

**Comment by Dragoboss** [comment] 2018-12-05 05:04
The ordnance is slightly different from the disc in their physics.
That was also noticeable in Revive but probably not as much...
I'll do some testing tonight see what I'll find. I think this is the same issue I've seen last just before Echo VR broke totally with Remixed.
Something to do with the way Remixed translates the tracking and possibly something with trigger delay, too.

Can you tell me if it is something similar to what I describe in this video from a long time ago?
https://m.twitch.tv/videos/264715636

**Comment by TesseractCat** [comment] 2018-12-05 16:43
I too get these issues in game. However the charge to shoot hand direction issue only happens with the 'comet' gun, and none of the other guns. Comet is the only gun that has a charge to shoot functionality, so I'm guessing that ingame they do something with the controller when charging the gun.

**Comment by Goanna7007** [comment] 2018-12-07 02:09
> Throwing frisbees is now also worse. When I throw it, it basically doesn't leave my hand. I can throw it quite hard and it will just sit there the second I release.

I also have the same problem, pretty much impossible to play arena.

**Comment by Werbel** [comment] 2018-12-09 05:30
Can you guys use Controler Bindings?

http://127.0.0.1:8998/dashboard/controllerbinding.html

There is a setting for a grip button where you can set values for things.

https://i.imgur.com/PdW33o7.png
https://i.imgur.com/l3uW2N2.png

Downgrade speed and drop speed to the max fixed problem for me.

I use the Knuckles so it might be different, but it should be there.

**Comment by TesseractCat** [comment] 2018-12-09 05:34
This is for revive remixed which does the not interact with steam vr, the controller binding menu is a feature of steam vr which is not relevant to this issue.

**Comment by Dragoboss** [comment] 2018-12-15 19:15
This is being worked on but no ETA is given at this point.
The cause is known thanks to @TesseractCat 

I'll update this ticket once there is new info available / a fix is ready.
Attaching image of chat with Echo dev for reference.
https://cdn.discordapp.com/attachments/313285397801205761/521851122374410240/unknown.png

**Comment by Dragoboss** [comment] 2018-12-15 19:53
Commit 04c4f1f3080f0d4980533248f02fafa3814ef6e0 should fix the disc throwing issue as well as the issue occuring in Echo Combat with the comet positioning weirdly upon trigger-press.

Will be in next release.
Assuming fixed upon next release, will reopen if not.

**Closed by Dragoboss** 2018-12-15 19:53 UTC
Labels: bug, remixed
