### ISSUE TITLE
Oculus Runtime 1.4 blocks Revive from working

### ISSUE THREAD

**Issue by cccpphil** [LibreVR/Revive#100] opened 2016-05-20 09:41 UTC
Hello,
The games do not work anymore since the update Oculus (Entitlement check failed)

**Comment by LibreVR** [comment] 2016-05-20 10:28
As far as I know, there is no 1.4 Runtime. You simply forgot to reboot the Oculus software. Go to `Settings > Beta > Restart Oculus` in Oculus Home to solve this problem.

**Comment by LibreVR** [comment] 2016-05-20 10:40
Seems like they indeed updated the runtime, I'll come up with a fix soon.

**Comment by vraddict** [comment] 2016-05-20 10:44
Same here !! all games stopped working (Entitlement check failed) (unable to find headset) ..

**Comment by LibreVR** [comment] 2016-05-20 11:02
@vraddict Can you try extracting [these DLLs](https://github.com/LibreVR/Revive/releases/download/0.5.1/LibOVRPlatform.zip) next to the game executable? If that doesn't work try extracting them in `Oculus\Support\oculus-runtime` (Make backups!)

**Comment by vraddict** [comment] 2016-05-20 11:17
Tried the DLLs in Oculus\Support\oculus-runtime and next to executables !! still the same for me not working !

**Comment by LibreVR** [comment] 2016-05-20 11:27
Ok, well I'll have to come up with a proper fix then. I'll examine the update this weekend and see what measures they've taken.

**Comment by vraddict** [comment] 2016-05-20 11:53
update after some testing !!  Strange things happening  !! none of my 12 oculus games showing up in steam anymore.. Also VR-Tennis online still works with the injector by dragging the executable to reviveinjector.
none of the other games work anymore.....

**Comment by LibreVR** [comment] 2016-05-20 11:55
@vraddict Can you check whether those games have been automatically moved from `Oculus\Software` to `Oculus\OculusGames`?

**Comment by vraddict** [comment] 2016-05-20 12:06
okay for some reason in oculus store my game where showing as not installed in the library, But all games are still in oculus/software.. ive reinstalled the games which overwrites the games in oculus/software... all game are now showing in steam and on revive dash....

**Comment by LibreVR** [comment] 2016-05-20 12:07
But they're still not starting right?

**Comment by vraddict** [comment] 2016-05-20 12:07
still not starting !!

**Comment by LibreVR** [comment] 2016-05-20 12:09
Have you tested the injector?

**Comment by vraddict** [comment] 2016-05-20 12:12
yes tested the only game that runs is vr tennis which i guess does not use the oculus DRM

**Comment by LibreVR** [comment] 2016-05-20 12:16
Can you post the logs after you've tried running a game that doesn't work? I wonder if there's anything interesting in there.

**Comment by vraddict** [comment] 2016-05-20 12:22
Launched injector with: ReviveInjector_x86.exe /handle 364
Injecting process handle: 364
Injecting DLL: C:\Program Files\Revive\Revive\x86\openvr_api.dll
LoadLibrary found at address: 0x77944bf0
Injecting DLL: C:\Program Files\Revive\Revive\x86\LibRevive32_1.dll
LoadLibrary found at address: 0x77944bf0
Injected dlls succesfully

**Comment by vraddict** [comment] 2016-05-20 12:24
Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/viewpoint-games-ltd-vr-karts/VRKarts.exe"
Creating process: C:\Program Files\Oculus\Software\viewpoint-games-ltd-vr-karts\VRKarts.exe
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x308e74d0
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x308e74d0
Injected dlls succesfully

**Comment by LibreVR** [comment] 2016-05-20 12:27
Ok, so they didn't patch the DLL injection at least.

**Comment by vraddict** [comment] 2016-05-20 12:31
guess its down to the new runtime ?

**Comment by LibreVR** [comment] 2016-05-20 12:32
Definitely seems like it, just look at the patch notes:

> Bug fixes and security updates, including updates to platform integrity checks

**Comment by vraddict** [comment] 2016-05-20 12:46
Yep Definitely looks like the runtime,,  just to add some games fail to launch full stop.. steam - shortcut launch failed !!

**Comment by vraddict** [comment] 2016-05-20 12:58
shortcuts are fine just needed to restart steam !! on trying to run (The climb) a error pops up saying (A connection to oculus store could not be established . please check your internet connection and firewall and make sure that you are logged into your oculus store account........

**Comment by LibreVR** [comment] 2016-05-20 12:59
What about the other games on the Oculus Store?

**Comment by vraddict** [comment] 2016-05-20 13:03
so far just that one !! after i get the error all shortcuts fail and a restart of steam and steam vr  need to be restarted... i will check the games i have and report my findings asap

**Comment by LibreVR** [comment] 2016-05-20 13:06
Does Lucky's Tale, Dreamdeck, etc. work?

**Comment by SRombauts** [comment] 2016-05-20 13:11
Where can I read online about the 1.4 oculus runtime? Or is it only somewhere in the Oculus Home app?
Yesterday I tried Revive for the first time and had a great time, but I believe it was still on 1.3.0.

**Comment by vraddict** [comment] 2016-05-20 13:11
lucky`s tail (game failed entitlement check) Dreamdeck (unable to find HMD) Blash Rush ( unable to find HMD) Chronos (unable to find HMD)

**Comment by vraddict** [comment] 2016-05-20 13:13
VR Karts (quick flash on screen then nothing)

**Comment by LibreVR** [comment] 2016-05-20 13:14
@SRombauts You can read about it here: https://forums.oculus.com/community/discussion/36575/oculus-app-1-4-release-notes

@vraddict Can you try clicking `Settings > Beta > Restart Oculus` in Oculus Home? That should refresh the entitlement check and then try to boot some games again.

**Comment by vraddict** [comment] 2016-05-20 13:16
yes i did that before i started testing !!

**Comment by gormanj** [comment] 2016-05-20 13:33
All the games that I have that are not Oculus home exclusive titles are still working fine.

**Comment by LibreVR** [comment] 2016-05-20 13:36
@gormanj Definitely, I've finally been able to test the update myself. What has happened is that the Oculus Platform DRM has started to check whether the Oculus Rift is actually connected.

All games that don't use the Oculus Platform SDK are not affected.

**Comment by vraddict** [comment] 2016-05-20 13:39
@LibreVR will this be a easy fix for you ??

**Comment by SRombauts** [comment] 2016-05-20 13:40
Ouch, if they are starting to enforce DRM, this is not good for us in the mid-term...

**Comment by vraddict** [comment] 2016-05-20 13:49
DRM can be removed but cant think of any legal way of doing it....

**Comment by LibreVR** [comment] 2016-05-20 13:51
It's certainly not something I'd want to do, I want people to buy the games not pirate them.

I will see if I can fool the DRM into thinking the Rift headset is connected.

**Comment by vraddict** [comment] 2016-05-20 13:54
Sounds like a plan !!!

**Comment by LibreVR** [comment] 2016-05-20 13:57
Also, if you have an Oculus Rift CV1 or DK2 then connecting the tracking camera and headset when starting the game will work around this issue.

**Comment by vraddict** [comment] 2016-05-20 14:05
did have the DK2 but sold on when my vive arrived. Im sure you will find a work around, if you need me to do any testing , give me a shout !!

**Comment by gormanj** [comment] 2016-05-20 15:26
I think the Oculus setup installs the older version before this last update and then updates itself. However, even after installing it or replacing the runtime files and turning of the Internet so it does not update. I still have the same issues.

**Comment by vraddict** [comment] 2016-05-20 15:52
It seems the Oculus Platform DRM as been changed with the update, its checking if you have a rift connected or not.  @LibreVR  said he was looking into fooling the DRM into thinking the rift HMD is connected. cant see this been a easy fix, but we can hope.  seems to me like a silly move by Oculus if the update was intended to block revive, as of today people were happy to pay for the games on the store and support Oculus, I think there have just opened the door to Piracy which will in someway damage the VR future.....

**Comment by gormanj** [comment] 2016-05-20 15:56
WORKAROUND: This is a partial workaround. The Oculus setup currently has all the mid April files before the last update. You can reinstall the Oculus software. If you are quick you can grab all of the installer files from the Oculus Download cache folder as it is is downloading (but before it starts installing). Do not let Oculus Home update (I believe this will happen forcibly when you quit home, so firewall or pull the plug when quitting/restarting, etc). Tested: Lost, The Body VR working again.

**Comment by LibreVR** [comment] 2016-05-20 16:00
@gormanj Can you make a zip file with the OVRPlatform DLLs? You might be able to use them with the Oculus 1.4 Runtime.

**Comment by gormanj** [comment] 2016-05-20 16:12
Are these in the Oculus>Support>oculus-runtime folder?

**Comment by vraddict** [comment] 2016-05-20 17:08
@gormanj  what folder are you grabbing the files from when reinstalling home ??

**Comment by gormanj** [comment] 2016-05-20 17:21
I installed Oculus on my D: drive. A folder appeared. It was called something like "Oculus Download Cache or similar." I don't see the folder now. I am not sure if the same folder appears if you have Oculus on the C: drive. Nonetheless, you should still be able to apply the above workaround at the moment.

**Comment by vraddict** [comment] 2016-05-20 17:39
is it anything to do with the OculusOnlineSubsystem ??

**Comment by gormanj** [comment] 2016-05-20 18:47
I noticed tons of different errors depending on in what state you run the software (64bit, 32 bit, as admin, with Steam VR launched and with Oculus Home opened). As of now, if you reinstall Oculus Home, redownload your games (I know, uggh) and then stop and start the OVR service with the command line, it should fix this issue. Just don't let Oculus update. I hope someone can find a minimal solution on what to block to stop this update (right now I have as much as I can blocked, but am expecting problems with this approach).

**Comment by ViveVR** [comment] 2016-05-20 21:37
@gormanj the workaround didn't work for me.  To clarify here are the steps I took:

1. download the oculus setup from their website
2. ran installation defaults to c:\program files\oculus
3. after it finished install it took me to the oculus store and immediately says hardware not setup.
4. find lucky's tale from store and install which downloaded ~1.4 gb for the game
5. after game downloaded and installed, it asked to install some system changes needed for the game I chose yes.
6. i opened up service manager and stopped the oculus vr runtime service, which automatically closes oculus home.
7.  started the service back up and then clicked on the oculus icon to reopen.
8. opened up SteamVR and chose revive tab, clicked on lucky's tale and says entitlement check error.
9.  tried using the drag LT.exe into reviveinjector.exe and this results in "headset not connected".

Any advice?

**Comment by gormanj** [comment] 2016-05-20 21:57
I never blocked services before testing the software, so you may have blocked an entitlement check. I never tested opening the games via the revive software tab, only dragging to the executable. I will try pinning down what to do in the firewall...

Other than that, I may shut down the service FIRST, renamed or deleted the oculus runtime folder, restarted the computer, then installed. However, if you quite the OVR service and delete the entire Oculus folder, then reinstall, I know I did nothing more than that.

**Comment by ViveVR** [comment] 2016-05-20 22:51
I tried again by shutting down the oculus vr service, deleting the c:\program files\oculus folder, then restarting.   And then reinstalled oculuset setup and then install lucky's tale.  then stop and start the service which automatically brings up the oculus store.  then tried dragging the lucky's tale lt.exe to reviveinjector.exe and same thing - says no headset found.

**Comment by ViveVR** [comment] 2016-05-20 22:57
my oculus app version shows "1.4.0.224375 (1.4.0.2249996)" when you go to oculus settings and then "general"

**Comment by gormanj** [comment] 2016-05-20 23:02
Lucky's Tale is probably not the best choice to start the test with. I think I tested first with "lost" once I got that working, I knew I was on the right track. Geez, now I am tempted to let it update again, just to see if I can get it to work. However, there is the possibility that they have updated the files that the installer downloads.

**Comment by gormanj** [comment] 2016-05-20 23:15
Try this: stop the OVR service with "OVRServiceLauncher.exe -stop" in the command prompt. Then restart your computer. Then try the same command. You should get an error. Then reinstall and leave Oculus home open. Then install "Lost". Then us the same command again to stop the service. Then use OVRServiceLauncher.exe -start. Then see if "Lost" will work at that point. Do not force quit Oculus home or quit it other than with the command. Also, you might try pulling the ethernet cable or turning of WifI when you are not installing something. BTW, did you Revive working before?

**Comment by gormanj** [comment] 2016-05-20 23:28
I edited the above to include opening Steam VR and Oculus Home. I have the same version of the Oculus Home app as you. However, I am noticing that it wants to update Lucky's Tale again, so maybe that has been updated. Looking at the logs somewhere I noticed that LT might call home itself so I do not recommend testing with that until you ensure things with "Lost."

**Comment by gormanj** [comment] 2016-05-21 00:02
From an Oculus rep:
"This update wasn’t targeted at a specific hack. The added security improvements were designed to curb piracy and protect content and developers over the long term."

**Comment by Razalom** [comment] 2016-05-21 00:08
Well plugged in my DK2 and Sensor but sadly my 970 only has 1 HDMI port and the games still wont run that are in Oculus Home. Obviously might be the HDMI issue causing this but no way to test that part of it.

**Comment by gormanj** [comment] 2016-05-21 01:17
Not sure why it needs the HDMI plugged in if you are using the Vive for VR, but there is always a Display Port to HDMI adapter ($9-$12).

**Comment by ViveVR** [comment] 2016-05-21 01:22
1. stop the OVR service with "OVRServiceLauncher.exe -stop" in the command prompt. *DONE*
2. Then restart your computer.  *DONE*
3. Then try the same command. You should get an error.  *NO ERROR*

On step 3 i didn't get any error .  What is the error I should get?

**Comment by gormanj** [comment] 2016-05-21 01:35
I edited to say stop the service twice. The second time you should get an error indicating that there was not service running. Then you know it is not running. Sorry. I hope that it isn't simply that Oculus patched the files that the installer downloads. I used an installer that I had downloaded from a few days ago BTW (however, it downloads the files).

**Comment by ViveVR** [comment] 2016-05-21 02:28
I went through the process and Lost says "unable to find the HMD" when i drag the app into reviveinjector64.exe.   To answer your question if I had used Revive successfully before today - Yes, it worked on Lucky's Tale but that was the only one I had tried.

**Comment by gormanj** [comment] 2016-05-21 02:33
Wow, sorry, I am at a loss other than checking the installed dll's with a checksum. I am up to it if you are. I have some hash numbers in the logs when I think it tried to update, so I can check my files against those, but I am not exactly sure if those hashes are from the update recently or my last install which had files from mid-April. Did you want to do some checksums with me to see if our files are any different?

**Comment by ViveVR** [comment] 2016-05-21 02:58
Sure i'm up for it

**Comment by gormanj** [comment] 2016-05-21 03:01
The checksum of my "LibOVRP2P32_1.dll" file is:
60b7bdee7987e9a41b9e52afad8f5499f9dff42b083bc2278edcfc8180d549bd

I see in the OVR logs that the same file name also had a checksum of:
fd4600de5b82f92331640d9a0c0a7e9b4222c6251fd0d09f1eccaffbc8ead9f6

Presumably the second is the updated file. What is yours?

**Comment by gormanj** [comment] 2016-05-21 03:09
So I think maybe all of these files with the SHA-256 Checksums indicated are the update:

[2016-05-21 10:51:47] [DEBUG] [Installer.cpp:installPackage:365] Attempting to hot-swap oculus-runtime.  Stand by...
[2016-05-21 10:51:47] [DEBUG] [file.cpp:recursivelyCreateDirectory:111] Created directory 'D:\Oculus\swap\oculus-runtime-473a0489-7b7e-4116-b95d-99ccc476318f\\'.
[2016-05-21 10:51:47] [DEBUG] [file.cpp:recursivelyCreateDirectory:111] Created directory 'D:\Oculus\swap\oculus-runtime-473a0489-7b7e-4116-b95d-99ccc476318f\firmware\\'.
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\DirectDisplayConfig.exe
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: bb6828a77146b8cfd7c11585a7460568100e0bb07afa45c14f911db501435a6c
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRP2P32_1.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: fd4600de5b82f92331640d9a0c0a7e9b4222c6251fd0d09f1eccaffbc8ead9f6
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRP2P64_1.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: d383e80ae1ad18c880f8cc868dfb286528302ec2d6a191be1ef54249fde51c60
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRPlatform32.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 533be2fe883cfae4db9e881167091a2b755be2f459560572364aceabc58edc4f
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRPlatform32_1.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 5eb54eb20a6952d7e87867b0752347bb4ee1d37b728611fe18be2d966ee19eb3
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRPlatform64.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 147b21ee972c1dfeaf524372610f1e95857bee5a917abdb03b5844d9594171a4
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRPlatform64_1.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: aa13a048e315343d352ce53906afde28c0e43a8548561df01beeea89ee7629f3
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRRT32_1.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 2fb32dc04eb3f1a510a4c002a83fb5ec117c4ee48fc859d06edf92d1bafaa2fe
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\LibOVRRT64_1.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: bf9e9cef0acf53a33f797f8963e11d8179301c8566846e76807d4fcfff7220cb
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\OVRServer_x64.exe
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: abd758a110bdf7cda2f0c015910b015867a3f9939aed227e74781e3e9407cddb
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\OVRServiceLauncher.exe
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 0f0f3ab11265fbe9c85b7dfb422610939fc56d615c241dc4d6819c7c46b3b0a6
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\OculusAppFramework.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 3c93e6222c9682a49cb5125b425ec592a71d6827d64e9bf9ab7d8995220cffd8
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\THIRD_PARTY_NOTICES.txt
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: d60e99bf6132f5e42dca68ddf7f49279f36eb0ec5cefe459bd3b6013105b745a
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\cacert.pem
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 451db040271ebb4bb0b953f1cc5512bd916306ba7822cc2b959182a67081f7ca
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\dbghelp.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: f0c1ba2e0c1c849d142372ec33b9d1630a2136107e7b91b99b487e0d5df6d699
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\firmware/firmware.zip
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 9e01869897a3f2a6c5f8cde9cfbed6f0ce29d3bedebeceef34e1c48f0b1086cb
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\oculus_p2p_32.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 5829f9bd96e8129d4e99771f97026935a14d0b2f8b58b10527c6b91f8521001c
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\oculus_p2p_64.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: c94de4c9087f25e9b4e181fc6a7171f5b54137d76d6e94d7af68786ec998ca18
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::verifyChecksum:66] Validating D:\Oculus\tmp\xinput1_3.dll
[2016-05-21 10:51:47] [DEBUG] [Security.cpp:Security::computeChecksum:127] Computed hash: 756cad002e1553cfa1a91ebe8c1b9380ffabe0b4b1916c4a4db802396ddfbef8
[2016-05-21 10:51:47] [DEBUG] [file.cpp:recursivelyCreateDirectory:111] Created directory 'D:\Oculus\Support\oculus-runtime\\'.
[2016-05-21 10:51:47] [DEBUG] [file.cpp:recursivelyCreateDirectory:111] Created directory 'D:\Oculus\Support\oculus-runtime\firmware\\'.
[2016-05-21 10:51:47] [DEBUG] [Installer.cpp:executeCommand:171] Success!  Committing changes.

**Comment by ViveVR** [comment] 2016-05-21 03:16
I was unable to find 'shasum.exe' on my windows 10 so I downloaded "sha256sum.exe".

C:\Program Files\Oculus\Support\oculus-runtime>sha256sum LibOVRP2P32_1.dll
fd4600de5b82f92331640d9a0c0a7e9b4222c6251fd0d09f1eccaffbc8ead9f6 *LibOVRP2P32_1.dll

**Comment by gormanj** [comment] 2016-05-21 03:23
Yep. That is the second checksum I assume is the update. Also, if you look at my log, it appears that the runtime was swapped out. Interestingly, I just noticed my computer's clock was set a day ahead. I don't think it would make any difference, but you could try to set your clock back a few days and use Oculus Setup again. Also checksum the file immediately after the installer finishes or as soon as you can find the same file. I hope someone knows how to look at where the installer is downloading from and maybe a link can be posted to the older runtime. I think the zip file is named "oculus-runtime.zip."

**Comment by gormanj** [comment] 2016-05-21 06:03
Bad news. I found the web url of the location of the runtime files that Oculus Setup downloads from and confirmed that for the same exact url the files have been updated from runtime v1.3.2.210591 to runtime version 1.4.0.224996. So reinstalling is not going to help anyone at this point. Sorry.

**Comment by gormanj** [comment] 2016-05-21 06:27
These are the files in the oculus-runtime folder that are updated (others are the same):

DirectDisplayConfig.exe
firmware/firmware.zip
LibOVRP2P32_1.dll
LibOVRP2P64_1.dll
LibOVRPlatform32_1.dll
LibOVRPlatform64_1.dll
LibOVRRT32_1.dll
LibOVRRT64_1.dll
manifest.json
OculusAppFramework.dll
OVRServer_x64.exe

Also in the Manifests folder:
oculus-runtime.json

**Comment by gormanj** [comment] 2016-05-21 06:30
Would a windows restore point on or before 5-18-2016 work if you had oculus installed on your C: drive? Maybe....

**Comment by Kennedy88** [comment] 2016-05-21 10:05
I have a complete backup of oculus-runtime folder and all support folder (V. 1.3) if you need

**Comment by kschima** [comment] 2016-05-21 10:44
It seems my Oculus Client made a backup of 1.3.2 as described here:

https://www.reddit.com/r/Vive/comments/4kd08m/revive_compatible_oculus_runtime_132_is_still_on/

**Comment by vraddict** [comment] 2016-05-21 10:58
So far managed to get (Lost + Blaze Rush ) Working. Still running test will update my findings later !!!

**Comment by LibreVR** [comment] 2016-05-21 12:09
I released [a new version](https://github.com/LibreVR/Revive/releases/tag/0.5.2) that bypasses the 1.4 DRM in at least Oculus Dreamdeck, still working on support for engines other than Unreal Engine.

**Comment by LibreVR** [comment] 2016-05-21 12:09
Oops accidental close

**Comment by vraddict** [comment] 2016-05-21 12:18
I have got all my games running again with overwriting some Dll`s in the 1.4 runtime with Dll`s from the old 1.3........

**Comment by LibreVR** [comment] 2016-05-21 12:22
That works too as a temporary workaround. But that workaround is not future-proof, eventually the games will update and will demand that the 1.4 runtime is installed.

**Comment by vraddict** [comment] 2016-05-21 12:29
Will the bypass still work with revive dash ?

**Comment by LibreVR** [comment] 2016-05-21 12:29
Probably, yes.

**Comment by caseyboy77** [comment] 2016-05-21 13:27
I've checked the revive dashboard and for some reason it comes up, but is blank.  I've also used the 5.2 dlls and have gotten Chronos to launch, but it will not go past the title screen.

**Comment by gormanj** [comment] 2016-05-21 15:53
All of my games launch (free + technolust) in the dash application in steamvr except Mythos, which has never gotten beyond a bit of startup and then black screen.

**Comment by vraddict** [comment] 2016-05-21 15:55
@gormanj Are using the new bypass dll`s or the 1.3 runtime dll`s ??

**Comment by caseyboy77** [comment] 2016-05-21 16:02
I'm trying to use the bypass, I wish I could find the 1.3 runtimes,

**Comment by vraddict** [comment] 2016-05-21 16:18
caseyboy77 :  best way to get the 1.3 runtime is to do a system restore, then save the oculus 1.3 runtime folder.... reinstall oculus home go the the runtime folder and overwrite the below files with the ones you saved...
this is just a workaround that will work untill the games are updated by Oculus.....
DirectDisplayConfig.exe
LibOVRP2P32_1.dll
LibOVRP2P64_1.dll
LibOVRPlatform32_1.dll
LibOVRPlatform64_1.dll
LibOVRRT32_1.dll
LibOVRRT64_1.dll
OculusAppFramework.dll
OVRServer_x64.exe

**Comment by caseyboy77** [comment] 2016-05-21 16:23
vraddict, I appreciate the info, I was irresponsible and did not have system restore enabled. Fresh install. do you know of any other way to get a hold of these files?

**Comment by vraddict** [comment] 2016-05-21 16:28
add me on steam

**Comment by caseyboy77** [comment] 2016-05-21 16:32
ok, I sent the invite

**Comment by kschima** [comment] 2016-05-21 17:08
I made a downgrade patch:
https://www.reddit.com/r/Vive/comments/4kd08m/revive_compatible_oculus_runtime_132_is_still_on/

**Comment by DasSmeagle** [comment] 2016-05-21 18:30
Thanks for that Downgrade Patch! ;)

Nobody mentioned it, I can't even Start "Oculus Home" any more. Before and after using the Downgrade Patch. All I get is "Set your View in VR - Stand up and put on your headset........" and a Link: "Continue in your Headset". Which does nothing. Is it the same to you?

![unbenannt](https://cloud.githubusercontent.com/assets/18378891/15450100/b82f6c30-1f92-11e6-8cc0-21bf17381729.PNG)

Thanks,
- Oliver

**Comment by vraddict** [comment] 2016-05-21 18:32
you have gone into HMD setup which should have been skipped.....

**Comment by DasSmeagle** [comment] 2016-05-21 19:28
vraddict ; Hmm, maybe by accident :( Possible. 

Anything I can do to skip that? Even after restart this will show up. But it's not that important, I will not buy new stuff now before the situation is more clear and the installed stuff works.

**Comment by vraddict** [comment] 2016-05-21 19:54
DasSmeagle : you just need to uninstall home and remove all oculus folders from appdata local and roaming.... you will need to show hidden files to do this...
oculus home will be back to start ..... remember to skip the HMD setup

hope this helps

**Comment by gormanj** [comment] 2016-05-21 22:58
There are instructions online for clearing out Oculus and reinstalling while also preserving your game downloads.

....(to answer previous question) I am still on pure 1.3.2 without update.

**Comment by DasSmeagle** [comment] 2016-05-22 07:28
Thanks! ;)

**Comment by paulasheville** [comment] 2016-05-22 16:14
So, is the new version verified as working? I installed the new Revive today, opened the revive tab in steam and tried to launch Blazerush and got an HMD not found error. Should I have the Oculus store/library app open when doing this? I've tried both open and closed. Please advise. Thanks!

**Comment by paulasheville** [comment] 2016-05-23 00:47
I have the old runtimes an the newest Revive install and I'm only able to play Blazerush. All other games give me an error of "failed entitlement check" or "app launched from a non trusted source". What am I doing wrong? The games not working are Dreamdeck, Lucky's Tale, Chronos, Henry, and Farlands.

**Comment by LibreVR** [comment] 2016-05-27 18:31
This has been fixed in Revive 0.6, grab the new release from the Releases page.

**Comment by sirkitree** [comment] 2016-05-27 18:56
Thanks for all your hard work on this!

I see Lucky's Tale working, and Oculus Video. w00t!

Darknet is not working for me. Comes up with a loading screen and then back to my SteamVR environment.

**Comment by LibreVR** [comment] 2016-05-27 19:03
I think Darknet has always had problems.

**Closed by LibreVR** 2016-05-27 19:03 UTC
