### ISSUE TITLE
EVE: Valkyrie pop up a window:run via the launcher

### ISSUE THREAD

**Issue by lanya0702** [LibreVR/Revive#169] opened 2016-06-28 12:28 UTC
I use injector,and got this window,game did not start

**Comment by LibreVR** [comment] 2016-06-28 12:46
EVE Valkyrie should be launched through the Revive Dashboard if possible.

**Comment by lanya0702** [comment] 2016-06-28 12:51
My problem is i can open Dashboard,but cant open game

**Comment by lanya0702** [comment] 2016-06-28 12:51
Is there any way to start game with injector?

**Comment by LibreVR** [comment] 2016-06-28 12:52
> My problem is i can open Dashboard,but cant open game 

Please give a more detailed explanation why you can't use the dashboard.

**Comment by lanya0702** [comment] 2016-06-28 12:55
I use shadowsocks to visit oculus.

**Comment by LibreVR** [comment] 2016-06-28 12:57
How does that prevent you from using the dashboard to launch the game? If you installed the game through Oculus Home then the Revive dashboard will detect it.

**Comment by lanya0702** [comment] 2016-06-28 13:01
I can see the game in the dashboard,but when i push the button,nothing happened

**Comment by LibreVR** [comment] 2016-06-28 13:15
Can you provide the log files from `%APPDATA%\Revive` and the manifest from `C:\Program Files\Revive\revive.vrmanifest`?

**Comment by lanya0702** [comment] 2016-06-28 13:34
libpng warning: iCCP: known incorrect sRGB profile
Loaded manifest from: C:\Program Files (x86)\Revive\revive.vrmanifest
Runtime directory: file:///C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
Oculus directory: file:///D:/Oculus/
Loading assets manifest: file:///d:/Oculus/Software/Manifests/altspacevr-altspacevr-pc_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/baobab-studios-invasion-for-rift_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/ccp-games-newcastle-eve-valkyrie_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/colosseteam-colosse-a-story-in-virtual-reality_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/epic-games-showdown_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/oculus-dreamdeck_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/oculus-farlands_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/oculus-oculus-video_assets.json
Loading assets manifest: file:///d:/Oculus/Software/Manifests/playful-luckys-tale_assets.json
Found assets bundle altspacevr-altspacevr-pc_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/altspacevr-altspacevr-pc.json
Found assets bundle baobab-studios-invasion-for-rift_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/baobab-studios-invasion-for-rift.json
Found assets bundle ccp-games-newcastle-eve-valkyrie_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/ccp-games-newcastle-eve-valkyrie.json
Found assets bundle colosseteam-colosse-a-story-in-virtual-reality_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/colosseteam-colosse-a-story-in-virtual-reality.json
Found assets bundle epic-games-showdown_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/epic-games-showdown.json
Found assets bundle oculus-dreamdeck_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/oculus-dreamdeck.json
Found assets bundle oculus-farlands_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/oculus-farlands.json
Found assets bundle oculus-oculus-video_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/oculus-oculus-video.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///D:/Oculus/Software/Manifests/playful-luckys-tale.json
Found application baobab-studios-invasion-for-rift
Found application ccp-games-newcastle-eve-valkyrie
Found application colosseteam-colosse-a-story-in-virtual-reality
Found application epic-games-showdown
Found application oculus-dreamdeck
Found application oculus-farlands
Found application oculus-oculus-video
Found application playful-luckys-tale
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()
Launching application: ccp-games-newcastle-eve-valkyrie
Failed to launch application: revive.app.ccp-games-newcastle-eve-valkyrie ()

**Comment by LibreVR** [comment] 2016-06-28 13:40
```
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
qrc:/Oculus.js:17: TypeError: Cannot read property '1' of null
```

Still need to fix that error, but that does mean you are blocking the Oculus servers. What is the contents of the revive.vrmanifest?

**Comment by lanya0702** [comment] 2016-06-28 14:24
{
    "applications": [
        {
            "app_key": "revive.dashboard.overlay",
            "arguments": "",
            "binary_path_windows": "ReviveOverlay.exe",
            "image_path": "revive.png",
            "is_dashboard_overlay": true,
            "launch_type": "binary",
            "strings": {
                "en_us": {
                    "description": "Revive Dashboard overlay",
                    "name": "Revive Dashboard"
                }
            }
        }
    ]
}

**Comment by LibreVR** [comment] 2016-06-28 14:35
Ok, the problem is completely caused by the fact that you block the Oculus servers. I recommend against doing that, it will make Revive more difficult to use.

**Comment by lanya0702** [comment] 2016-06-28 14:45
But i dont know how did i block the oculus servers,how to find out?

**Comment by LibreVR** [comment] 2016-06-28 15:08
> I use shadowsocks to visit oculus.

Why do you use shadowsocks to connect to Oculus?

**Comment by lanya0702** [comment] 2016-06-28 15:11
Because my ISP block the oculus server

**Comment by LibreVR** [comment] 2016-06-28 15:38
Ok, well it will be fixed in the next release, if the Oculus servers are blocked Revive will just use a conical name. I'll release a new version this week.

**Comment by lanya0702** [comment] 2016-06-29 13:31
I reinstall the windows system,its work!

**Closed** 2016-06-29 13:54 UTC
