### ISSUE TITLE
Lucky's Tail "No Headset" issue again

### ISSUE THREAD

**Issue by KLWN** [LibreVR/Revive#22] opened 2016-04-20 20:07 UTC
Hi everybody,

after following the "how-to" for Installation, I finally started LT.exe the first time. But I received the mysterious message "No Headset" available.

Unknown Sources is checked and enabled, SteamVR is running in the bg and running as admin method, but none of it solved the problem. 

Kinda desperate after trying for almost 3h.

greetings,
alex

**Comment by vraddict** [comment] 2016-04-20 20:49
Have you rebooted your computer, I had the same and a reboot sorted it !!!

**Comment by KLWN** [comment] 2016-04-20 20:57
I rebooted a couple of times, but its not solving the problem, but thanks for the clue

**Comment by vraddict** [comment] 2016-04-20 21:05
did you copy over the patch to C:\Program Files\Oculus\Software\playful-luckys-tale ??
Also you need to have Oculus store running for the first run... And check that you have OVRServer_x64 running in task manager,,,, if not running go to C:\Program Files\Oculus\Support\oculus-runtime and double click OVRserver x64....... hope this helps

**Comment by KLWN** [comment] 2016-04-20 21:21
I copied it to C:\Program Files\Oculus\Software\playful-luckys-tale 
Store is also running and OVRServer_x64 too, doesnt work.

**Comment by vraddict** [comment] 2016-04-20 21:22
Make sure you replace OVRPlugin.dll and that both LibRevive64_1.dll and openvr_api.dll are present next to LT.exe.

**Comment by KLWN** [comment] 2016-04-20 21:26
they are perfectly fine, I already tried re-downloading, unzipping & pasting it again but its still showing me the "No Headset" message.

**Comment by KLWN** [comment] 2016-04-20 21:29
![unbenannt](https://cloud.githubusercontent.com/assets/14029001/14691110/af1c407e-074f-11e6-8a33-bff5640e664a.JPG)

**Comment by vraddict** [comment] 2016-04-20 21:39
We have covered everything, I had the same and a reboot got it running !!! one more thing you could try is to stop the server in task manager and restart it from C:\Program Files\Oculus\Support\oculus-runtime and double click OVRserver x64...... good luck let me know if you have any luck.... as from the picture you sent my folder is just the same,,, im running windows 10.1

**Comment by vraddict** [comment] 2016-04-20 21:43
you have prob tried this but did you restart VR ??

**Comment by KLWN** [comment] 2016-04-20 21:56
yes I have tried restaring manually, first problem was that after i stopped the process it restarted from its own like 3sec after. After some tries I got it working but I see some issues there...
![unbenannt](https://cloud.githubusercontent.com/assets/14029001/14691763/6f366490-0753-11e6-9761-992ff6fea27b.JPG)

**Comment by vraddict** [comment] 2016-04-20 22:08
It all good mine`s the same, think its a warning that the rift headset is missing,

**Comment by KLWN** [comment] 2016-04-20 22:09
I have not setup a device in the settings except for my 360 Controller, could this be the issue? It looks like the server recognizes the missing HMD.

**Comment by vraddict** [comment] 2016-04-20 22:36
mine i the same, and i am using a 360 controller... from what i have read it works for some and not for others..

**Comment by Evil-Streets** [comment] 2016-04-21 05:44
It's not working because you're using windows 7.

**Comment by KLWN** [comment] 2016-04-21 08:11
so I need to update to windows 10?

**Comment by Evil-Streets** [comment] 2016-04-21 08:20
Yeah or you wait until someone gets it working for win 7.

**Comment by LibreVR** [comment] 2016-04-21 13:32
Duplicate of issue #4

**Closed by LibreVR** 2016-04-21 13:32 UTC
