### ISSUE TITLE
Dirt Rally no longer works for me

### ISSUE THREAD

**Issue by slaata** [LibreVR/Revive#318] opened 2016-11-23 21:22 UTC
This may be a well known issue but I cant find it anywhere and I have searched . Since Dirt Rally changed to 1.23 I can no longer get it to work with my Vive. Has the update changed the revive compatibility?

I hope someone can help me with this.

Thanks

**Comment by LibreVR** [comment] 2016-11-23 23:24
Duplicate of #317.

**Closed by LibreVR** 2016-11-23 23:24 UTC
