### ISSUE TITLE
Odyssey+ The Climb: Issues found so far

### ISSUE THREAD

**Issue by LeonDres** [LibreVR/Revive#1116] opened 2018-11-27 20:57 UTC
Running ReVive 1.6.0 at the time of this post. 

So far only I've only had the height issue not appear once (think it was just a fluke). When starting up the climb I am met with being stuck about 5-6 feet off the ground. Lastly there seems to always be a jitter regardless of the settings. The least amount of jitter was at 1.2 upscale resolution in the game settings (changing the other settings seemed to make no difference). These issues persist in both windows 1803, windows 1809, steamvr, steamvr beta, windows mixed reality for steamvr, and windows mixed reality for steamvr beta. Supersampling at 0.8, 0.9, 1.0, and 1.2. Asyncronis/always reprojection on and off in OpenVR. Have yet to have these issues in any other ReVive games.

Also I've had two counts of starting the game and the vibration of the right controller would constantly run even after turning it off and on again. It kept vibrating until I closed out the game.

Specs: 
GPU: GTX 970 Driver Version 417.01
CPU: Intel i5-3570k
Ram: 16 GB

**Comment by Dragoboss** [comment] 2018-12-15 19:45
Some (jitter) issues are to be expected running with WMR on Revive.
Have you tried this with Remixed?

The height issue, could be that WMR and SteamVR might not be correctly communicating regarding your playspace.
Have you tried altering the play-space through OpenVR Advanced settings module? Also checking the ground in the Cliffhouse if that one is correct?

Please provide me with some more details where you can and/or steps to reproduce.

**Comment by LeonDres** [comment] 2018-12-16 02:40
Haven't tried it with remixed. 

I've tried messing with boundaries in steam's side, but both boundaries still read the floor at the same height (the boundary floor being 6ft above the games floor), and the floating only occurs when in the climb's client (going into cliffhouse or steamvr home puts me back to their respective height. No other oculus games that I've tested through revive has given me this issue. I start it via having the oculus client open, starting steamvr for wmr, then the revive option in steam's in game menu (and variations of the like). Not very much of a specific step for reproduction as it happens as you're first put into the game's starting menu and persists throughout.

**Comment by Dragoboss** [comment] 2018-12-16 10:04
I have head a couple of games spawn me in above floor before, amongst others with Dead and Buried, however those games have a 'reset position' function which then fixed it for me.
Does the Climb have such a feature?

The height issue already starts in the menu or is that displayed on the intended height?

**Comment by lurkin-heavy** [comment] 2018-12-23 00:47
I am having the same issues . I did how ever launch it in remixed and it ran beautifully except for the camera position was too close my hands take up the whole display.
 Anyone found a fix for this?. 
No matter what settings I run in steam vr its choppy and laggy, huge frame rate drop.
 I am assuming its a bug in revive with steam vr.  
I have the being too tall problem in the beginning, i can reposition myself with the track pad but it still wont fix the choppyness .
Not sure if im missing something but like i said it runs great in remixed.
 just gives me a head ache being so close to my players hands

**Comment by Armada651** [comment] 2019-06-06 00:48
Jitter issues have been fixed in the latest release: https://github.com/LibreVR/Revive/releases/tag/1.7.0

If you still encounter the other problems leave a comment here.

**Closed by Armada651** 2019-06-06 00:48 UTC
Labels: WMR on Revive
