### ISSUE TITLE
iRacing crashes on load

### ISSUE THREAD

**Issue by dtandersen** [LibreVR/Revive#141] opened 2016-06-07 19:45 UTC
iRacing just added Oculus CV1 support. Let me know if you need an iRacing account.

It should be noted that this game used "EasyAntiCheat".

```
The instruction at 0x00007FFE74DB3CE9 referenced memory at 0x0000000000000014. 
The memory could not be read. Click on OK to terminate the program.
```

https://www.reddit.com/r/iRacing/comments/4n05no/anyone_with_a_vive_got_revive_working_yet/

**Comment by LibreVR** [comment] 2016-06-08 00:32
I've seen these type of access violations before, except in those cases it was non-reproducible for me.

I hope I can consistently reproduce this one.

**Comment by yidhoe** [comment] 2016-06-09 17:30
Hey,

I just tested this myself, I used the Revive Steam DLL's and dropped them into iRacing folder, started iRacing and it detected I had a Rift and asked if I wanted to run the game full screen on there, I said yes then it crashed with the same error as above.

Wonder if it's their Anti-Cheat kicking in, maybe we need these DLL's white listed by iRacing themselves?!

If you need a tester let me know. :)

Thanks

Stuart.

**Comment by LibreVR** [comment] 2016-06-09 21:18
Well, I don't yet know whether the Anti-Cheat is causing the crash, but I do know it's making it much harder to debug it. The Anti-Cheat software is blocking attempts at attach a debugger and against dumping the memory. So I'll have to use some unorthodox methods to get a crash dump.

**Comment by trwoteb** [comment] 2016-06-09 21:36
thx for keeping on ... hope you`ll fix this ;)

**Comment by TOCA2FREAK** [comment] 2016-06-11 00:20
I don't know if this will be any help but in order to use OBS with iRacing they had a check box for the anti cheat otherwise it would not record the picture.

https://obsproject.com/

**Comment by LibreVR** [comment] 2016-06-11 11:41
No that doesn't help, OBS is just turning off features that trigger the anti-cheat. Anyway, since Revive injects into the application already I should have full control so I'll attempt to work around the anti-cheat that way.

It's pretty interesting that Revive doesn't trigger the anti-cheat, even though foreign code was injected into the application. I guess DLL injection remains difficult for anti-cheat software to deal with.

**Comment by TOCA2FREAK** [comment] 2016-06-11 18:11
Ok.  I do hope you can get this working with iRacing soon.  Thanks again. :D

**Comment by yidhoe** [comment] 2016-06-13 15:50
I've had a response from EasyAntiCheat and it doesn't sound promising... :(
=================================================================
Hi,

Most likely that injector won't work with EAC as EAC sandboxes the game and prevents injecting foreign code inside the game process. The game would need to add native support for VR.

--
Best regards,
EasyAntiCheat Team
==================================================================

So come on then iRacing....

**Comment by LibreVR** [comment] 2016-06-13 16:32
The code injection went fine, it's just that EAC prevents crash dumps from being generated so i can't debug the crash. I could work around that protection, but that costs too much time.

**Comment by aWakeParks** [comment] 2016-06-13 17:32
How does EAC prevent generating the crash dumps? Is there anything someone could do to present you with the information you need? Maybe someone at iRacing could "install" Revive on a Dev Client without EAC in place and send you the crash dump. Would this be something you could work with or is it too much hassle that way?

**Comment by LibreVR** [comment] 2016-06-13 21:06
That would work, I'd need to compile a debug version for them though.

**Comment by aWakeParks** [comment] 2016-06-13 21:18
I will ask if someone is willing to give it a shot and let you know if so.

**Comment by TOCA2FREAK** [comment] 2016-06-13 21:29
I do hope that someone from iRacing does help out. So want to play iRacing with the Vive. :)

**Comment by aWakeParks** [comment] 2016-06-13 21:48
I just wrote them an email regarding all of this, including a link to this github page. Let's see if it gets handed over to the right person and that he or she will give LibreVR a helping hand.

**Comment by TheHairyGun** [comment] 2016-06-19 08:00
I noticed TriDef has a special module for iRacing. I wonder if we could ascertain any details from this.

https://www.tridef.com/cart/product.php?productid=51&cat=2&page=1

**Comment by StephF1** [comment] 2016-06-22 18:27
Hello
Someone on the iracing forum has the vive working with iracing however it looks complicated and uses vorpx ,there must be an easier way 
here is the link : http://members.iracing.com/jforum/posts/list/125/3486300.page
Cheers

**Comment by LibreVR** [comment] 2016-06-25 19:47
Sorry guys, I won't be fixing this issue, it's too difficult to debug it right now.

**Comment by Acurus** [comment] 2016-06-25 19:53
Thanks for trying!

Hopefully they will implement Vive support fairly soon.

**Comment by TOCA2FREAK** [comment] 2016-06-25 19:58
Yeah thanks for trying.  Looks as if iRacing will be working on it at some point so we will just have to wait. :)

**Comment by martinw89** [comment] 2016-06-25 20:00
Thanks so much for your efforts LibreVR! This is an awesome project; not your fault that iRacing is a little more complicated because of EAC. Luckily, they just got a Vive in their studio a day or two ago.

**Comment by snakecult** [comment] 2016-06-27 01:37
I'm fine with closing the issue.

**Comment by JasonRivers** [comment] 2016-06-27 07:54
Thanks for looking in to this, iRacing have stated on their forums that they are looking in to the Vive and they have (at least one) Vive in-house. Fingers crossed it won't be too long before they're able to get the Vive to work with it!

**Comment by LibreVR** [comment] 2016-09-12 22:35
If I understood correctly iRacing now has official Vive support.

**Closed by LibreVR** 2016-09-12 22:35 UTC
Labels: help wanted
