### ISSUE TITLE
Revive can't detect games when installing Oculus Library in the root of a drive

### ISSUE THREAD

**Issue by gibsonlash** [LibreVR/Revive#402] opened 2016-12-20 17:57 UTC
first off let me say all the problems started when i tried to migrate all data for steamvr, vive, and oculus on to a separate hdd due to the fact the main one was ssd for the operating system. before this happened everything worked great, but i can not sustain all that data on that hdd without going over and bogging the system down.

where i am at now
1. refomatted both hdd and ssd
2. reinstalled o.s on ssd
3. reinstalled steamvr on hdd
4. reinstalled steam and vive on hdd.
5. reinstalled revive on hdd.
6. reinstalled oculus and games on hdd.

now my problem.

1. revive opens in vr with standard games showing in dash but unable to see anything other than what comes generically with oculus.
2. unable to see the unspoken, ripcoil, chronos, and luckys tail.

i understand some of the titles dont work but i would really apperciated if someone had a idea on how to get the unspoken to work again.

**Comment by LibreVR** [comment] 2016-12-20 18:40
Please post your logs from `%APPDATA%\Revive`, you can simply drag them in the comment box here after renaming the extension to `.txt`.

**Comment by gibsonlash** [comment] 2016-12-20 19:05
so these are the logs under \\user\tetsoma\appdata\roaming\revive

libpng warning: iCCP: known incorrect sRGB profile
Failed to add manifest file to OpenVR: D:\Revive\revive.vrmanifest (VRApplicationError_InvalidManifest)
Loaded manifest: D:\Revive\app.vrmanifest
Loaded manifest: D:\Revive\support.vrmanifest
Oculus Library found: D:\\

Launched injector with: "D:\Revive\Revive\ReviveInjector_x64.exe" /base "Support/oculus-touch-tutorial/TouchNUX/Binaries/Win64/TouchNUX-Win64-Shipping.exe" -gamemode=nux
Creating process: C:\Program Files\Oculus\\Support/oculus-touch-tutorial/TouchNUX/Binaries/Win64/TouchNUX-Win64-Shipping.exe -gamemode=nux 
Injecting DLL: D:\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0x2979f610
Injecting DLL: D:\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0x2979f610
Injected dlls successfully

**Comment by gibsonlash** [comment] 2016-12-20 19:38
is there a way to manually add the games to revive?

**Comment by LibreVR** [comment] 2016-12-20 19:57
> Oculus Library found: D:\

That's the problem, Revive doesn't currently support installing games directly into the root of a harddrive. Please make a subdirectory named something like `D:\Oculus` to fix it. I'll fix this in the next version.

**Comment by gibsonlash** [comment] 2016-12-20 20:07
well right now im creating a j link we will see what that does.

**Comment by LibreVR** [comment] 2016-12-20 20:09
That's not necessary though, I know for sure that the problem is that you installed your Oculus Library to the root of your drive.

**Comment by gibsonlash** [comment] 2016-12-20 20:16
ok so this is exactly what i did oculus is installed on C: and all the games are on D: . what should i do to fix this ive installed revive on either one with no results. if i try to move oculus to D: it wont boot even if a j link is in place.

**Comment by LibreVR** [comment] 2016-12-20 20:21
It doesn't matter where you install Revive, it will run from anywhere.

The important thing is to install Oculus correctly. Uninstall Oculus Home and reinstall it. When it asks you where you want to install your games library you Browse and create a subfolder on your D drive called "Oculus", then you select that folder and continue the installation.

**Comment by gibsonlash** [comment] 2016-12-20 20:31
1. uninstalled oculus home
2. reinstalled it
3. chose D:\Oculus for games
4. ran steamvr
5. still no The Unspoken 

any other ideas?

**Comment by gibsonlash** [comment] 2016-12-20 20:35
i dont understand how dreamdeck is showing up but not the other games.

**Comment by gibsonlash** [comment] 2016-12-20 20:41
i am trying something different. i will let you know the results.

**Comment by gibsonlash** [comment] 2016-12-20 20:44
ok not sure what i did different this time but everything is good to go. that whole sub folder thing is crazy it would be easier if you could edit or add the .exe file to what ever is launching the game for revive. but thanks for the help

**Comment by LibreVR** [comment] 2016-12-20 20:52
> that whole sub folder thing is crazy

That's because it's a bug, installing games in the root of the drive **should** work, but it doesn't yet.

**Comment by LibreVR** [comment] 2016-12-22 22:09
Fixed in 013cb95e83421c8c4d33f1ae2e99bfa902a01482.

**Closed by LibreVR** 2016-12-22 22:09 UTC
