### ISSUE TITLE
Medium Launches with a Fatal Error "Medium has crashed."

### ISSUE THREAD

**Issue by drspalumbo** [LibreVR/Revive#897] opened 2018-01-13 05:34 UTC
When I try and launch Medium, either in VR or from the Steam library window, it crashes immediately upon starting, and brings up a small dialogue box named "Fatal Error" reading "Medium has crashed."

Interestingly, the SteamVR status panel shows (beneath the "Ready"):
"SteamVR Home"
"Exiting Oculus Medium"
"Starting Oculus Medium"
"(unresponsive) Oculus Medium"
all in that order.

Uninstalled and reinstalled Revive and Medium. Other programs (Lone Echo, First Contact, Quill) working fine. I'm all up to date with the Revive.

**Comment by Armada651** [comment] 2018-01-13 09:29
Which headset are you using?

**Comment by drspalumbo** [comment] 2018-01-13 15:33
I’m using the Vive.

**Comment by Expicot** [comment] 2018-01-31 17:01
Same issue. Using a Vive as well. Too bad, I really needed to use Medium.

**Comment by Armada651** [comment] 2018-01-31 19:42
Are you sure you're running the latest version of Revive? I tested it yesterday and I couldn't reproduce it.

**Comment by Expicot** [comment] 2018-01-31 20:21
I uninstalled Medium, installed it again, reinstalled Revive.
The app starts to load, it does display the first frame (grey background+oculus logo) and "Fatal Error/Medium is crashed"

**Comment by Armada651** [comment] 2018-01-31 20:50
You could try it without the SteamVR beta. But I can't reproduce it even when I'm using the beta version.

**Comment by Prism777** [comment] 2018-02-01 01:31
Thanks for you help with all of this Armada651 --  I'm having similar issues. On my computer screen the app opens and displays a frozen shot of the Medium sky and stage, with the background audio playing. Nothing appears in the headset, and it doesn't display a fatal error or crash until I try to close the program on screen. 

I did notice that once I attempted to open Oculus, I couldn't access menus in Vive any more. I could still move around, but I had to close Vive from my computer.   

I currently have Version 1.2.1 installed, and I tried installing Beta Version 1.2.0, Second Beta Version 1.2.0 and Third Beta Version 1.2.0, reinstalling Medium for each, and it didn't load with any of them. I also reinstalled Oculus each time.

Any thoughts? I feel as if Medium is having trouble finding the controllers.

**Comment by Prism777** [comment] 2018-02-01 01:37
Also, I tried opening Medium with and without SteamVR Beta, with Revive Version 1.2.1 installed. I got the same results: nothing in headset, frozen Medium scene on screen, music playing in background.

**Comment by Armada651** [comment] 2018-02-01 10:16
I'm able to reproduce it now, seems like a really strange problem as it only happens when Revive is compiled in the Release configuration. If I use the Debug configuration of Revive it works fine.

That... shouldn't be happening.

**Comment by Armada651** [comment] 2018-02-01 10:22
Even better, it doesn't happen even in the Release configuration if a debugger is attached.

This is starting to look a lot like there's a race condition somewhere.

**Comment by Armada651** [comment] 2018-02-01 11:16
I can only reproduce it on the SteamVR beta, so it does look like it's a SteamVR beta issue.

@Prism777 Can you test again and make absolutely sure you still have the problem while **not** on the SteamVR beta?

**Comment by Prism777** [comment] 2018-02-01 16:26
Success! When I started to open it in Seam VR Beta, I noticed there was a Steam error pop-up saying "An error occurred updating SteamVR (app running)" -- so I decided to uninstall and reinstall Steam before moving forward. I also uninstalled/reinstalled the latest Revive Version 1.2.1. All of this did the trick,  Medium opened successfully while not in Steam VR Beta. 

Not sure if this was a factor, but previously I had everything installed on an external drive, so when I reinstalled them, I decided to install everything to the default C:\ and simply have their libraries saved on the external (example: I made my steam apps folder to D:\Steam Apps). Thanks again for your help with this Armada651! Let me know if I can provide any more info to help.

One more variable: I have Avast installed as virus protection, and I made sure to disable its protections for an hour while I installed everything again. I had done this in the past also, but I easily could have forgotten to do so during one of the installs several days ago when these issues started.

**Comment by Armada651** [comment] 2018-02-01 17:05
Sounds like it didn't properly switch off the SteamVR beta last time. Anyway, this confirms for me that it's a regression in the SteamVR beta, I'll try and contact Valve to see if we can fix it ahead of time.

**Comment by Prism777** [comment] 2018-02-01 18:22
Great, I'm glad you were able to home in on the problem. I did notice that after I started Medium, if I press the system button on a controller and try to access the the Steam, Desktop, Revive or Steam tab, I can select the individual tabs themselves, but can no longer select items inside them (for example, I can't select another Revive app to start running). I can still select things in the Settings tab though.  Thanks again Armada651!

**Comment by Expicot** [comment] 2018-02-01 23:12
I confirm the issue with SteamVR beta. I switched to standard build and Medium is working perfectly !

**Comment by Armada651** [comment] 2018-02-24 23:02
@cartoonmonkey It should be fixed in the most recent SteamVR beta.

**Comment by Armada651** [comment] 2018-02-24 23:03
Also, native support is in the works:

![medium](https://user-images.githubusercontent.com/2028870/36636081-470ccd94-19bf-11e8-8cea-7e0bcc754b68.png)

**Comment by cartoonmonkey** [comment] 2018-02-25 07:13
Ahhh  bloody amazing. Thank you!

**Comment by beldolor** [comment] 2018-02-28 01:45
Hi, I am getting this same error (fatal error medium has crashed). I've updated revive to the latest release as of today, and disabled the SteamVR Home Beta (is this the right one?) but still cannot get Medium to load. Am I missing a step? Thanks in advance.

**Comment by Armada651** [comment] 2018-03-21 05:55
The new release should fix the crash on startup once and for all: https://github.com/LibreVR/Revive/releases/tag/1.2.2

**Closed** 2019-06-06 00:55 UTC
