### ISSUE TITLE
I know win 10 minecraft does not fully work but...

### ISSUE THREAD

**Issue by 01beaker** [LibreVR/Revive#322] opened 2016-11-28 17:54 UTC
I know win 10 minecraft does not fully work but the wiki says that the game will load the background. I do not even get that far. I only get a "failed to get libOVR". Is there a way to fix this?

**Comment by 01beaker** [comment] 2016-11-28 17:59
The error was actually "failed to initialize libOVR"

**Comment by 01beaker** [comment] 2016-11-28 18:00
Everything works on other oculous games.

**Comment by Rojoyinc** [comment] 2016-11-28 18:01
Get VIVECRAFT it's free.

**Comment by 01beaker** [comment] 2016-11-28 18:08
I do have vivecraft I wanted on windows 10 to play with my mobile friends

**Comment by LibreVR** [comment] 2016-11-28 22:35
When people report it "loads to the background" what they're actually seeing is a 360 dome that the Oculus Store launcher shows before it starts Windows 10 Minecraft.

While I have a branch ready that allows Revive to inject into Windows Store apps (UWP), but OpenVR doesn't support UWP and developing a bridge requires significant effort.

Note that this doesn't just affect Revive, currently it's not possible to add OpenVR support to any Windows Store app. As soon as OpenVR adds UWP support I will finish the branch and add Minecraft support.

Keep an eye on this issue: https://github.com/ValveSoftware/openvr/issues/238

**Comment by LibreVR** [comment] 2016-11-28 22:36
Closed as duplicate of #230.

**Closed** 2016-11-28 22:36 UTC
