### ISSUE TITLE
Rock Band VR does not launch

### ISSUE THREAD

**Issue by jonnibravo** [LibreVR/Revive#1029] opened 2018-07-08 11:48 UTC
Since installing I cannot get this game to launch, it starts loading and after a few seconds it goes back to steam library.  The rock band process remains running in the background but using no CPU resource.

**Comment by Danktoast** [comment] 2018-07-10 21:59
I am having the exact same problem (had previously opened issue #1012).

**Comment by Armada651** [comment] 2018-07-18 08:45
Duplicate of #1012

**Comment by Armada651** [comment] 2018-07-18 08:46
Just return Rock Band VR and buy it again once the issue is fixed.

**Closed by Armada651** 2018-07-18 08:45 UTC
