### ISSUE TITLE
Lost, Henry and Mythos of the world axis not working "Video driver crashed and was reset! Make sure your video drivers are up to date. Exiting..."

### ISSUE THREAD

**Issue by koribian** [LibreVR/Revive#119] opened 2016-05-28 11:45 UTC
Dreamdeck, Farlands and Luckys Tale are working fine.
My video divers are up to date..
Any idea what could cause the problem?
GTX 970, i7-2600k, 16GB Ram

**Comment by LibreVR** [comment] 2016-05-28 11:48
I've never seen this error before, no idea what the problem could be. Looks like a driver crash, I'll keep an eye out for any DirectX errors that could cause that.

**Comment by Mad1723** [comment] 2016-05-30 21:49
Same problem here.

Every other game works, but Henry just crashes as soon as you start the story itself. The little introduction works, but not once you get into the rendering part.

i7-6700k, GTX970, 16GB RAM, Win 10 x64

**Comment by gonedns** [comment] 2016-05-30 21:53
Same here, Henry crash after fisrt intro... thx a lot for the EXCELLENCE work

i5 3570k, GTX 980ti, Win 7

**Comment by Arigator** [comment] 2016-05-31 16:09
I have the same problem with Henry and Lost (Invasion, Dreamdeck etc. works).
AMD Phenom II X4 965 Processor, 8 GB RAM, GTX 970, Windows 10
I recently updated my Nvidia graphics driver and Revive, unfortunately around the same time, so I don't know which caused this.  
Thanks for your hard work!

**Comment by patch24** [comment] 2016-06-04 01:43
This was just a problem for me too. On a titan x with latest drivers. Still haven't been able to see Henry or Lost.  Although Henry does get through the initial introduction with hand drawn plates...then...crash.

**Comment by wissper** [comment] 2016-06-04 18:04
I'm running a 980ti with Runtime 1.4 and geforce driver version 368.22.  I was able to get Lost to load in Vridge and play all the way through, though the colors were very Sepia tone heavy which from what I read is because I lack positional tracking.  None of the files are set to run as admin.  I'm using 0.6.0 release files. I did NOT load steamvr first - that may make a difference - instead I used the drag and drop loading method.  

I wonder if the reason Vridge is successful where an actual vive is not relates to the positional tracking difference between the 2 setups?

**Comment by LibreVR** [comment] 2016-06-04 18:28
No, the difference is likely due to the different OpenVR headset drivers.

**Comment by Brody79** [comment] 2016-06-09 12:10
I also have this problem, it worked in the past (using Revive 0.6 and older) but not anymore.
Downgrading the Oculus software to 1.3 and using old Revive versions didn't help for some reason.
I even tried older versions of Henry and Lost (I made backups of those from end of April) with the same effect. Very strange.

**Comment by Arigator** [comment] 2016-06-10 12:56
I can report that having connected more than one monitor is not the reason for the error also does not have to do anything with. I have a multi screen setup (PC monitor, TV, graphics tablet and the Vive) and just disconnected all displays except the PC monitor and the Vive, but 'Lost' and 'Henry' still crash with the same error. 

Thanks, LibreVR, for your thoughts on the matter and thank you, wissper, for the tip with 'Vridge'. I just googled it, but to my understanding 'Vridge' helps getting to display VR content on an Android device, but would not offer me an alternative possibility to display, for example, 'Lost' on my PC, right? 

LibreVR, could you give us some more advice how we could try to troubleshoot the problem (if you deem it possible at the moment)? For example, you mentioned DirectX above, dou you think it could be worth a shot to reinstall it or downgrade it, if possible? Or do you know if 'Lost' and 'Henry', ReVive or Oculus background processes produce log files which could be of use to pinpoint the problem? 
Thank you again for your awesome work!!

**Comment by LibreVR** [comment] 2016-06-10 14:01
> Thanks, LibreVR, for your thoughts on the matter and thank you, wissper, for the tip with 'Vridge'. I just googled it, but to my understanding 'Vridge' helps getting to display VR content on an Android device, but would not offer me an alternative possibility to display, for example, 'Lost' on my PC, right? 

Where did you see that 'tip'? I would never recommend anyone to use VRidge with Revive. I often ask people whether they are using that application so that I know their issue is not caused by Revive.

**Comment by DanielSnd** [comment] 2016-06-11 04:52
Got the exact same issue happening here :(

**Comment by Arigator** [comment] 2016-06-11 13:40
> Where did you see that 'tip'? I would never recommend anyone to use VRidge with Revive. 
Vridge was mentioned by wissper, but I mentioned you and him in the same sentence. Sorry for the misunderstanding.

**Comment by Brody79** [comment] 2016-06-14 21:02
I got Henry and Lost working again: you need Oculus runtime 1.3 and [this old RevivePatch](https://github.com/LibreVR/Revive/releases/download/0.5.2/RevivePCars.zip). Just copy the files from the patch into the folder with the ...-shipping.exe (...\Binaries\Win64) and you are set.

**Comment by LibreVR** [comment] 2016-06-15 00:49
Very interesting, then it may just be an issue with the DRM patch. Hopefully it will be fixed in future versions of Revive.

**Comment by noodle1009** [comment] 2016-06-15 04:36
I have to admit that I'm new to Oculus Home (and Revive as well), but I managed to get things working on my Vive with the patch Brody79 posted alone.  I've only got 1.4 - I don't think I have 1.3 (I don't have a 'swap' folder where it is located usually?).  I actually tried to find the 1.3 runtime after Brody made his post, and when I couldn't, figured 'what the hell, I'll just try it with the patch', and it worked just fine for me.

**Comment by LibreVR** [comment] 2016-06-15 12:46
@noodle1009 It works fine for most people, but there is a group of people who run into this issue.

**Comment by Arigator** [comment] 2016-06-15 20:26
> I got Henry and Lost working again: you need Oculus runtime 1.3 and this old RevivePatch. Just copy the files from the patch into the folder with the ...-shipping.exe (...\Binaries\Win64) and you are set.

Wow, I had the crash problem before but your method worked for me for both 'Henry' and 'Lost'! Like noodle1009, I could use it with the most current Oculus Home version 1.4. I copied LibreVr's ProjectCars RevivePatch files which you linked to both -shipping.exe folders and could start them without a problem from the ReVive Dashboard! 
Thanks a lot, Brody79, for posting this solution and thank you again, LibreVR, for creating ReVive and also for providing links to the older patch files which made it possible for Brody79 to find this solution!

**Comment by LibreVR** [comment] 2016-06-15 22:03
That doesn't make much sense, the ProjectCars patch will attempt to redundantly inject the Revive library, which the injector already did. It really shouldn't affect anything.

**Comment by Mad1723** [comment] 2016-06-15 22:03
I can confirm it indeed works.

**Comment by LibreVR** [comment] 2016-06-15 22:04
@Mad1723 Does it still work if you only use the `xinput1_3.dll` and not the Revive DLLs?

**Comment by Mad1723** [comment] 2016-06-15 22:05
Let me try this out, I'll report back in a few minutes.

**Comment by Mad1723** [comment] 2016-06-15 22:17
With the normal "installer" files, the game crashes. 

With just xinput1_3.dll , it doesn't launch.

With the PCars patch files all there, it launches and goes through the whole sequence without issues.

**Comment by noodle1009** [comment] 2016-06-15 22:18
I get the same result as Mad1723, fwiw.

**Comment by jespertheend** [comment] 2016-06-22 13:16
I was having the same issue. I still couldn't get it to work using the PCars patch. But I fixed it by adding both the files from the PCars patch as well as the regular files (ReviveInjector_x64 and then dragging Shipping.exe to ReviveInjector_x64)
Just using ReviveInjector causes a crash and a graphics driver error once the story starts. Using just the PCars patch causes an error right at the beginning saying "unable to find HMD"
but using both patches fixes it for me.

**Comment by LibreVR** [comment] 2016-06-22 13:22
If you want to use that solution you should just use the RevivePatch, it's the same as the ProjectCars patch but with an updated Revive library. If you use that one then there's also no need for the injector.

**Comment by jespertheend** [comment] 2016-06-23 18:45
Ah I see, I'll use that next time. Thanks!

**Comment by LibreVR** [comment] 2016-06-26 00:31
Can anyone re-test this issue with the latest version of Oculus Home and Revive?

**Comment by jespertheend** [comment] 2016-06-26 15:35
I tried running Henry using both the RevivePatch and the ReviveInjector and through the revive steamvr overlay but they all give me a crash once the actual story starts saying "Video driver crashed and was reset! Make sure your video drivers are up to date. Exiting..."

**Comment by LibreVR** [comment] 2016-06-26 15:53
It's difficult for me to pin this one down without being able to reproduce it.

**Comment by jespertheend** [comment] 2016-06-26 18:34
Yeah, I understand. Well at least the project cars patch is still working. Let me know if I can help

**Comment by LibreVR** [comment] 2016-06-26 19:20
I'll try running henry to a graphics debugger soon, I'll see if there are any warnings about API usage.

**Comment by MasterMNB** [comment] 2016-06-26 22:05
For me Mythos of the World Axis is crashing without a Message.
But Henry and Lost are working.

Revive 0.7 and 0.62
GTX 980 driver version 368.39
Oculus Version 1.5.0

**Comment by LibreVR** [comment] 2016-07-05 16:50
Hey guys, can you test out version 0.8.1? I've made a lot of bug fixes which may affect your issue.

**Comment by noodle1009** [comment] 2016-07-05 17:23
Henry and Lost now work without issue (for me)!

Mythos of the World Axis gives me a UE crash...
[logs.zip](https://github.com/LibreVR/Revive/files/348279/logs.zip)

not sure if that helps or not.  Thanks for your continued hard work on this!

**Comment by LibreVR** [comment] 2016-07-05 19:18
Great to hear! Looks like checking for API errors paid off, thanks for the feedback.

Mythos seems to be an unrelated issue, if you can submit a separate issue for then I'll mark to for the 0.9 milestone so it'll be fixed in the next version.

**Closed by LibreVR** 2016-07-05 19:18 UTC
Labels: help wanted
