### ISSUE TITLE
Oculus Video Tracking and image Reversed

### ISSUE THREAD

**Issue by jrheinfrank** [LibreVR/Revive#258] opened 2016-09-17 02:43 UTC
Can't seem to find anything on google or reddit with someone with a similar issue.
Reinstalled multiple times, and other apps/games track fine.

Anyone else having this issue?

**Comment by higate** [comment] 2016-09-17 09:25
Same issue here - Image and tracking is reversed (upside down)

**Comment by LibreVR** [comment] 2016-09-17 11:38
I can confirm the problem, it's a regression in the OpenGL support specifically in the case of Oculus Video which uses a deprecated part of the Runtime.

I'm not sure why I didn't notice it, but I'll release a hotfix soon/

**Comment by 04nd01** [comment] 2016-09-17 16:31
It also happens with Oculus 360 Photos

**Comment by LibreVR** [comment] 2016-09-19 13:26
Well, the inverted images was easy to deal with as it is just two minus signs I needed to correct for. However what is very strange is that the image for the right eye is used for both eyes in the headset.

This is specific to Oculus Video, as other OpenGL applications are not affected. What makes it even stranger is that the mirror window which Revive renders shows the correct image for the left/right eyes.

I think some of the OpenGL state from Oculus Video may be affecting OpenVR.

**Comment by LibreVR** [comment] 2016-09-19 13:39
Looks like it's a "Heisenbug", when I attach a graphics debugger it works fine. There's probably an invalid state somewhere that's causing this.

**Comment by LibreVR** [comment] 2016-09-24 00:05
Fixed in commit 4fd42f9910e3410fa1ccb8fcb0810932857ffddf.

I'll probably have a release ready around the end of the week.

**Closed by LibreVR** 2016-09-24 00:05 UTC
