### ISSUE TITLE
Headset picture drift/lag

### ISSUE THREAD

**Issue by saikoyama** [LibreVR/Revive#1126] opened 2018-12-04 05:10 UTC
I'm getting good framerate, but the picture drags behind about half a second. I'm using a Samsung Odyssey Mixed Reality headset. Also my first time using Revive.

**Comment by Goanna7007** [comment] 2018-12-04 06:59
I also have the same problem with the dell visor wmr.

**Comment by renatopmestre** [comment] 2018-12-05 14:05
> 
> 
> Strangely, setting AA to 4X in Echo Arena actually improves the tracking latency (although still noticeable), and reducing the resolution actually makes the tracking latency worse. Lower FPS = better latency? Confusing... I think it may be a reprojection issue.

Same issue here and same results. Using Oculus Go + ALVR + Revive + SteamVR. Games launched with Revive get a ?desync? in framerate? Its only a guess
When looking to the sides it feels like the the image is rendered, then a previous image is rendered (from the side you just looked at), then your actual image is rendered again.

Tried an option on ALVR called TrackingFrameOffset to -1 and it seems to reduce a bit, but it doesnt even make it enjoyable.

**Comment by Lucid360** [comment] 2018-12-07 13:38
+1 using Vive

GPU: AMD R9 Fury
GPU: 4690K

Latest version of Revive (tried two older ones with same results)
Tried the two latest versions of AMD graphics drivers, same results.

**Comment by cappaholic** [comment] 2018-12-07 13:45
Same issue on a Dell Visor WMR HMD while playing TribeXR. Just started I’m the last week or two.

**Comment by Lucid360** [comment] 2018-12-08 10:03
Hello Armada651.

I’m also using an AMD-GPU  which at the current time doesn’t support motion smoothing, so it’s off by default (and I can’t turn it on)

**Comment by Dragoboss** [comment] 2018-12-14 16:34
Actually motion smoothing still shows up in the settings @DawsSangio 
Also inside the Advanced Settings module.

https://cdn.discordapp.com/attachments/444340991177261057/523175162145800195/unknown.png
To illustrate. It can be found there.

For those that use WMR, please verify this once more with the latest version and give me some more details regarding your specs, os, etc. Anything that could affect this.

For those with Vive having this issue, please check motion smoothing settings and possibly post a separate report.
Also keep an eye on your CPU/GPU percentages see how hard they have to work in order to run your games, and check your graphic drivers.

**Comment by Armada651** [comment] 2018-12-15 17:07
If you're a WMR user and you notice lag only when running games like Wilson's Heart or The Unspoken, that is a known issue. There are certain games that can't run efficiently on SteamVR when using a WMR headset. Please use the experimental Remixed implementation by using the Revive Dashboard from the Start Menu without having SteamVR running.

**Comment by DawsSangio** [comment] 2018-12-17 18:49
> Actually motion smoothing still shows up in the settings @DawsSangio
> Also inside the Advanced Settings module.
> 
> https://cdn.discordapp.com/attachments/444340991177261057/523175162145800195/unknown.png
> To illustrate. It can be found there.
> 
> For those that use WMR, please verify this once more with the latest version and give me some more details regarding your specs, os, etc. Anything that could affect this.
> 
> For those with Vive having this issue, please check motion smoothing settings and possibly post a separate report.
> Also keep an eye on your CPU/GPU percentages see how hard they have to work in order to run your games, and check your graphic drivers.

When using WMR head set the motion smoothing option is not present:
![svr](https://user-images.githubusercontent.com/26057951/50108158-d95fcd00-0234-11e9-8a8d-196ae6cb0d3e.jpg)

**Comment by Dragoboss** [comment] 2018-12-17 18:52
It is not 'using WMR head set' because clearly, if you look at my screenshot, Dell Vidor is also a WMR headset... Sooo.
Old video driver indeed may be a cause of the setting not showing up.
Try updating with Gefore Xperience.

**Comment by DawsSangio** [comment] 2018-12-17 19:48
Now that is fun, updated to latest nvidia driver, still no option:
![svr](https://user-images.githubusercontent.com/26057951/50111394-fdbfa780-023c-11e9-8a33-48305735b902.jpg)
windows 1809, stable steam vr and WMR steam driver.

**Comment by cappaholic** [comment] 2018-12-17 19:49
UPDATE:

So, for sake of argument I did the following today:

1. Updated the NVidia Drivers via the GeForce Experience. Ran a "clean install" update. Driver date=12/12/2018
2. Uninstalled SteamVR and installed latest version (1.1.4)
3. Rebooted PC and ran SteamVR. Took screenshots to show the motion smoothing option is not 
available (see attached screenshot)
4. Tried opening TribeXR via ReVive within the SteamVR menu in the HMD. Will not open at all now.

As a work around I've been manually overwriting the SteamVR folder with a previous version. Honestly, I'm not 100% which version it is, besides build/bin 250820/version 1539100633.

![steamvr](https://user-images.githubusercontent.com/38006907/50111508-ed8ed480-020a-11e9-8b49-49e5cbda4117.JPG)

![steamvr - manual override](https://user-images.githubusercontent.com/38006907/50111516-f1225b80-020a-11e9-8a3d-3425ff3d17b1.JPG)

**Comment by Dragoboss** [comment] 2018-12-17 20:13
Strangely enough as of this point I have to agree.
Even though I did no updates, changes or anything the like since I took the other screenshot, motion smoothing has now disappeared from my menu as well... I will have to investigate this further....

**Comment by DawsSangio** [comment] 2018-12-18 09:18
Just want to note, that before SteamVR 1.1.3/1.1.4 all was perfect. The image drag is weird, look like the image is rendered with wrong aspect ratio.

**Comment by Dragoboss** [comment] 2018-12-18 10:47
Yeah. I am aware. SteamVR 1.1.3 was the one that introduced the motion smoothing, though, So that is for sure what you're seeing.
But the setting disappearing out of the Video tab is concerning, if it is still on but the setting gone...

As a work-around, do the following:
Navigate to C:\Program Files (x86)\Steam\config (or wherever your SteamVR is installed).
Open 'steamvr.vrsettings'.
Scroll down till the 'steamvr' section.
add a , behind the last entry in there, then new line:
"motionSmoothing" : false

That should at least force-disable it...
OR you can attempt starting SteamVR without the headset plugged in, however I feel as if as soon as you DO plug in the headset it might enable by default again...

**Comment by Lucid360** [comment] 2018-12-18 14:46
So, still same story on the Vive.

SteamVR literally tells me: “Motion Smoothing is currently unavailable on AMD hardware”

**Comment by Dragoboss** [comment] 2018-12-18 20:13
Well that's actually known and not a bug.
The question is if you also have the weird image drag/drift.

Remember people this tracker is about Revive not about steamvr.

So provide details about your case, if it's the same as the original post you can keep it in this ticket, if it looks / feels different post a new ticket. If it's not Revive related don't post it here...

**Comment by Lucid360** [comment] 2018-12-18 21:15
Not a bug, sure.

Still have the image drift/drag on the Vive though as soon as I use Revive. 

HTC Vive
GPU: R9 Fury
CPU: 4690K
Win10 - latest update 
SteamVR - Latest version

Played around with it some today. Tried the Blu: In the ”menu” where you can choose the three underwater experiences the drag was gone, as soon as i started one of the experiences it came back.  

Also tried Beat Saber. Lots of drag.

**Comment by elnarvideo** [comment] 2018-12-18 23:35
Lucid360, Dragoboss actually meant that AMD not supporting motion smoothing is not a bug. The lagging with latest SteamVR is a bug though.

Im getting same thing as everyone on Samsung Odyssey+ and on Lenovo Explorer. I was playing Robo Recall, Arktika 1 and many other Oculus games just fine before 1.1.3 and now they are all dragging heavily. Even Henry cant handle it. And Im also getting good FPS. All SteamVR and Viveport games run brilliantly.

MacBook Pro 2014 with 1060 6gb eGPU

**Comment by newOnahtaN** [comment] 2019-02-18 17:30
I am also experiencing this issue on my Odyssey Plus in Lone Echo. I've got a 1070 8gb, Ryzen 7 1700

I also do not have the motion smoothing option in Steam. Is there any resolution for this yet?

**Comment by Armada651** [comment] 2019-06-06 00:49
Lag issues have been fixed in the latest pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0

**Closed by Armada651** 2019-06-06 00:49 UTC
Labels: WMR on Revive

**Comment by mena99** [comment] 2019-08-05 00:03
hi , I've just bought Samsung OdySSey and i was excited about playing lots of games in vr 2 of them were fallout 4 and Defector .

all games that supports WMR works GREAT!
but Defector Glitches so badly , i tried to go through it but i couldn't hold it for more than 10 mins without feeling like throwing up .


i have : Dell Inspiron 15 7567 Laptop + Samsung Odyssey
NVIDIA GTX 1050ti
12GB rams 
SSD 256 (( the game is on the ssd ))
1 TB HDD ( windows is installed here )
 I7 processor  7700HQ  2.8 GHZ

any idea how to fix it ?

**Comment by Armada651** [comment] 2019-08-05 00:26
@mena99 Open a new issue, don't hijack an existing one.

**Comment by mena99** [comment] 2019-08-07 23:03
@Armada651 it's the same issue... 
anyway here is mine ...
#1287 
it has been 2 days with no views or replies ... i hope some experts can help me figure out why does this happen.

keep in ur mind , i've just played Zero Caliber VR today with Zero lags.

**Comment by Armada651** [comment] 2019-08-10 10:19
It is not the same issue, there are many ways in which drift/lag can occur and it will be different for each game.
