### ISSUE TITLE
Revive Dashboard is empty.

### ISSUE THREAD

**Issue by guzzlrr** [LibreVR/Revive#256] opened 2016-09-13 17:13 UTC
Hi, 

Firstly it escaped me that i could have tried the free apps first, so i bought Eve Valkyrie but as stated in the title nothing is showing in the dashboard.

the injector works but says something along the lines of this game needs to be launched via the launcher and nothing happens, i think the problem is its looking in the wrong place for the games/apps but I've no idea how to fix, or even if that's the issue.

[ReviveOverlay .txt](https://github.com/LibreVR/Revive/files/470377/ReviveOverlay.txt)

I've tried Restarts, reinstalling, uninstalling everything then re-installing, re downloading, making sure i have the up-to date version but the issue persists, I would just install it all to C to test to see if that works but i haven't got much space on that drive.

thanks for any help, you guys can provide : )

**Comment by LibreVR** [comment] 2016-09-13 22:50
This is a duplicate of issue #228, it is a known problem that will be fixed in the next version which should be out around the end of the week.

**Closed by LibreVR** 2016-09-13 22:50 UTC
