### ISSUE TITLE
Revive Dashboard Crashing at start

### ISSUE THREAD

**Issue by andregm3** [LibreVR/Revive#214] opened 2016-07-30 13:36 UTC
i Can't start Revive Dashboard, always crashing.

**Comment by LibreVR** [comment] 2016-07-30 19:13
Duplicate of issue #156.

Please post your log from `%APPDATA%\Revive` in that issue so we have more information about the crash. I will add crash reporting functionality in the next version so we can get to the bottom of this issue.

**Closed by LibreVR** 2016-07-30 19:13 UTC
