### ISSUE TITLE
unspoken frame rate 

### ISSUE THREAD

**Issue by zeq2mapper** [LibreVR/Revive#357] opened 2016-12-07 19:43 UTC
Is there anyway to get a better frame rate? 4790k i7 980ti 

Async repro is on the others are off. Even on lowest settings with ss completely disabled it get horrible ditters. Im updated to the latest nvidia drivers.  What do i do to get better frame rates and smoothing of it? Thanks plenty

**Comment by calibban** [comment] 2016-12-07 20:45
disable async help a lot for me

**Comment by LibreVR** [comment] 2016-12-07 21:37
Duplicate of #353.

**Closed by LibreVR** 2016-12-07 21:37 UTC
