### ISSUE TITLE
Subnautica pause menu bug when in game (Edited)

### ISSUE THREAD

**Issue by xLiquidBronze** [LibreVR/Revive#37] opened 2016-04-25 00:37 UTC
Myself and another user have experienced this: When hitting the start button (or esc) in game to get to the options, save game, etc... and then going back to game, all tracking from the right thumb stick will be lost from the Xbox controller (this is the stick that turns you left and right in Subnautica).

I also am not able to save a game, I do not get a message of "game is saved" like when just using my monitor. 

Not sure these will be able to be fixed, but thought I would throw the issues up here.

**Comment by Kaesemuffin** [comment] 2016-04-25 19:26
first of all "hi"
second :) Subnautica is still in alpha, so you should address this "save issue" at subacuaticas forum.

For the controller issue, are you working with the actual 0.4 version?
The Xbox 360 controller was fixed in 0.4 (yay big thx to Libre)
You got a Xbox One controller unit?

However I couldn't reproduce you controller bug.
Can you give any more examples which this issue apply?

**Comment by xLiquidBronze** [comment] 2016-04-25 20:06
Hi, thanks for the reply and all your efforts with revive, I and the community appreciates it:) 

The save issue is defiantly associated with using the revive injector, I can save normally when just loading the game up using my monitor and continue normally as well (not using steam VR or the headset etc).

2 users (myself included) have reported this same save/load behavior using revive, so it is not the game itself. Unfortunatly, I do not think the subacuatica forums would be able to help, since revive is a 3rd party tool making a rift only (at the moment) game work with the Vive.

And ya using a standard xbox 360 controller, I actually have 2 of them, tried both, same behavior: when hitting start or esc and just navigating the menu, then selecting something (options, save, etc) the right thumb stick will just stop working. This behavior is also reported by another user.

A few other things,
Both of us are using steam, both ahve steam installed in D: and using standard xbox 360 controllers along with revive.

Let me know if there is anything else I can provide, thanks, LB

**Comment by JesusTheAstronaut** [comment] 2016-05-13 22:31
Hello, xLiquidBronze.

I am in the same boat (heh) as you in regards to this trouble. I am not sure how much of this issue is specifically Vive/Revive related, vs just an overall problem Subnautica has with VR currently. I'd be interested to see if people using Oculus may be experiencing similar issues. 

One potential, though for some unappealing, workaround for the save issue you're having is to create a new game on "Hardcore" mode. I have found that by doing this, you get a new menu option "Save and Quit to Desktop", and for some reason actually works for saving the game. Personally, I think such an immersive game is well suited for playing in a Hardcore mode, but obviously there are a lot of drawbacks to doing this...

This doesn't directly resolve the other issue we share, with the menu screen ruining the tracking, however if you do play on Hardcore mode, then you hopefully won't need to open the menu until you're ready to quit the game.

Hope this helps until there is a better fix. If you discover any similar workarounds or end up elaborating on this trick, please share. Hopefully by utilizing the console and by being clever, we can work out a better solution until the devs at LibreVR or Subnautica change something that gives us better options...
Take care!

**Comment by xLiquidBronze** [comment] 2016-05-13 23:49
You sir are a gentleman and a scholar, setting it to hardcore allowed me to save/reload! I really just wanted to play around in the world, but I guess I will be playing hardcore at least to save progress :) 

So for the revive devs, that leaves numerous users who report lost tracking after hitting esc in game to bring up the options menu, etc... that is the only thing I see wrong with it at this point!

**Comment by JesusTheAstronaut** [comment] 2016-05-14 03:21
Yes, I also have the right-trigger bug when attempting to swap items between containers and personal inventory. I saw posts on the steam support page indicating this was happening after a recent update and is affecting anyone using VR, so this does not appear to be a problem unique to LibreVR..

I've seen possible workarounds involving 3rd party gamepad mappers such as xpadder; but heres what I do instead - I use a 360 controller to play 99% of the game, but when I need to manage inventory i power off my controller, which then forces the game over to keyboard + mouse, which uses right-click instead of right-trigger. After I'm done, I power my xbox controller back on and the game automatically switches back to gamepad control and I keep on playing hardcore mode I guess.

Glad to hear the tip for hardcore mode works for you and hope this other info is helpful as well. Take care!

**Comment by yohaskan** [comment] 2016-05-16 10:23
_using the console by typing "SURVIVAL" or "HARDCORE" while in game._
In VR mode, consol work but not visible. i think it's outside of the Headset view

**Comment by yohaskan** [comment] 2016-05-16 21:08
New test with 0.5 and still same problem
In fact, i have try without any controller for this case, and you can play with Keyboard &Mouse. But whatever you go to option mode, (Echap, F5 key, or controler button), The cursor headtracking stop to follow your head when you come back to the game.
And then, you can't save, and rotate the body of avatar

It's a bug with Revive and this game, because all players on Oculus don't have any

**Comment by Aoris** [comment] 2016-05-20 22:55
Any news for this bug?

**Comment by holyphyre** [comment] 2016-06-05 03:16
I'm having all of the mentioned issues: right thumb button on XBOX one controller not working, can't save game, lost headtracking once going to escape menu. Additionally, when i try to change the render distance on my vive, the game crashed, and i'm stuck stairing at my PDA super close up, which is making me cross eyed. Also, the health bar is slightly off screen. Using Vive .6, but this game looks FANTASTIC. I hope we can get these issues worked out, or that they make a vive version.

**Comment by caltheon** [comment] 2016-06-13 00:22
Yes, same issue, Saving just closes the menu and doesn't actually save, and once you've opened the pause menu once, head tracking (and mouse tracking) are disabled as well as the right thumbstick on the xbox360 controller.  Very frustrating as this game is beautiful to play on the Vive, the only one I use Revive for at the moment.  

Seems like it would be pretty trivial for them to add basic SteamVR support, I really wish they would and any time anyone asks they are ignored.

**Comment by TheJerit** [comment] 2016-06-24 21:55
Wanted to mention that this is still occurring with the latest Revive version, .6.2. If it's helpful to the dev, I can provide whatever info/data that they may need for further analysis on their end and perform any testing with the game.

**Comment by peaoo** [comment] 2016-06-26 18:17
Yep same issue here. "Saving" does not save the game and after going to the pause menu and resume to game the mouse seems disabled.

**Comment by LibreVR** [comment] 2016-06-26 19:31
I have no idea why Revive would affect game saving.

**Comment by caltheon** [comment] 2016-06-26 19:43
I don't think it effects the game-saving per-se.  If you switch to hardcore mode, the game still auto-saves properly.  One workaround to save is to switch to hardcore, let the game autosave on exit, then switch it back to regular (outside of Revive) and then load it again in Revive.

The problem seems to be with a hook on the menu/pause screen.  As soon as you enter it, half the input breaks.  The mouse look/head track stops working, if you are using a joystick the right joy-stick stops working.  Reeks to me of an input reference that gets left dangling after entering the menu (or being nulled out)

**Comment by caltheon** [comment] 2016-06-26 20:22
Just tried it out with the new .7 injectors and it appear to be working properly now!  Will give it some more testing soon after I finish some untimely Sunday job work

**Comment by TheJerit** [comment] 2016-06-26 21:01
Thanks for the feedback from everyone. That's very promising, Caltheon, going to download shortly and will report my results as well.

**Comment by TheJerit** [comment] 2016-06-26 21:14
Good news, I got the same results as Caltheon; the Save game and right joystick bug are no more with the latest .7 injector! Thanks again for the awesome work as usual, LibreVR!

**Comment by xLiquidBronze** [comment] 2016-06-26 21:15
I just tried .7 and same results, cant save in survival and lost tracking when hitting the menu...caltheon are you using the steam version, or?

**Comment by TheJerit** [comment] 2016-06-26 21:19
xLiquidBronze, I'm using the Steam version and the save I tested was from the Freedom version of Survival. It was an existing save I tested on though. I'll test on a completely new game save in a moment.

**Comment by caltheon** [comment] 2016-06-26 21:20
xLiquidBronze.  Yes, using the Steam Version, loaded an existing save I have from playing on the Desktop (recent changes included).  Oculus Home running in the background, though it is complaining about updating drivers or something.  I've never actually used Oculus Home for anything other than Revive though.

**Comment by yohaskan** [comment] 2016-06-27 01:03
caltheon, maybe the Fov command can help ?
FOV [#]
_Toggles player camera zoom (5-60), 60 is normal. Different types of lens framing such as flip, upside down, telescopic effect, etc., are found in the values of 5 to 500,000._

**Comment by Marflemerfmarf** [comment] 2016-06-27 02:35
I've started fresh on both Subnautica and the injector (.7), tried the same with patching for Steam. Dragged Subnautica executable over Revive Injector x64. Same thing happens, save from pause menu has no functionality, and crosshair/selector locks when I press pause menu still. In each of these instances I loaded from a previously saved game I started in desktop mode, AND tried a fresh start.
Just been playing Hardcore for now.

**Comment by caltheon** [comment] 2016-06-27 03:31
I should have added I am running in the "expiremental" build.  From Steam, go to properties, then the Betas tab and select expiremental - (no code required)

**Comment by peaoo** [comment] 2016-06-27 11:00
@caltheon 
Thanks that finally solved the problem for me! 
I guess the .7 injector and the experimental game version did the work.

**Comment by xLiquidBronze** [comment] 2016-06-27 16:14
@caltheon, yup downloading the beta version fixed the issue for me as well. I can save, move after getting out of the menu and swap items in your inventory to your locker and back, etc! 
Just as a FYI, I am using the "steam games" download, so I suppose that and the "standalone" download version are working if you are using the later. Thanks all again for the input and to LibreVR of course for making this possible!

**Comment by Marflemerfmarf** [comment] 2016-06-27 16:23
Yes! Switched to the beta and everything works nominally using the injector. Thank you guys so much for putting work in! This is such an impressive game to have working on the vive.

**Comment by TheJerit** [comment] 2016-06-29 14:31
Got unexpectedly tied up, but I did get to retest again on my end and it still worked. Using Experimental  build as well. That's several confirmations now, so looks like this one's resolved! And I agree, awesome game to play in VR; all thanks to Revive.

**Comment by LibreVR** [comment] 2016-06-29 14:45
Added this information to the compatibility list, thanks for the feedback.

**Closed by LibreVR** 2016-06-29 14:45 UTC
Labels: help wanted

**Comment by bboydastyck** [comment] 2016-07-01 01:39
I am having issues with my xbox 360 controller not working in the main menu/at all. I have tried using mouse and keyboard and no response with those too if there is supposed to be. Anyone have this issue? Followed all the above suggestions.

**Comment by leaky3** [comment] 2016-07-01 16:35
I am having the same issue as bboydastyck. Neither controller or mouse/keyboard are working so I can't go anywhere from the main menu. I can look at the menu to highlight options but have no way to select.

**Comment by BBK-PiJ-2014-85** [comment] 2016-07-01 18:53
I'm also having the same issue as bboydastyck and leaky3. This happens only in experimental mode, but non-experimental mode still has the menu and save bug at the top of this thread.

**Comment by caltheon** [comment] 2016-07-01 19:00
You do realize when you select start game from the main menu you then need to look to your right and select the game mode before proceeding, right?

**Comment by BBK-PiJ-2014-85** [comment] 2016-07-01 19:15
yeah, it worked fine in non experimental mode. When i click on any of the buttons in experimental mode, they do nothing, no click animation and even the quit button doesnt work.

**Comment by LibreVR** [comment] 2016-07-01 19:26
I'm not sure which of these problems are caused by Revive and which are caused by the stability of the game itself.

**Comment by BBK-PiJ-2014-85** [comment] 2016-07-01 19:32
I reckon its most likely the game, as it works in one mode but not the other. Hopefully once the experimental mode become non-exp this issue doesnt carry over.

**Comment by leaky3** [comment] 2016-07-01 20:38
I finally got controls working by launching the game outside VR and then enabling the controller. The in-game view is a little too close which is making it hard to see my stats on the lower left but everything else works well.

**Comment by BBK-PiJ-2014-85** [comment] 2016-07-01 22:02
tried leaky3's solution and it works. Cheers.

**Comment by bboydastyck** [comment] 2016-07-02 00:41
I dont seem to have a "Controller" tab in the options menu =(

**Comment by bboydastyck** [comment] 2016-07-02 01:23
And under keyboard tab there is no switch or anything regarding a controller option

**Comment by leaky3** [comment] 2016-07-02 15:54
Bboydastyck I am running experimental and had the controller plugged in when I launched outside VR to enable controller. Not sure if either of those things make a difference.

**Comment by sangretu** [comment] 2017-02-05 03:45
I have a full repro on the underlying issue with a completely different trigger (no VR involved); note that fixing the trigger will not solve the problem as it could happen again with a different trigger - needs to be resolved by making the underlying state impossible to reach.

Issue is: complete loss of a subset of controls; mouse movement, tab (inventory), esc (won't even bring up game menu), while other controls remain unaffected (keyboard movement, jump). Game breaking as there is no way to save & exit, alt-f4 and reload last save was the only option I found.

Trigger was: with view currently set to cyclops keel camera, hit F8 to report a bug (yes I was reporting a different bug when I discovered this) - in the feedback text area, start typing....as soon as you hit the letter "E" (yeah, the one that would normally make you step away from the helm), you'll notice that while the feedback UI remains, the keel camera view disappears and your character steps away from the helm. Once you leave the feedback screen, the game is left in the state described above.

Enjoy! And, uh....save first, eh?
