### ISSUE TITLE
"No Headset" error on LT

### ISSUE THREAD

**Issue by Stoppablemurph** [LibreVR/Revive#15] opened 2016-04-19 15:37 UTC
Can't get Lucky's Tale to work. Keeps starting with a "No Headset" detected error. Have tried restarting and launching with and without oculus home and with and without steamvr running.

**Comment by LibreVR** [comment] 2016-04-19 15:40
This often means you have not applied the patch correctly. Make sure you replace `OVRPlugin.dll` and that both `LibRevive64_1.dll` and openvr_api.dll are present next to `LT.exe`.

**Comment by LibreVR** [comment] 2016-04-19 15:41
Duplicate of #12.

**Closed by LibreVR** 2016-04-19 15:41 UTC
