### ISSUE TITLE
Eve Valkyrie Still Having Fatal Error after update?

### ISSUE THREAD

**Issue by newend** [LibreVR/Revive#312] opened 2016-11-20 18:51 UTC
My eve valkyrie is still showing fatal error when I try to launch from revive.  Anyone else still having issues?

**Comment by LibreVR** [comment] 2016-11-20 19:54
I'll look into it, but you really shouldn't be using Revive for EVE Valkyrie anymore. It has native support now and you should contact their customer support for a Steam Key.

**Comment by newend** [comment] 2016-11-20 23:08
They said that it is something they are looking into for the future. Has anyone got a key yet?

**Comment by LibreVR** [comment] 2016-11-21 00:16
That's too bad, I would've hoped that every publisher would give you access to both the Oculus and the SteamVR version. It would be a shame if we would get the same thing as consoles, where you have to buy everything twice.

**Comment by jconstant77** [comment] 2016-11-24 05:44
Yeah it's a bummer that they don't have the ability to issue those extra keys yet.  I'm also getting the fatal error.

**Comment by 994wemj** [comment] 2016-11-25 14:57
The issue is they do not want to give everyone steam keys that'll end up on being sold on 3rd party sites. I believe they are working on a method of adding the game directly to you library by linking your steam account - but no estimated delivery time unfortunately.

**Comment by LibreVR** [comment] 2016-11-27 20:58
Good news, I've fixed the bug, but I think you'll like the reason why the exists in the first place. The version of EVE Valkyrie on the Oculus Store has native OpenVR support!

Here's how to use it:

1. Go to your Oculus Software library and navigate to `Software\ccp-games-newcastle-eve-valkyrie\Image\WindowsNoEditor\VkGame\Binaries\Win64`
2. Right-click `EVE Valkyrie.exe` and click `Create Shortcut`.
3. Go to the properties of the newly created shortcut and add these arguments at the end of the Target field: ` -oculus -vr -tenant=live -windowed`.
4. Press OK and double-click the shortcut to start playing.

**Comment by 994wemj** [comment] 2016-11-27 21:19
Haha, brilliant. launching this way seems to suffer from potato graphics but I can play with my friends again which is what I needed!

Thanks @LibreVR, your continued efforts are very much appreciated!!

**Comment by jconstant77** [comment] 2016-11-28 18:04
Oh good, I'm not the only one looking those awful graphics.  It was significantly improved but not great with 1.5 supersample.  I'm planning to push up to 1.75 or maybe 2 tonight.

**Comment by danvic7** [comment] 2016-11-28 19:19
I don't think the potato graphics issue is about supersampling, but if he helps I might try it too. Right now it is really terrible. I wonder if a simple argument like those listed by @LibreVR could fix this.

**Comment by DowJohns** [comment] 2016-11-28 20:36
Hmm... every time I append the argument, it says it is invalid.  Am I missing something?

And thanks again @LibreVR for the hard work!

**Comment by danvic7** [comment] 2016-11-28 21:11
I just kept the path to Eve Valkyrie.exe between quotes, added a space after the closing quote and pasted the arguments. But be ready for the extremely low resolution graphs...

**Comment by jconstant77** [comment] 2016-11-28 22:54
@DowJohns  , yeah you just have to put the options after the last " in the path to the executable.

@danvic7 I think it's definitely a resolution thing.  I couldn't read any text on the options screens when I booted it up the first time.  Once I upped the supersampling to 1.5 I could at least read the bigger text.

**Comment by LibreVR** [comment] 2016-12-02 13:52
Seems like a lot of people are running into resolution problems, so if you want to switch back to the Oculus support using Revive, try this development version of the injector: [ReviveInjector.zip](https://github.com/LibreVR/Revive/files/627272/ReviveInjector.zip)

If you installed Revive in the default location you can extract the injector to `C:\Program Files\Revive\Revive` to use it for the dashboard.

**Comment by danvic7** [comment] 2016-12-02 15:52
Thanks again @LibreVR for the great work. It is working perfectly with the development version of the injector.

**Comment by DowJohns** [comment] 2016-12-02 17:21
Works beautifully - and no image stuttering.  Thanks @LibreVR!

**Closed** 2016-12-05 16:37 UTC
