### ISSUE TITLE
Real VR Fishing - Can't Cast (PSVR2)

### ISSUE THREAD

**Issue by Guffaluff** [LibreVR/Revive#1866] opened 2024-09-05 01:36 UTC
Exactly the same problem as described in this old report: https://github.com/LibreVR/Revive/issues/1671

So I will copy/paste it here below, with adjusted info based on my versions.
-----
**Describe the bug**
You can't cast out. The trigger works, but when you do the motion to cast, It doesn't cast. You can sometimes get it to cast by spamming the trigger, although this is very inconsistent and doesn't cast very far. I've tried different bindings presets using my PSVR2 controllers.

**To Reproduce**

Start Real VR Fishing with revive
Open any map
Try to cast

**Expected behavior**
My line gets casted out normally and works consistently

**Environment (please complete the following information):**

App: Real VR Fishing
OS: Windows 11
Headset: PSVR2 with PSVR2 Sense Controllers

**Versions (please complete the following information):**

Revive: Can't find version number, is fresh install September 5th '24
SteamVR: Build ID 15141130

**Comment by CrossVR** [comment] 2024-09-05 10:55
Duplicate of #1671

**Closed as completed by CrossVR** 2024-09-05 10:55 UTC
Labels: revive
