### ISSUE TITLE
Dirt Rally Executable has stopped working

### ISSUE THREAD

**Issue by Skalledalle** [LibreVR/Revive#630] opened 2017-06-07 22:22 UTC
Hello.

I have the HTC vive, and wanted to setup the Dirt Rally to play with Vive. 

Ive followed the newest guide, wich says to patch the dr.exe (from the revive in hidden icons), but i get an error i cant find anyone else tried.

Imidiatly after opening the Dirt rally (while SteamVR is on), i get the Dirt logo, and then it stops loading. When i tab out, theres and error box saying "Dirt Rally Executable has stopped working" and i can only "Close".

Ive tried to download the newest DirectX, and im running Windows 7. Everything is updated, and ive even tried to reinstall Dirt Rally to see if it was it.

I have no problems what so ever running any other games in Steam and even SteamVR.

I cant seem to find anywhere to take out the errorlog, but can anyone relate to this problem and help? :)

Thanks in advance!

**Comment by Skalledalle** [comment] 2017-06-07 22:24
As if now i notice, others are having same problems in https://github.com/LibreVR/Revive/issues/627 

But this might be the "big topic" on the executable, as the other topic is arround another issue.

**Comment by hyperseven** [comment] 2017-06-07 22:26
did ou install the latest revive with hotfix as it says?

**Comment by Skalledalle** [comment] 2017-06-07 22:36
Hi Hyperseven! 

I just noticed Armada made a hotfix for this, ive been working last days so its a couple of days since i "gave up" on this. 

So it works now!! Im so happy! 

Just downloaded the last revive and now it works. I even dont have the oculus installed, its amazing :o

**Comment by Armada651** [comment] 2017-06-08 01:16
Closed as duplicate of #637.

**Closed by Armada651** 2017-06-08 01:16 UTC
Labels: duplicate
