### ISSUE TITLE
DG2 Freezes

### ISSUE THREAD

**Issue by oosilentcoon** [LibreVR/Revive#25] opened 2016-04-21 06:59 UTC
Defense Grid starts up fine.  But after a seemingly random amount of playtime, which is always less than 10 minutes, the game stops.  In my headset, all I see is the default steam view that you see when you start steamvr, and on my computer monitor I see the game frozen. This also occurs if I hit the start button on my xbone controller.

**Comment by LibreVR** [comment] 2016-04-21 20:48
This is probably caused by the patched executable, I made some new commits that allow ReviveInjector to inject into Defense Grid 2. So this will probably be fixed in the next release.

**Comment by LibreVR** [comment] 2016-04-23 11:31
The ReviveInjector can now inject into Defense Grid 2 and that seems to have fixed the issue. The new injector will bepart of the 0.4 release.

**Comment by LibreVR** [comment] 2016-04-24 12:46
I can still reproduce it with internal builds of 0.4. I'm not sure I'll be able to solve it before the release.

**Comment by oosilentcoon** [comment] 2016-05-16 02:22
Haven't had this issue so far in 0.5!

**Comment by Brody79** [comment] 2017-04-27 09:34
I have played this game for many hours without any crash. I guess it's save to say that this issue doesn't exist anymore.

**Comment by Armada651** [comment] 2017-04-27 09:43
Thanks for the report.

**Closed** 2017-04-27 09:42 UTC
