### ISSUE TITLE
Camera / UE

### ISSUE THREAD

**Issue by tracrium** [LibreVR/Revive#43] opened 2016-04-25 11:59 UTC
In all the Unreal Engine apps/games/demos (Airborne 1944, 9/11 Experience, SnowCoaster, Boursin Sensorium, Halloween Coaster, NewRetroArcarde, Rexodus, The Caretaker, ...), the camera is too high. It's like I was a giant and for some games it's very buggy, unusable.
Recenter camera in the game or in the settings of SteamVR doesn't change anything.
No problem with Unity games.

Thanks in advance.

**Comment by LibreVR** [comment] 2016-04-25 12:09
Duplicate of issue #18.

**Closed** 2016-04-25 12:09 UTC
