### ISSUE TITLE
Dragon Front Not working

### ISSUE THREAD

**Issue by euandrei** [LibreVR/Revive#323] opened 2016-11-30 12:34 UTC
I have installed first oculus ( oculus software in C:/progra files.. , then downloaded the games in separate directory.. ). Installed Revive, The tab appears the game is there but when I click nothing happens. I went on to try with the Standalone solution, for a second the gamescreen appears, stays 1 second ( black screen ) and the vanishes. The game is called Dragon Front.

What should I do now. Is there any chance that I miss any library being installed from my machine ?

UPDATE:

While I kept trying ( installed other apps that worked ). I wanted to try this one again and this time i got a pop-up saying: " A connection the the Oculus Store could not be established. Please check your internet connection and firewall and make sure that you are logged into your Oculus Store account. " 

I checked my firewall and is not enabled at all.  

UDATE 2:

I actually noticed that no game works at all. The movie experiences do but no games open or start from oculus. Is there any chance for me to have an updated version of Oculus software so that they patched it ?

**Comment by LibreVR** [comment] 2016-12-02 21:10
Closed as duplicate of issue #326

**Closed by LibreVR** 2016-12-02 21:10 UTC
