### ISSUE TITLE
The Unspoken Stuttering/Lag

### ISSUE THREAD

**Issue by 1Revenger1** [LibreVR/Revive#512] opened 2017-02-22 20:45 UTC
Not sure if this should go into the other issue or not, I just made a new one to be safe.
I got The Unspoken recently, and even with the latest version of Revive (1.0.5) I am getting missed frames. This does not change with any graphic settings within the game (whether it is low to high) although I do get less missing frames at the lower settings. Attached is a screenshot(the second is because I accidentally covered up part of the first) of what the performance looked like. Super sampling is at 1.0(default)

I have also noticed that if I restart the game or SteamVR multiple times, the problem gets worse very quickly, to the point where even with low settings it's a slide show basically. I don't think that has to do with Revive though as it effects the main menu room thing as well.

System:
I5 6600k @ 4.5GHz (issue occurs at stock speeds as well)
8GB 2133 DDR4
2 GTX 970s
![screenshot_5](https://cloud.githubusercontent.com/assets/13190749/23231477/d7546cc0-f8fc-11e6-9c5d-3aa9220a8c41.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/13190749/23231486/dc6f4982-f8fc-11e6-81aa-c62d80744a00.png)

**Comment by Armada651** [comment] 2017-02-22 21:12
Unfortunately both The Climb and The Unspoken are CPU bottle-necked and rely heavily on tracking prediction which Revive doesn't support yet. It will probably require an update in OpenVR before it can be fixed.

**Comment by Strongpillow** [comment] 2017-02-22 21:16
That's unfortunate. Unspoken was the main reason for setting up Revive but Super Hot was fantastic so thanks for that and keep up the amazing work!

**Comment by Armada651** [comment] 2017-02-22 21:17
It'll be fixed eventually, but it may take a while though.

**Comment by 1Revenger1** [comment] 2017-02-22 21:26
Oh that's to bad, it's a great game as well. Thanks for trying at least and doing what you can.

**Comment by Armada651** [comment] 2017-02-22 21:28
One workaround you can try is going to your SteamVR settings, go to the developer page and enable "Always on reprojection". That should reduce the CPU bottleneck, but increase tracking latency.

Remember to turn it off again when you're done playing The Unspoken.

**Comment by Chupacabra1989** [comment] 2017-02-23 07:43
yes this works much better now. hope in future this will be fixed unspoken is really a main reason for vr :D but thanks for the workaround awesome job.

**Comment by Chupacabra1989** [comment] 2017-02-23 07:47
ah im such a troll havent seen the new release (-.-) i try this today and give feedback thanks for the fast release :)

**Comment by mikegomak** [comment] 2017-02-23 14:06
A couple of quick questions as I'm having the same issues with an almost identical spec machine. How do I change the supersampling, and if I increase my RAM from 8GB to 16GB should I see a notable performance improvement? Just FYI I did need to turn off all AntiVirus software to get a descent improvement previously.

**Comment by Chupacabra1989** [comment] 2017-02-23 15:43
@mikegomak 

hey bro just install openVR then u can change the supersampling when u are in menue of the vive headset. im not shure but this can not be bad if you upgrade your hardware setup.  i give later feedback i also upgraded cpu and gpu i try it with the latest fix.

**Comment by Chupacabra1989** [comment] 2017-02-24 11:09
ok i tested it and the performance is much better now it is playable but not perfect. thank u for the update :) btw i disabled supersampling in openvr (set back to 1.0) and enabled in unspoken options ingame high grafics. ( hamburger button on vive controller). also disabled reprojection it works really much better now. hope this help someone and sorry for my bad english lol.

**Comment by catbert7** [comment] 2017-02-26 18:29
Unfortunately, I have not been able to achieve any improvements with any of the solutions proposed here :( I was waiting to buy the Unspoken until this release so that the issue would be fixed; woops :p Unspoken was really the game that convinced me to buy VR so it's definitely sad that the wait will be longer. Not blaming though, I really appreciate that anyone has put so much charitable work into making any of these games available to the Vive community. Thanks for all your efforts!

**Comment by mikegomak** [comment] 2017-02-26 22:50
Thanks all for your feedback and help. Although it's not dropping frames anymore the lag still leaves it unplayable for me as whilst I don't get vomit sick right away I do immediately suffer from some dizziness and discomfort that I can't become accustomed to. I'll keep an eye on this and am sure it will be 100% soon. Thanks for your work on this so far - you still rock!

**Comment by SimplexPL** [comment] 2017-02-28 11:52
> both The Climb and The Unspoken are CPU bottle-necked and rely heavily on tracking prediction which Revive doesn't support yet.

@Armada651 
Would  a fast CPU mitigate the issue? (like i7 6700K overclocked to 4.5GHz)

**Comment by Armada651** [comment] 2017-02-28 12:37
@SimplexPL It would probably help a bit, but I don't think it would mitigate this issue. What we need is a change in OpenVR that allows it to work with the larger tracking prediction.

**Comment by SimplexPL** [comment] 2017-02-28 13:00
@Armada651 Thanks for clarification. I hope Valve is aware of this issue and they will update OpenVR accordingly.

**Comment by mikegomak** [comment] 2017-02-28 13:34
This is interesting. I have quite a large play space. Could reconfiguring the play area and setting up as "Standing only" help with the tracking issue in that case?

**Comment by Armada651** [comment] 2017-02-28 13:37
@mikegomak Your room setup has nothing to do with it. The problem is that The Unspoken requests 2 frames of tracking prediction whereas OpenVR was only ever designed around 1 frame of prediction.

**Comment by mikegomak** [comment] 2017-02-28 14:25
Thanks for clarifying for me as a non techie.

**Comment by Werbel** [comment] 2017-02-28 14:38
I'm having horribly bad lagg issues most of the time after last update. Tracking is a little better but frame drops are insane.

Today Unspoken will get new patch and i will test it after that providing logs etc.

**Comment by Chupacabra1989** [comment] 2017-03-01 20:06
is there any possibility to send this information to valve support? im not sure if nobody gives that as a report that they will take care of this problem.

**Comment by Chupacabra1989** [comment] 2017-03-01 20:07
@SimplexPL i got this cpu with this 4,5 ghz overclocked it works a bit better but still this issue u can try it yourself if you got also this cpu

**Comment by Armada651** [comment] 2017-03-17 22:18
Here's a small update on this problem that I gave on Reddit:

> I was just working on The Unspoken today and I've figured out a lot more about that problem. One of the things I discovered is that these games are actually not applying a full 2 frames of prediction, it just looks that way on the side of Revive.
>
> Revive expects games to request new tracking data after submitting the last rendered frame. However The Unspoken seems to request new tracking before submitting the latest frame.
>
> On the Revive side this look like the game is predicting 2 frames ahead, while it's actually just requesting the tracking data for the next frame a little bit early.
>
> However this presents a bit of a problem, because this assumption in Revive is rooted in the fact that OpenVR ties frame submission and tracking data together. I will try and use some more obscure features in OpenVR to hopefully separate these two concepts.

**Comment by mikegomak** [comment] 2017-03-17 22:50
Thanks for looking even more into this, and for keeping the community updated. Intriguing.

**Comment by 1Revenger1** [comment] 2017-04-13 22:32
Is there any update on this? I appreciate that you are working on this :D.

**Comment by Armada651** [comment] 2017-04-13 23:13
@1Revenger1 I'm working on a new version that takes a different approach to tracking prediction. We'll see how it works out.

However in any case The Unspoken will be incompatible with asynchronous reprojection, so you will need to turn that off while playing The Unspoken.

**Comment by 1Revenger1** [comment] 2017-04-14 02:34
Sounds awesome, hopefully it works out well.

**Comment by Chupacabra1989** [comment] 2017-04-14 07:32
@Armada651 thank u so much im waiting so long for this news :D

**Comment by mikegomak** [comment] 2017-04-14 08:36
@Armada651 - I usually try it with Asynchronous reprojection on as its the smoothest way to play it... Are you saying I should turn this off? strangely, the most juddering/lag is actually in the room, not when playing. I have also noticed a new setting on the Nvidea menu, attached, will modifying this help maybe? Thx again for all your work on this - from what I can see its an incredible game and somehow worth the effort.
![nvidea settings](https://cloud.githubusercontent.com/assets/19430087/25038274/d4cf03b8-20f5-11e7-993c-d6855be8b6ca.PNG)

**Comment by Armada651** [comment] 2017-04-15 19:03
Please test the latest release: https://github.com/LibreVR/Revive/releases/tag/1.1

You may experience some stuttering due to the amount of prediction The Unspoken is using. If you are experiencing stuttering, try different configurations of reprojection. Try enabling/disabling Asynchronous Reprojection or enabling Always-on Reprojection.

**Comment by 1Revenger1** [comment] 2017-04-16 00:16
In like the 10-15 minutes I had to try this out, I found that with no reprojection, it was a lot of stutter and not really playable. Always-on Reprojection I found helped the most, although there was still a lot of stutter, and I noticed my view kind of rubber-banding a little bit at times. The other 2 modes of reprojection, even if they were all applied, didn't do much from what I found.
![screenshot_1](https://cloud.githubusercontent.com/assets/13190749/25067658/2d313c2e-21ff-11e7-958c-63623871eb7b.png)
This screenshot is shown with Interleaved reprojection and Always-on Reprojection on low settings within the Home at the entrance.

**Comment by Armada651** [comment] 2017-04-16 12:18
Moving this issue ahead to the next milestone to look for more opportunities for performance improvements.

Don't get your hopes up though, improving the performance without a deeper understanding of the game engine is very difficult.

**Comment by mikegomak** [comment] 2017-04-16 12:44
Thanks again for all the effort being put into this - I wanted to check asap and get back to you. I am not really noticing any differences regardless of settings, although the most recent driver update from Nvidea definitely improved things - previously I could only play the game a short while before nausea struck - I have either acclimatised to it - or framerates have gone up. (I don't get missed frames reports coming up at all). I have also noticed that I get less stuttering when I turn off some background tasks like virus scanner CC cleaner and Quicktime console. I'm thinking in that case upgrading the RAM to 16G would help - would you agree? Thanks again.

**Comment by Armada651** [comment] 2017-04-16 12:49
That wouldn't help anything, the reason that works is probably because you're freeing up resources like CPU time and SSD/HDD access.

**Comment by Chupacabra1989** [comment] 2017-07-10 07:20
hi guys. is there still a chance to get this game running fine ? still unplayable for me this stuttering lags are awful. tried all options in reprojection. btw thanks for the work

**Comment by Armada651** [comment] 2017-07-27 18:08
Fixed in the latest release: https://github.com/LibreVR/Revive/releases/tag/1.1.12

**Closed by Armada651** 2017-07-27 18:08 UTC

**Comment by Nordomus** [comment] 2017-07-28 19:41
How is it fixed? It still judders, unless it's different problem.

**Comment by mikegomak** [comment] 2017-07-28 20:19
I noticed the same and have tried various on/off settings in the developer options especially asynchronous repro and always on repro. Initially I thought that I did not install the new version properly. If it helps, the issue is most prevalent in startup and in the "home" it's about 50% better in games and tournaments but I honestly have not noticed an improvement since the last version.

**Comment by Nordomus** [comment] 2017-07-28 20:20
Yep, exactly my point, it is playable but anoying.

**Comment by Armada651** [comment] 2017-07-28 23:40
Asynchronous Reprojection is only supported on compatible GPUs, so what GPUs do you have?

**Comment by SimplexPL** [comment] 2017-07-29 00:47
Nordomus is my friend, I know he has 1070.

**Comment by mikegomak** [comment] 2017-07-29 07:28
Hi, I'm running Nvidea GTX 1060

**Comment by mikegomak** [comment] 2017-07-29 07:31
Could it be related to a specific graphic card setting? I have noticed some new controls for 3D and I have also noticed an improvement in all games when I have selected the "performance over power consumption" option. Happy to send screenshots if that may help.

**Comment by Nordomus** [comment] 2017-07-29 07:49
I have always used "prefer maximum performance" setting since some games ran terrible without it.

**Comment by SandmaN666** [comment] 2017-08-20 15:03
Still no update to fix the stuttering?  No setting that can fix this at all?

**Comment by Armada651** [comment] 2017-08-20 16:18
@SandmaN666 Are you running the SteamVR beta? Do you have asynchronous reprojection enabled?

**Comment by mikegomak** [comment] 2017-08-20 17:05
I can confirm I am running steamVR beta, have tested with AR enabled and still have the same level of juddering. I have tried all combinations of adjusted settings with no effect. The juddering is very bad in the apartment but I think it does improve a little in game - although I might be distracted by the action and not have a 100% reliable opinion on that.

**Comment by Armada651** [comment] 2017-08-20 20:32
@mikegomak What is your GPU?

**Comment by mikegomak** [comment] 2017-08-20 22:31
Nvidea 1060, i5 processor. HP Omen build.

**Comment by Werbel** [comment] 2017-08-21 15:29
I dont have this problem anymore with latest update and SteamVR Beta. I had huge stuttering in apartment + tracking lagg but both has gone. i7 4770 & 1070

**Comment by mikegomak** [comment] 2017-08-21 16:23
Here's the full spec https://support.hp.com/in-en/product/omen-by-hp-870-100-desktop-pc-series/12079703/document/c05321116/
Interestingly when I increase the settings it looks better obviously but the judder only gets marginally worse and I still don't get missed frames errors displayed.
@Werbel have you made any changes to your graphics card settings in its controls other than power management "prefer performance over power"?

**Comment by Armada651** [comment] 2017-08-21 16:25
@mikegomak This is likely due to translation overhead, especially since someone with an i7 does not have the problem. The next version will get a lot of optimizations, so let's get back to this once that version is released.

**Comment by Werbel** [comment] 2017-08-21 17:14
> @Werbel have you made any changes to your graphics card settings in its controls other than power management "prefer performance over power"?

Nope. But i had terrible performance all through few last versions, stuttering was the least important as it happened only in the apartment. And it's all gone now! I can even run a game on max setting with some SS up. AR works like a charm.

**Comment by davidskis** [comment] 2020-06-02 06:03
Seems to be occurring again - I have bad judder in the house. Reprojection, supersampling don't seem to have any effect. Appreciate any help!
