### ISSUE TITLE
I get this error every time I try to load the Revive Dashboard in Win10 using Riftcat / Vridge

### ISSUE THREAD

**Issue by wissper** [LibreVR/Revive#97] opened 2016-05-19 14:25 UTC
This comes up immediately upon running Revive Dashboard, but the option does show up in settings for SteamVR so it's registering its presence somewhere.

Faulting application name: ReviveOverlay.exe, version: 0.0.0.0, time stamp: 0x573ca6bd
Faulting module name: ReviveOverlay.exe, version: 0.0.0.0, time stamp: 0x573ca6bd
Exception code: 0xc0000005
Fault offset: 0x0000000000003b2a
Faulting process id: 0x2e14
Faulting application start time: 0x01d1b1d84b5a1bcd
Faulting application path: C:\Program Files\Revive\ReviveOverlay.exe
Faulting module path: C:\Program Files\Revive\ReviveOverlay.exe
Report Id: df0c654d-c459-4e99-b415-7667abb23085
Faulting package full name: 

Sometimes it errors on Qt5gui.dll - but it's generally a similar type of error, then immediately followed by an OVRService Launcher error saying that it can't be found - I checked that the ovrservice is running and it is.

I've also tried as many ways as I can think of to get Technolust and some other games that are Unity based to load in VR without any luck.  Technolust just loads the 2d non-vr version on the desktop, and darknet just crashes at startup.

Any ideas what I should do to help debug my system since others seem to have been more successful with these types of games using the injector and patches that have been around for a while?  For riftcat I'm able to run a lot of other SteamVR / Vive content without any difficulty.

**Comment by LibreVR** [comment] 2016-05-19 14:27
Make sure you're running [version 0.5.1](https://github.com/LibreVR/Revive/releases/tag/0.5.1) and then try starting the Revie Dashboard and starting a game.

**Comment by LibreVR** [comment] 2016-05-19 14:32
Also, do note that Vridge is not officially supported in Revive.

**Comment by wissper** [comment] 2016-05-19 14:54
yeah I know... my hopes are tempered with very low expectations at this point - trying to get two beta softwares to play nice is touch and go at best - I'm grateful for any thoughts you have on it though.

I tried to run Lucky's Tale, which I know was running before on riftcat using revive 0.4 I guess and hasn't been touched between versions.  It crashed like the others with this output log pointing to an F:/dd/ drive - which I do not have in my system since my drives are C: D: and S:.  Any idea where this might have come from, or if it is related to the crash?  Now that I look closer, none of those paths exist on my system.

========== OUTPUTING STACK TRACE ==================

0x00007FFE0AD5430D (LibRevive64_1) ovr_GetAudioDeviceInGuidStr
0x00007FFE0AD54388 (LibRevive64_1) ovr_GetAudioDeviceInGuid
0x00007FFE0ACC341A (OVRPlugin) ovrp_GetNativeSDKPointer
0x00007FFE0ACC0619 (OVRPlugin) ovrp_GetNativeSDKPointer
0x00007FF7F60ED499 (LT) [c:\buildslave\unity\build\runtime\vr\oculus\vrdeviceoculus.cpp:150] VRDeviceOculus::Initialize 
0x00007FF7F60E7F4E (LT) [c:\buildslave\unity\build\runtime\vr\vrmodule.cpp:84] CreateVRModule 
0x00007FF7F5C469D2 (LT) [c:\buildslave\unity\build\runtime\gfxdevice\gfxdevicesetup.cpp:484] InitializeGfxDevice 
0x00007FF7F5CC8B3B (LT) [c:\buildslave\unity\build\runtime\misc\saveandloadhelper.cpp:271] InitializeEngineGraphics 
0x00007FF7F5CB3C8E (LT) [c:\buildslave\unity\build\runtime\misc\player.cpp:705] PlayerInitEngineGraphics 
0x00007FF7F5D807EA (LT) [c:\buildslave\unity\build\platformdependent\winplayer\winmain.cpp:853] PlayerWinMain 
0x00007FF7F61D97E8 (LT) [f:\dd\vctools\crt_bld\self_64_amd64\crt\src\crt0.c:275] __tmainCRTStartup 
0x00007FFE5CFD8102 (KERNEL32) BaseThreadInitThunk

========== END OF STACKTRACE ===========

**Comment by LibreVR** [comment] 2016-05-19 15:01
That is a duplicate of #34, but it's not related to your Dashboard crash.

Please download the new version and upload your logs if you want a solution for that.

**Comment by wissper** [comment] 2016-05-19 15:23
I just uninstalled Revive and reinstalled it... immediately got this error before running steam or steamvr.

Faulting application name: ReviveOverlay.exe, version: 0.0.0.0, time stamp: 0x573ca6bd
Faulting module name: ReviveOverlay.exe, version: 0.0.0.0, time stamp: 0x573ca6bd
Exception code: 0xc0000005
Fault offset: 0x0000000000003b2a
Faulting process id: 0x3a84
Faulting application start time: 0x01d1b1e1485e04ae
Faulting application path: C:\Program Files\Revive\ReviveOverlay.exe
Faulting module path: C:\Program Files\Revive\ReviveOverlay.exe
Report Id: d9d5f756-61dd-43d0-9770-7d76f9a920b4
Faulting package full name: 
Faulting package-relative application ID: 

I then loaded Steam, and SteamVR, then the Dashboard - I see no event ID for a crash, but I also don't see the dashboard inside VR.

**Comment by LibreVR** [comment] 2016-05-19 15:41
Closing this issue, since you don't seem to be interested in posting your logs.

**Closed by LibreVR** 2016-05-19 15:41 UTC

**Comment by wissper** [comment] 2016-05-19 18:06
Sorry for the delay - I had a Bar review class to attend.  What log files do you want? The Revive logs only contained the info pasted here:

 Injector log:

Launched injector with: "C:\Program Files\Oculus\Software\iris-vr-technolust\ReviveInjector_x86.exe" "C:\Program Files\Oculus\Software\iris-vr-technolust\Technolust.exe"
Creating process: C:\Program Files\Oculus\Software\iris-vr-technolust\Technolust.exe
Failed to create process

Overlay log:

Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///S:/games/Steam/steamapps/common/SteamVR/
Oculus directory: file:///C:/Program Files/Oculus/

**Comment by LibreVR** [comment] 2016-05-19 19:08
I was just frustrated that you kept posting crash info instead of the log files I asked for.

Anyway, that info is useful, the game won't even start. That is an issue outside of Revive.

**Comment by wissper** [comment] 2016-05-19 19:16
That's what I was afraid of... I was just putting up all the info I had available to work with at the time... sorry about that.  I'll keep an eye on the logs to see what's going on with them... I think it's something in steam that's keeping games from loading in VR at all.. some kind of conflict that's forcing an exit state right at the start of the load process.

**Comment by LibreVR** [comment] 2016-05-19 21:24
Oh you're running it through Steam, that's not supported exactly because of the issue you describe. See issue #80.

**Comment by gormanj** [comment] 2016-05-19 21:31
Technolust looks great and I'd love to get that working, Please read on... I've gotten many games to work by using the current version of Revive AND replacing the OVRPlugin in the data>plugins folder of the game with the plugin for Unity from Oculus (https://developer.oculus.com/downloads/), Note that the proper Unity 5.3 32bit/64bit plugin needs to be used (usually 32bit), One way to find if an app is 32 bit is to check task manager when it is running (if you can get a startup launcher). Task Manager will report 32 bit, if it does not, then it is 64bit. I am not sure why, but replacing the OVRPlugin with the one from 5.3 folder and choosing the proper 32/64 bit version make many, many games work (over 70 that I have tried). I hope it works for you.

**Comment by LibreVR** [comment] 2016-05-19 22:07
Technolust already works if you have the Oculus Home version, I've tried it myself. What you're describing it the workaround to get Oculus Runtime 0.8 games working. But Technolust is an Oculus Runtime 1.3 game, so it should work out of the box.

**Comment by gormanj** [comment] 2016-05-19 22:32
Awesome. I'll buy it!
