### ISSUE TITLE
Revive jitter

### ISSUE THREAD

**Issue by Crusage** [LibreVR/Revive#584] opened 2017-04-24 20:13 UTC
All my normal htc vive games do not jitter at all. But when i play games with revive, like superhot, it jitters. Its still playable. Just wondering if someone knows a fix

**Comment by Armada651** [comment] 2017-04-25 13:59
Can you try disabling asynchronous reprojection?

**Comment by CarrotSurvivor** [comment] 2017-04-25 15:45
Yea the new update added some weird jitter to all games I think

**Comment by Monkeychow01** [comment] 2017-04-25 16:19
As a temp fix do what he says about disabling asynchronous reprojection in the settings in SteamVR.   At least for Giant Cop it did help a bit.   Not perfect, but it helped.   Not sure how it will do with other games, but give it a shot to see if it fixes your issue temporarily until he gets to the bottom of what's up.

**Comment by ionic234** [comment] 2017-05-01 14:00
I'm getting the same problem in Wilson's Heart. Have turned off asynchronous reprojection and rolled back  to 1.1 but neither have helped with the problem. I doubt its a performance issue as i have a 1080 and an i7-6700k, checked the frame timing and everything seems to be hovering around the 50% mark with no spikes when  the jitters occur.

**Comment by Armada651** [comment] 2017-05-01 14:01
This can happen due to changes in pose predictions, try version 1.0.6.

**Comment by ionic234** [comment] 2017-05-01 14:15
Thanks for your quick response. I tried 1.0.6 but the game wont run on that version. If i try it from the revive dashboard a throbber appears but nothing else happens. I've also had no luck trying to use the inject method to open the .exe.

**Comment by Armada651** [comment] 2017-05-01 14:17
Can you go back to version 1.1 and confirm that the jitter also visible on your desktop monitor? Could you capture a video of it?

**Comment by ionic234** [comment] 2017-05-01 14:25
Looks like the jitters only happen in the HMD.

**Comment by Armada651** [comment] 2017-05-01 14:26
Can you describe what the jitter looks like?

**Comment by ionic234** [comment] 2017-05-01 14:29
A periodic snap. It looks like the left eye and right eye images aren't aligning up properly as i move my head.

**Comment by Armada651** [comment] 2017-05-01 14:32
Well, a periodic "snap" could be caused by the 1.1 update. However that should affect the left and right eye equally.

**Comment by ionic234** [comment] 2017-05-01 14:38
its defiantly an issue with the stereopsis. If i move my head fast enough i can see duplicate objects. I also tried lowering the quality setting but that didn't improve anything.

**Comment by ionic234** [comment] 2017-05-01 14:42
Actually i take that back. I still get jittering in the image even if i play with one eye closed.

**Comment by Armada651** [comment] 2017-05-01 14:56
Try this build of Revive, just extract it in the `C:\Program Files\Revive` folder: 
[Revive.zip](https://github.com/LibreVR/Revive/files/968062/Revive.zip)

**Comment by CarrotSurvivor** [comment] 2017-05-01 15:09
The guy needs to just enable always on reprojection.

**Comment by Armada651** [comment] 2017-05-01 15:12
@CarrotSurvivor "Always on reprojection" is not some magical fix-all. It has serious downsides and it is definitely **not** something I want to rely on.

**Comment by ionic234** [comment] 2017-05-01 15:15
The game crashes when i run it now. I think my virus software took a disliking to one of the files. Unfortunately It's getting late now and i have to go to bed. Thanks for all your help, shame we couldn't get it to work but ill be back on the forum tomorrow.

**Comment by CarrotSurvivor** [comment] 2017-05-01 16:00
Dude, I don't actually turn on always on reprojection..... I just tick off the check box and it results in serious performance improvements. You are supposed to actually restart steam VR when you check it off fornit to work but I don't do that. I just check off the box after games start and it makes serious improvements.

**Comment by Armada651** [comment] 2017-05-01 16:02
@CarrotSurvivor You don't need to restart to turn on Always-on Reprojection. I know OpenVR-AdvancedSettings says so, but that just not true. So you are playing with Always-on Reprojection if you do that.

I have performance reports that clearly show Always-on Reprojection is applied without restarting SteamVR or restarting the game. Just like all the other reprojection settings.

**Comment by Usurper1** [comment] 2017-05-02 00:39
Did we get the the bottom of the "snapping" issue in Wilsons Heart...? I have the same rig as the guy above, and am having the same issue. Any final verdict about it,...?

**Comment by ionic234** [comment] 2017-05-02 00:49
Always on reprojection will remove the jitters but at the cost of tracking precision. Im not a VR engineer so this might be wrong but as i understand it the vive only allows gpu calls to happen 2ms before the draw so theres only ever 2ms between the position the controllers were captured at what appears on screen. 2ms isnt a lot of time for a gpu to do stuff so always on reprojection allows the gpu to do its stuff early but this increases the lag between when the position data capture and the screen draw.

**Comment by Usurper1** [comment] 2017-05-02 00:59
Ok. Hmmm. 

I actually did what @Armada651 said, and installed the version of Revive that he suggested. It got rid of the jitters/snapping for the most part if I also disable Asynchronus Reprojection.

It now feels a little off though...like, theres not alot of snapping, or jitters, but there seems to be a lag that feels disorienting. Maybe its all in my head though. Its a huge improvement over what I was dealing with before. So thank you.

**Comment by Armada651** [comment] 2017-05-02 12:29
I have another experimental build of Revive, just extract it in the `C:\Program Files\Revive` folder, replacing the files: [Revive.zip](https://github.com/LibreVR/Revive/files/970385/Revive.zip)

This version should fix the jitter without the need for Always-on reprojection. Keep Async reprojection off though, it doesn't work very well with games running in Revive.

**Comment by Usurper1** [comment] 2017-05-02 13:09
Cool. Thanks. Ill let you k ow how it works.

**Comment by Usurper1** [comment] 2017-05-03 01:28
I tried it. Its overall more smooth...but like I said up there, theres now a lag in my head movements. Like, the world moves when I move my head around. For instance, if I nod my head up and down, the world kinda bounces and bobs with it. Theres no jitter or snapping...but a slow lag of sorts.

**Comment by Usurper1** [comment] 2017-05-03 01:28
Can you link a donations page...

**Comment by Armada651** [comment] 2017-05-10 10:47
Found the problem, I had an old piece of test code in that experimental build that added an extra frame of latency in the prediction. That should be fixed in the next version.

**Comment by Armada651** [comment] 2017-05-10 10:53
Please test this release: https://github.com/LibreVR/Revive/releases/tag/1.1.2

**Closed** 2017-08-16 18:22 UTC
