### ISSUE TITLE
Games launch to desktop, but not HMD

### ISSUE THREAD

**Issue by roulbs** [LibreVR/Revive#486] opened 2017-02-06 07:24 UTC
I don't have any virus protection. My Revive is up to date.

When I launch superhot when I'm in VR, for a split second, it'll say "Launching superhot" and have the animation it looks like when you launch any game when you have your headset on, but then it just goes away. 

Also when it goes away, my trigger will still be pressed down (from when I pressed it to select the game I wanted to start up), so I'll have to click it again to stop scrolling, and there'll be a refresh wheel in the middle of the revive tab that doesn't go away.

And in the SteamVR box with the green statuses of all the components, it'll say "Launching SUPERHOT VR" but it totally failed at doing so. 

Thanks for reading!

**Comment by Armada651** [comment] 2017-02-15 16:06
Can you post your logs from `%APPDATA%\Revive`? Just enter that into the explorer address bar, rename them to .txt files and drag them in the comment box below.

**Comment by Armada651** [comment] 2017-02-19 10:23
Probably a duplicate of #478.

**Closed by Armada651** 2017-02-19 10:23 UTC
