### ISSUE TITLE
Oculus Remote emulation is broken

### ISSUE THREAD

**Issue by eximer168** [LibreVR/Revive#367] opened 2016-12-10 03:41 UTC
Using single vive controller was able to get past photo (trick seems to be to require swiping motion across pad) but get stuck at point were BACK (menu button, on vive controller) should activate the next scene. Keyboard input, and other controller combinations seem to have no effect. Various YOUTUBE's seem to suggest this worked at some point, perhaps not any more. Please advise -- I wouldn't bother if this wasn't such a beautiful game.

**Comment by LibreVR** [comment] 2016-12-10 10:36
Make sure you have only one Vive controller turned on turn off the other one. Then the Vive controller becomes an Oculus Remote with the following mapping (using paint again):

![remote](https://cloud.githubusercontent.com/assets/18057864/21072737/716d1bc2-bec4-11e6-816a-a0b44c326663.png)

**Comment by eximer168** [comment] 2016-12-10 12:19
Yes, I did use only one controller Using, FARLANDS v1.02 and current rev Revive v1.03 (3 days ago). No change.

The good news is that reverting Revive v1.02 works! Key-controls notably easier to use, and also the swipe-hints are now appearing in the center circle (A in the above picture). Thanks for making this available!

**Comment by LibreVR** [comment] 2016-12-10 13:25
I see, this is a 1.03 regression because it changed the controller activity detection. I will work on a patch.

**Comment by Armada651** [comment] 2017-01-06 15:48
The problem is not were I expected it, but it is now fixed in commit 1d849d27ad7306449b9bda835795c2e290659c85.

**Closed by Armada651** 2017-01-06 15:48 UTC
Labels: regression

**Comment by eximer168** [comment] 2017-01-06 16:08
You are awesome and make the world a better (and more) fun place.
