### ISSUE TITLE
Robo Recall not working since update 1.5

### ISSUE THREAD

**Issue by strueli** [LibreVR/Revive#841] opened 2017-12-05 12:48 UTC
Robo Recall did an (automatic) update today to V1.5, and now it seems to be not working anymore.
It won't start up, but gets the 'unreal engine crashed' message

**Comment by g3n3r1cL10n** [comment] 2017-12-05 18:47
Here too. On Revive Stable Version 1.1.14 i can´t select robo recall anymore from the ReVive Dashboard, on Third Beta 1.2.0 i can select Robo Recall in the Dashboard, but it just doesn´t start. No error message or whatsever. On Robo Revive, i get an crash message from the unreal engine. But on the "normal" revive dashboard, it just doesn´t start at all.

**Comment by Armada651** [comment] 2017-12-06 16:07
Duplicate of #840

**Closed by Armada651** 2017-12-06 16:07 UTC
