### ISSUE TITLE
OculusMedium.exe has stopped working.

### ISSUE THREAD

**Issue by impostorcalledoz** [LibreVR/Revive#1025] opened 2018-07-01 04:57 UTC
Everytime i try to open **Medium**, it crashes saying **OculusMedium.exe has stopped working** and **windows is looking for a solution**. Every other oculus app works fine through **Revive**. I have changed the library directory through **regedit.exe** and have **updated my monitor and graphics card drivers.** Uninstalled and reinstalled too. Nothing works. This is really frustrating -( I'm attaching my **crash logs**.
[medium crash logs.txt](https://github.com/LibreVR/Revive/files/2152427/medium.crash.logs.txt)

**Comment by Armada651** [comment] 2018-07-01 10:53
Duplicate of issue #1022.

**Closed by Armada651** 2018-07-01 10:53 UTC
