### ISSUE TITLE
Damaged Core - new graphical and gameplay issues

### ISSUE THREAD

**Issue by jiminnyv** [LibreVR/Revive#383] opened 2016-12-14 14:08 UTC
I'm a huge supporter of the Revive project and greatly indebted the great work that you've been doing.

However, I wanted to feedback some issues I've encountered with Damaged Core running on my HTC Vive.

Initially the game runs perfectly, however there seems to be a graphical issue once the zoom/focus mechanic is introduced in the tutorial where instead of zooming, the image just becomes heavily pixellated, making this key gameplay feature unplayable.

The second issue I have encountered is immediately after the tutorial section when you find yourself on a ledge outside your crashed ship in the game and need to teleport into a nearby robot. Unfortunately no matter what I try the positioning of the robot appears to be too far away to teleport to and I find myself stuck on the ledge unable to progress in the game. 

Anybody else had these issues?

FYI, I am playing on an i7 6700 with GTX 1080 and a lot of RAM.

**Comment by LibreVR** [comment] 2016-12-14 14:20
Sounds like you're running an older version. The zoom bug has long since been fixed. Unless there's been a regression.

**Comment by jiminnyv** [comment] 2016-12-14 14:44
Thanks for the quick response. I thought I was on the latest version, but I'll try updating and come back to you if the issue persists.

**Comment by kvdv99** [comment] 2016-12-14 21:00
I would love a way of seeing the actual version you're running of Revive. Maybe in the dashboard overlay, above the game panels?

**Comment by LibreVR** [comment] 2016-12-14 21:44
You can check it when you use "Check for updates" in the tray icon menu.

**Comment by kvdv99** [comment] 2016-12-14 22:43
Well, don't know if you remember, but I once started a thread about this :  everything is working for me, except one thing : I never get to see the Revive tray icon, still don't. You thought I was still using an old version, but I don't. I even renamed the Revive directory and re-installed the latest 1.x version, everything worked, but still no tray icon :(

**Comment by kvdv99** [comment] 2016-12-14 22:50
Is there any other way for me to check the version (without the tray icon)?

**Comment by kvdv99** [comment] 2016-12-14 22:51
I just noticed that the revive.vrmanifest file is always 0 Kb, is that normal?

**Comment by LibreVR** [comment] 2016-12-14 23:20
No, that means that no Oculus games were detected, so the dashboard most likely won't work. This may be caused by installing two versions of Revive at the same time in different locations.

I very much doubt that you don't have a tray icon, it's most likely just hidden under the popup button:

![image_3](https://cloud.githubusercontent.com/assets/18057864/21205378/daaedfd4-c253-11e6-87bc-468562f7e72e.jpg)

**Comment by kvdv99** [comment] 2016-12-15 00:44
The strange this is that the dashboard does work. Just to be sure I now just openend a couple of Oculus games and they ran fine.  Then I re-checked the files :  revive.vrmanifest is still 0 Kb, and app.vrmanifest is 1 Kb.  

Nope, the sys tray icon is not hidden. I just re-checked again. 
 Is there maybe a (Windows background) process I can check to verify that the sys tray icon isn't working/running ?

**Comment by nateev** [comment] 2016-12-15 08:16
I also do not have the tray icon, revive is working fine.

**Comment by LibreVR** [comment] 2016-12-15 09:25
@kvdv99 If your manifest is 0kb and you do not have a tray icon, then another older version of Revive is installed on your system somewhere which blocks the newer version from starting.

@nateev If you don't have a tray icon, you are running an older version, simple as that.

**Comment by nateev** [comment] 2016-12-15 09:40
I run 1.0.3 updated the day i came out.

**Comment by kvdv99** [comment] 2016-12-15 09:40
I believe you.  It would explain why some (newer) games aren't working for me, but do run for other people.  

I tried closing SteamVR, renaming the Revive folder to "d:\revive_OLD" and then install 1.0.3 and reboot the pc.   So how can the old version still be running? And more importantly, how can I stop this?

Can I completely remove everything Revive related, and then install from scratch, without losing imporant stuff like my Oculus library?

Thanks for the support!

**Comment by LibreVR** [comment] 2016-12-15 10:16
@kvdv99 You can always reinstall Revive without losing anything. You can see a complete list of every application registered with SteamVR in the file `C:\Program Files (x86)\Steam\config\appconfig.json`. So please post the contents of the file here so we can see which versions of Revive are installed.

**Comment by LibreVR** [comment] 2016-12-15 10:23
I've cleaned up this report of unrelated comments, because @kvdv99 introduced a problem in this issue that has no relation to the report here.

**Comment by Dragoboss** [comment] 2018-12-16 12:03
Closing this as no response was posted for two years.

**Closed by Dragoboss** 2018-12-16 12:03 UTC
Labels: regression, revive, wontfix
