### ISSUE TITLE
Dead And Buried Voip Issue

### ISSUE THREAD

**Issue by BubsonHD** [LibreVR/Revive#351] opened 2016-12-06 21:54 UTC
Potential Issue with Voip, I sound fine in any other games I play but people are report that I am coming through either very muffled or low pitched voice.

**Comment by LibreVR** [comment] 2016-12-06 23:18
Sorry, but Revive doesn't affect audio other then device selection. (Which works since people do hear you)

**Comment by BubsonHD** [comment] 2016-12-06 23:20
Ok Thanks, Sorry just trying to be as helpful as I can.

**Comment by LibreVR** [comment] 2016-12-06 23:25
Reports are always welcome, it's not a problem if your issue is closed as invalid.

**Comment by Drewwit** [comment] 2016-12-21 20:31
Hey Bubson, did you ever figure this out? I am having the exact same issue, only affecting Dead and Buried. LibreVR I know its nothing to do with Revive, but is it ok to continue the discussion here?

**Comment by Drewwit** [comment] 2016-12-21 22:48
SO when I live monitor the audio coming from my Vive mic it sounds perfect. Yet in game people are telling me that I sound like i'm using a voice changer. Almost like this one specific game has a unique way of handling the rift mic, and when its not getting that, its messing up.

**Comment by arthurjdam** [comment] 2017-01-10 05:33
Can report similar behavior from both sides (player and listener) that this seems to be the case. It sounds like the frequency recorded is way lower than that being played back. Unsure about what's the actual cause yet, though.

**Comment by lghtanddrk** [comment] 2017-01-10 14:19
I'm having the same issue with Dead and Buried but the other players sound fine.  I only have this issue when playing through Revive.  I previously played Rip Coil and the Oculus version of Rec Room and didn't have this issue but I am now on Revive 1.04 and installed OpenVR Advanced Settings the same day.  If it's not the latest version of Revive then I think the issue may be with OpenVR.  Are you using OpenVR Advanced Settings too? If not, then maybe it's just the latest version of Revive.

One of the things I noticed is that OpenVR does not see the same microphone settings that are in SteamVR and I had to change the device in Windows Sound Options.  I have been trying to troubleshoot this with the OpenVR dev but haven't got far enough yet to see what the solutions is.

**Comment by lghtanddrk** [comment] 2017-01-10 14:26
Just found this in another thread: "Dead and Buried has had the microphone issues with previous Revive versions as well, but according to crossVR it is not caused by Revive itself but rather an ingame bug that only affects Vive users. We need to get a patch from the Dead and Buried developers themselves to get it fixed, however, I doubt they are going to do any fixes that only affect Vive users :/"

**Comment by Armada651** [comment] 2017-01-10 15:54
I'm still not convinced this is something that can be fixed in Revive, it's still worth some more research so I'll reopen this issue.

**Comment by Lucid360** [comment] 2017-01-16 10:18
+1 :)

Have met the occasional user sounding super weird mostly inaudible speech and they've been Revive users.m and people can't hear what I say when I'm using Revive because of severe muffling/pitching of audio... sounds like talking from the pits of hell...

Using my Rift everything works great.

**Comment by Armada651** [comment] 2017-01-16 10:21
Are there any other Oculus games that use voice chat? Can you reproduce the issue in those games?

**Comment by Lucid360** [comment] 2017-01-18 14:18
Hej Jules!

I tried playing Ripcoil, the Unspoken & Bigscreen thorugh Revive just now, and it seems my audio is fine in those titles... Only one affected so far is Dead and Buried.

/Daniel

**Comment by Chupacabra1989** [comment] 2017-02-18 13:06
can confirm with lucid. also got this issue. thx for take a look :)

**Comment by Lucid360** [comment] 2017-02-23 01:14
..so this is being adressed by the developers:

"Just this week I played Dead and Buried with Vive users. I could tell they were Vive users,” Rubin said. According to him, he knew they were Vive users because their in game voice chat was being distorted by the “hacks they were using.” Rather than condemning these actions, Rubin claims that, “we have done nothing to stop this right now and in fact members of the team in Menlo Park are working now to fix the mic problem.“

Source: https://uploadvr.com/jason-rubin-vr-exclusivity-open-platform-never-created-one-company/

**Comment by Armada651** [comment] 2017-02-23 01:50
Great news, if it ends up being a problem with Revive after all I hope they'll let me know.

**Comment by SimplexPL** [comment] 2017-07-21 10:02
It's bug in the game, Rubin promised a fix in July and never delivered. Here's a workaround:
https://www.reddit.com/r/Vive/comments/5s30v3/how_to_fix_your_voice_in_dead_and_buried/

**Comment by TesseractCat** [comment] 2018-11-18 21:38
I'm having a similar issue in Echo VR, many people are telling me that my voice sounds like I'm using a voice changer. I'm not sure if this is only for Echo VR as I don't own any other games in the Oculus store with VoIP. I know it doesn't happen in SteamVR games as nobody comments on my voice in Pavlov VR.

**Comment by Dragoboss** [comment] 2018-12-16 12:01
It has something to do with Vive itself rather than Revive and the way some games handle voice.

**Closed by Dragoboss** 2018-12-16 12:01 UTC
Labels: help wanted
