### ISSUE TITLE
The Climb VR - Choppy

### ISSUE THREAD

**Issue by avancleef** [LibreVR/Revive#482] opened 2017-02-04 09:13 UTC
Heya,

I know there are lots of posts about this already but they dont help me as I cannot get it fixed. My PC does not have the best hardware, but it should be able to run the game without any problems. Unfortunately when I dont move my head, everything looks pritty fine, when I do move my head eveything is jumping and doing all kinds of strage stuff. Game is literally unplayable now on my HTC Vive.

Intel i5 3570k 3.40GHz (overclocked to 4GHz)
MSI GTX980 TI Lightning 6GB
16GB DDR3 highest speed (Corsair)
Windows 8.1 Pro
SSD 550 / 550

Does anyone know how to fix this? the game is pritty awesome but when I move my head everything is jumpy, This is BTW the only game that I am having this problem with. I mean, I can play Battlefield 1 with all settings on ultra and the highest possible AA and SS and I have literally zero lag with my system so... I should be able to play this as well i'd recon? :)

Best regards

**Comment by mapotter99** [comment] 2017-02-04 10:23
Try disabling Asynchronus Reprojection in the SteamVR settings. Make sure your render target multiplier in "The Climb" graphics settings is set to 1.2 or less (1.2 is the max those of us with GTX 1070's and 1080's can use, so adjust accordingly). Turn off the low frame rate warnings. 

I'm not a developer, and I have nothing to do with Revive development, but based on things others have said and my own experimentation, I don't think this is a Revive-specific issue. There are multiple reports of "The Climb" performance issues in the Oculus forums. That said, SteamVR does not yet have an ASW equivalent, so that may be making things worse.

**Comment by avancleef** [comment] 2017-02-04 11:47
Thanks for your reply, will try that right away and let you know if that worked :)

**Comment by avancleef** [comment] 2017-02-04 12:16
Well, that did work indeed but im down to 45FPS now.. also, I cannot see the (number) at resolution slider... there simply is no number saying what resolution I picked... same for some other settings :)

**Comment by calibban** [comment] 2017-02-10 10:27
the problem with the climb on revive is the tracking,the camera don't follow the headset very well and there is a lot of latency.
same problem with unspoken.

**Comment by Wowfunhappy** [comment] 2017-02-10 21:52
> That said, SteamVR does not yet have an ASW equivalent, so that may be making things worse.

Neither did Oculus at the time The Climb was released, so it shouldn't matter.

**Comment by Armada651** [comment] 2017-02-12 17:23
Duplicate of issue #403.

**Closed by Armada651** 2017-02-12 17:23 UTC
